### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by baole-lunex** [paypal/PayPal-Java-SDK#101]
Hi all, 

This is my code:

CreateFromRefreshTokenParameters params = new CreateFromRefreshTokenParameters();
    params.setGrantType("refresh_token");
    params.setScope("openid"); // Optional
    params.setClientID(AppConfig.paypalAppClientId);
    params.setClientSecret(AppConfig.paypalAppClientSecret);
    Map<String, String> configurationMap = new HashMap<String, String>();
    configurationMap.put(Constants.MODE, AppConfig.paypalMode);
    APIContext apiContext = new APIContext();
    apiContext.setConfigurationMap(configurationMap);
    tokeninfo.setRefreshToken(refreshToken);
tokeninfo.createFromRefreshToken(apiContext, params);

It's alway create exception 404 not found

This is log

ERROR [2015-04-28 11:17:14,425] com.lunex.service.merchantgw.PaypalService: Error code : 404 with response : https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice
! java.io.FileNotFoundException: https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice
! at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.7.0_60]
! at java.net.HttpURLConnection.getResponseCode(Unknown Source) ~[na:1.7.0_60]
! at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source) ~[na:1.7.0_60]
! at com.paypal.base.HttpConnection.execute(HttpConnection.java:95) ~[rest-api-sdk-1.2.2.jar:1.2.2]
! ... 55 common frames omitted
! Causing: java.io.FileNotFoundException: https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice
! at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_60]
! at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_60]
! at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_60]
! at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.7.0_60]
! at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[na:1.7.0_60]
! at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source) ~[na:1.7.0_60]
! at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_60]
! at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source) ~[na:1.7.0_60]
! at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[na:1.7.0_60]
! at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[na:1.7.0_60]
! at com.paypal.base.HttpConnection.execute(HttpConnection.java:96) ~[rest-api-sdk-1.2.2.jar:1.2.2]
! ... 55 common frames omitted
! Causing: com.paypal.base.exception.HttpErrorException: Error code : 404 with response : https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice
! at com.paypal.base.HttpConnection.execute(HttpConnection.java:126) ~[rest-api-sdk-1.2.2.jar:1.2.2]
! at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:403) ~[rest-api-sdk-1.2.2.jar:1.2.2]
! ... 54 common frames omitted
! Causing: com.paypal.base.rest.PayPalRESTException: Error code : 404 with response : https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice
! at com.paypal.base.rest.PayPalRESTException.createFromHttpErrorException(PayPalRESTException.java:66) ~[rest-api-sdk-1.2.2.jar:1.2.2]
! at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:410) ~[rest-api-sdk-1.2.2.jar:1.2.2]
! at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:261) ~[rest-api-sdk-1.2.2.jar:1.2.2]
! at com.paypal.api.openidconnect.Tokeninfo.createFromRefreshToken(Tokeninfo.java:324) ~[rest-api-sdk-1.2.2.jar:1.2.2]
! at com.lunex.service.merchantgw.PaypalService.createAccessTokenFromRefreshToken(PaypalService.java:754) [classes/:na]
! at com.lunex.service.merchantgw.PaypalService.createFuturePayment(PaypalService.java:805) [classes/:na]
! at com.lunex.web.merchantgw.PaypalRequestResource.auth(PaypalRequestResource.java:123) [classes/:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_60]
! at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_60]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_60]
! at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_60]
! at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.18.1.jar:1.18.1]
! at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185) [jersey-server-1.18.1.jar:1.18.1]
! at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.18.1.jar:1.18.1]
! at io.dropwizard.jersey.guava.OptionalResourceMethodDispatchAdapter$OptionalRequestDispatcher.dispatch(OptionalResourceMethodDispatchAdapter.java:37) [dropwizard-jersey-0.7.0.jar:0.7.0]
! at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.18.1.jar:1.18.1]
! at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.18.1.jar:1.18.1]
! at com.sun.jersey.server.impl.uri.rules.ResourceObjectRule.accept(ResourceObjectRule.java:100) [jersey-server-1.18.1.jar:1.18.1]
! at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.18.1.jar:1.18.1]
! at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.18.1.jar:1.18.1]
! at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [jersey-server-1.18.1.jar:1.18.1]
! at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [jersey-server-1.18.1.jar:1.18.1]
! at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-server-1.18.1.jar:1.18.1]
! at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-server-1.18.1.jar:1.18.1]
! at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [jersey-servlet-1.18.1.jar:1.18.1]
! at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) [jersey-servlet-1.18.1.jar:1.18.1]
! at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) [jersey-servlet-1.18.1.jar:1.18.1]
! at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet-3.0.0.v201112011016.jar:na]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [dropwizard-jetty-0.7.0.jar:0.7.0]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515) [jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [jetty-servlets-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:295) [jetty-servlets-9.0.7.v20131107.jar:9.0.7.v20131107]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:127) [dropwizard-jetty-0.7.0.jar:0.7.0]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [dropwizard-servlets-0.7.0.jar:0.7.0]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1486) [jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519) [jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448) [jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:173) [metrics-jetty9-3.0.1.jar:3.0.1]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [dropwizard-jetty-0.7.0.jar:0.7.0]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:92) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:162) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.server.Server.handle(Server.java:446) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [jetty-io-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
! at java.lang.Thread.run(Unknown Source) [na:1.7.0_60]

Please help me

**Comment by juwlee** [comment]
@baole-lunex have you tried [curl](https://developer.paypal.com/webapps/developer/docs/api/#grant-token-from-refresh-token)? The error indicates the URL does not exist, which seems to work fine on my end.

**Comment by baole-lunex** [comment]
Yes, i had tried curl, but it not work

< HTTP/1.1 404 Not Found
< Date: Tue, 28 Apr 2015 11:03:59 GMT
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Set-Cookie: Apache=10.72.128.11.1430219040597475; path=/; expires=Thu, 20-Apr-45 11:04:00 GMT
< Vary: Accept-Encoding
< Content-Length: 0
< Content-Type: text/html

**Comment by baole-lunex** [comment]
Oh my god, i have just tried it again. It work. I don't know why, yesterday, Paypal response 404 not found for me. Maybe it a sometime error from paypal

Thank juwlee
