### ISSUE TITLE
Agreement create is broken

### ISSUE THREAD

**Issue by kangsy** [paypal/PayPal-Java-SDK#105]
Agreement sends the the whole data structure of plan on creation, but the rest-api expects only the plan-id:

"name":"VALIDATION_ERROR",
"details":[{"field":"plan","issue":"Invalid Fields passed in plan. Pass only a valid plan-id."}]

**Comment by juwlee** [comment]
@kangsy can you provide an example of the problem?

**Comment by kangsy** [comment]
Because I am using clojure, I can't give you a concrete code to reproduce, but I think the problem is quite easy to describe:

The agreement object has a plan field of type com.paypal.api.payments.Plan https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/api/payments/Agreement.java#L77

If you call create() on a agreement object, it encodes the whole object to json and posts it to server
https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/api/payments/Agreement.java#L389

At that point your agreement json looks like this:
```javascript
{
  "name": "Productname //TODO",
  "description": "Description //TODO",
  "start_date": "2015-07-02T17:08:41Z",
  "payer": {
    "payment_method": "paypal"
  },
  "plan": {
    "id": "P-XXX",
    "name": "Produktname //TODO",
    "description": "Description //TODO",
    "type": "FIXED",
    "state": "CREATED",
    "create_time": "2015-06-17T17:08:39.930Z",
    "update_time": "2015-06-17T17:08:39.930Z",
    "payment_definitions": [
      {
        "id": "PD-XXX",
        "name": "Name //TODO",
        "type": "REGULAR",
        "frequency_interval": "1",
        "frequency": "Month",
        "cycles": "12",
        "amount": {
          "currency": "EUR",
          "value": "464.9"
        },
        "charge_models": []
      }
    ],
    "merchant_preferences": {
      "setup_fee": {
        "currency": "EUR",
        "value": "0"
      },
      "cancel_url": "http://localhost:3000/shop/order/paypal/fail",
      "return_url": "http://localhost:3000/shop/order/approve-paypal",
      "max_fail_attempts": "0",
      "auto_bill_amount": "NO",
      "initial_fail_amount_action": "CONTINUE"
    },
    "links": [
      {
        "href": "https://api.sandbox.paypal.com/v1/payments/billing-plans/P-XXX",
        "rel": "self",
        "method": "GET"
      }
    ]
  }
}
´´´
But the api server expects the plan field to be plan-id only. Like this:
```{
...
  },
  "plan": {
    "id": "P-XXX",
    },
...
  }
}

**Comment by kangsy** [comment]
I have found a solution for me:
I create a new Plan object and copy only the id of the created plan. Then I pass this to the agreement via setPlan().
I am not sure, if this is the intended way, but at least it is a workaround for me.

**Comment by jaypatel512** [comment]
You are correct. As shown in the [developer docs for creating agreement](https://developer.paypal.com/webapps/developer/docs/api/#create-an-agreement), you are supposed to just pass the `"id"` field in `"plan"` object.
