### ISSUE TITLE
Adding business email

### ISSUE THREAD

**Issue by pmaingi** [paypal/PayPal-Java-SDK#110]
Hi there,
Am trying to add receiver email but am having challenges. Where do i need to edit in the rest api ?

List<Receiver> receivers = new ArrayList<Receiver>();
receivers.setEmail("business email");

**Comment by juwlee** [comment]
Hi @pmaingi you can set receiver email by calling [this method](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/api/payments/PayoutItem.java#L109). Please make sure you pass it to the payout objects in request.

See [this sample](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sample/src/main/java/com/paypal/api/payouts/servlet/CreateBatchPayoutServlet.java) or [this one](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sample/src/main/webapp/source/payouts/servlet/CreateBatchPayoutServlet.html) for creating payouts.

**Comment by pmaingi** [comment]
Thank you @juwlee .

**Comment by pmaingi** [comment]
Hi @juwlee 
One more question. 
Created Single Synchronous Payout (Failed), why do i keep on getting a 
Error code : 401 with response : {"error":"invalid_client","error_description":"The client credentials are invalid"}.
Note am running the sample application.

Thanks
