### ISSUE TITLE
CreditCard.list(APIContext apiContext, Map<String, String> containerMap) method not returning any credit card resource.

### ISSUE THREAD

**Issue by julius-litmus7** [paypal/PayPal-Java-SDK#112]
Upon calling the method CreditCard.list(APIContext apiContext, Map<String, String> containerMap), the credit cards added are not getting fetched. The API is returning the response but JSONFormatter.fromJSON sets only the count as 0.

**Comment by juwlee** [comment]
Thanks for pointing this out @julius-litmus7 . We will release a fix soon.

**Comment by juwlee** [comment]
The latest release should have the fix. Please give it a try and re-open if problem persists.
