### ISSUE TITLE
Lost configuration map

### ISSUE THREAD

**Issue by rkazanova** [paypal/PayPal-Java-SDK#113]
If I put configuration map and then call UserInfo using apiContext  it lost this configuration map:

APIContext ctx = new APIContext(accessToken);
ctx.setConfigurationMap(metaData);
Userinfo  userInfo = Userinfo.getUserinfo(ctx);

I created a fix but i cannot push to my custom branch and do pull request:

Fix in Userinfo.java:

/**
	 * Returns user details
	 * 
	 * @param apiContext
	 *            {@link APIContext} to be used for the call.
	 * @return Userinfo
	 * @throws PayPalRESTException
	 */
	public static Userinfo getUserinfo(APIContext apiContext)
			throws PayPalRESTException {
	        String accessToken = apiContext.getAccessToken();
		System.out.println("accessToken=" + accessToken);
		String resourcePath = "v1/identity/openidconnect/userinfo?schema=openid";
		String payLoad = "";
		APIContext apiContext = new APIContext(accessToken);
		HashMap<String, String> httpHeaders = new HashMap<String, String>();
		if (!accessToken.startsWith("Bearer ")) {
			accessToken = "Bearer " + accessToken;
		}
		httpHeaders.put(Constants.AUTHORIZATION_HEADER, accessToken);
		apiContext.setHTTPHeaders(httpHeaders);
		return configureAndExecute(apiContext, HttpMethod.GET,
				resourcePath, payLoad, Userinfo.class);
	}

	/**
	 * Returns user details
	 * 
	 * @param accessToken
	 *            access token
	 * @return Userinfo
	 * @throws PayPalRESTException
	 */
	public static Userinfo getUserinfo(String accessToken) throws PayPalRESTException {
		return getUserinfo(new APIContext(accessToken));
	}

**Comment by juwlee** [comment]
Hey @rkazanova thanks for reporting and suggestion. I will have a look and update this thread.

**Comment by juwlee** [comment]
Fixed in 86310a6b1d5891faa5a302c0c28e609cafccd07f
