### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by robertotru** [paypal/PayPal-Java-SDK#114]
Hi, in the readme it is reported the following line of code:
`OAuthTokenCredential tokenCredential = Payment.initConfig(new InputStream(new File("../sdk_config.properties")));`

I guess that it is not `Payment.initConfig`, but `PayPalResource.initConfig`.

Best
R

**Comment by juwlee** [comment]
@robertotru Any reason you think it should be PayPalResource instead of Payment class? [Payment extends PayPalResource](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/api/payments/Payment.java#L16).

**Comment by robertotru** [comment]
@juwlee Ah Ah! No, sorry, my mistake!

**Comment by juwlee** [comment]
No worries @robertotru :)
