### ISSUE TITLE
Release v1.2.6

### ISSUE THREAD

**Issue by stickfigure** [paypal/PayPal-Java-SDK#116]
Hi, sorry about creating an issue for this but I'm not quite sure how else to make the request. There is a critical bugfix for us in the 1.2.6 branch - how far away is a release?

**Comment by juwlee** [comment]
@stickfigure I am guessing you need the fix for #111, correct? I wonder if you have got a chance to try it out. It would be great if you could confirm that it works.

The next release will be rolled out in a few days. Stay tuned! :)

**Comment by stickfigure** [comment]
This turned out to be rather hard to test because it only happens when deployed in production (GAE server-side) and our build gets pushed from CI, not my desktop. But I got a snapshot of v1.2.6 pushed to maven central and it does seem to work.
