### ISSUE TITLE
UNKNOWN_ERROR

### ISSUE THREAD

**Issue by stickfigure** [paypal/PayPal-Java-SDK#119]
What is the process for debugging UNKNOWN_ERROR? I'm getting this when I try to execute a payment on sandbox (using the v1.2.6 branch):

{"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"26ed93663a8c0"}

**Comment by tomwhipple** [comment]
You'll need to contact [merchant support](https://www.paypal.com/mts) and provide this debug ID. It will also help them to have the request body as well.

Usually UNKNOWN_ERROR corresponds to a bug the error handling of the API you are calling.
