### ISSUE TITLE
NullPointerException in PaypalResponse (409)

### ISSUE THREAD

**Issue by crypti76** [paypal/PayPal-Java-SDK#120]
In Version 1.2.7 you've added mode-check in PaypalResponse (line 409)
The field configurationMap may not be initialized (because it's not merged with apiContext when calling execute), so there will be a NullPointerException when calling execute with apiContext.

Please correct.

**Comment by juwlee** [comment]
@crypti76 thanks for pointing this out. We will have a look. In the mean time, could you share how the exception is thrown? I wonder how the SDK is initialized and leaves `PayPalResource.configurationMap` empty.

**Comment by crypti76** [comment]
look at the following code:

        Map<String, String> sdkConfig = new HashMap<>();
        sdkConfig.put(Constants.MODE, CWXProperties.getInstance().getPaypalMode());
        String returnUrl = "someUrl";
        String cancelUrl = "someOtherUrl";
        String accessToken = new OAuthTokenCredential(userName, password, sdkConfig).getAccessToken();
		APIContext apiContext = new APIContext(accessToken);
		apiContext.setConfigurationMap(getConfigMap());

		Transaction transaction = new Transaction();
		transaction.setDescription("some description");
		// iterate over positions
		double totalSum = 100.0d;
		double articleSum = totalSum;

		Amount amount = new Amount();
		amount.setCurrency("EUR");
		amount.setTotal(String.format(Locale.ENGLISH, "%.2f", totalSum));
		Details details = new Details();

		details.setSubtotal(String.format(Locale.ENGLISH, "%.2f", articleSum));
		details.setHandlingFee("0.00"));			       
                details.setTax("0.00");

		details.setShipping(String.format(Locale.ENGLISH, "%.2f", 6.90d));
		amount.setDetails(details);

		transaction.setAmount(amount);
		List<Transaction> transactions = new ArrayList<Transaction>();
		transactions.add(transaction);

		Payer payer = new Payer();
		payer.setPaymentMethod("paypal");

		Payment payment = new Payment();
		payment.setIntent("sale");
		payment.setPayer(payer);
		payment.setTransactions(transactions);

		RedirectUrls urls = new RedirectUrls();
		urls.setReturnUrl(returnUrl);
		urls.setCancelUrl(cancelUrl);
		payment.setRedirectUrls(urls);

		Payment createdPayment = payment.create(apiContext);

When calling payment.create it will result in a PaypalRestException caused by a NullPointerException in PaypalResponse line 409.

Even I initialized the map and apiContext, the field configurationMap in PaypalResponse is null (checked via debugger).  

I used the code from the interactive integration guide of Paypal API Integration (https://devtools-paypal.com/guide/pay_paypal?interactive=ON&env=sandbox), so this should work.

**Comment by juwlee** [comment]
The fix was released in `v1.2.9`
