### ISSUE TITLE
"SDK Integration:"

### ISSUE THREAD

**Issue by richardrega** [paypal/PayPal-Java-SDK#121]
Shouldn't this say something like 'mvn install' etc.?

https://github.com/paypal/PayPal-Java-SDK has blank instructions.

https://github.com/paypal/PayPal-Java-SDK/commit/8ab49dfa181497658f7e4adf77e79c769e3ed641 Why was this deleted? Am I missing something?

**Comment by juwlee** [comment]
@richardrega It is recommended to pull dependencies from maven repo. It is SDK integration guideline, so the name still holds.

**Comment by richardrega** [comment]
@juwlee alright, I just don't have an official pom.xml for the project I'm working with.  Thanks for the quick response.

**Comment by juwlee** [comment]
@richardrega no problem! Java maven info is available [here](http://mvnrepository.com/artifact/com.paypal.sdk/rest-api-sdk). I will close this issue now.
