### ISSUE TITLE
NullPointerException when getting list of plans before any plans exist (status 204)

### ISSUE THREAD

**Issue by kcsaff** [paypal/PayPal-Java-SDK#124]
When the server returns a 204 response, the entity is null and this is not handled correctly; for example we get an exception thrown out of `Plan.list()` when an empty list would be more appropriate.  Similar problems likely exist elsewhere a 204 is returned.

**Comment by juwlee** [comment]
@kcsaff what exception did you get? Can you post the stack dump?

**Comment by juwlee** [comment]
@kcsaff code changes are committed and will be shipped in the next release.
