### ISSUE TITLE
Internal Service Error

### ISSUE THREAD

**Issue by SteveKelseyMocapay** [paypal/PayPal-Java-SDK#126]
I've been working with PayPal trying to resolve this but getting nowhere so I thought I would try here. 

We are getting an Internal Service Error whenever we try to do a sale transaction. Our entire flow is using Cordova/Phonegap (the Cordova plugin from PayPal) to get the token and then sending that to our server which gets the refresh token. That refresh token is then stored and used when a sale is authrorized by the consumer. The Cordova plugin and the call using this SDK to get the refresh token is working flawlessly. It is just when we try to do a sale that we get the Internal Service Error. Thanks in advance for any tips/pointers/ideas. 

    package com.mocapay;

    import java.util.ArrayList;
    import java.util.HashMap;
    import java.util.List;
    import java.util.Map;
    import java.util.Properties;
    import com.paypal.api.openidconnect.CreateFromRefreshTokenParameters;
    import com.paypal.api.openidconnect.Tokeninfo;
    import com.paypal.api.payments.Payer;
    import com.paypal.api.payments.Payment;
    import com.paypal.api.payments.RedirectUrls;
    import com.paypal.base.Constants;
    import com.paypal.base.rest.APIContext;
    import com.paypal.base.rest.OAuthTokenCredential;

    public class PaypalTest {
	
	public void doTest() {
		try {
	            String clientId = Your Client ID;
		    String clientSecret = Your Client Secret;
	
		    Map<String, String> configurationMap = new HashMap<String, String>();
		    configurationMap.put(Constants.CLIENT_ID, clientId);
		    configurationMap.put(Constants.CLIENT_SECRET, clientSecret);
		    configurationMap.put(Constants.ENDPOINT, Constants.REST_SANDBOX_ENDPOINT);
		    configurationMap.put(Constants.MODE, Constants.SANDBOX);
		    Properties properties = new Properties();
		    properties.putAll(configurationMap);
	        OAuthTokenCredential authTokenCredential = new OAuthTokenCredential(clientId,clientSecret,configurationMap); 
	        APIContext apiContext = new APIContext(authTokenCredential.getAccessToken());
		    apiContext.setConfigurationMap(configurationMap);
	    	Payment.initConfig(properties);
		    Tokeninfo info = new Tokeninfo();
		    info.setRefreshToken(Your Refresh Token);
		    CreateFromRefreshTokenParameters params = new CreateFromRefreshTokenParameters();
		    params.setClientID(clientId);
		    params.setClientSecret(clientSecret);

		    info = info.createFromRefreshToken(apiContext, params);
	        
	        com.paypal.api.payments.Amount paypalAmount = new com.paypal.api.payments.Amount();
	        paypalAmount.setCurrency("USD");
	        paypalAmount.setTotal("10");

	        com.paypal.api.payments.Transaction paypalTransaction = new com.paypal.api.payments.Transaction();
	        paypalTransaction.setDescription("creating a payment");
	        paypalTransaction.setAmount(paypalAmount);

	        List<com.paypal.api.payments.Transaction> transactions = new ArrayList<com.paypal.api.payments.Transaction>();
	        transactions.add(paypalTransaction);

	        Payer payer = new Payer();
	        payer.setPaymentMethod("paypal");
	        
	        Payment payment = new Payment();
	        payment.setIntent("sale");
	        payment.setPayer(payer);
	        payment.setTransactions(transactions);
	        RedirectUrls redirectUrls = new RedirectUrls();
	        redirectUrls.setCancelUrl("https://devtools-paypal.com/guide/pay_paypal?cancel=true");
	        redirectUrls.setReturnUrl("https://devtools-paypal.com/guide/pay_paypal?success=true");
	        payment.setRedirectUrls(redirectUrls);
	        apiContext = new APIContext(info.getAccessTokenWithType());
	        apiContext.setConfigurationMap(configurationMap);
	        Payment createdPayment = payment.create(apiContext);
	        System.out.println("Success! createdPayment = "+createdPayment.toJSON());
		} catch (Exception ex) {
			System.err.println(ex.getMessage());
			ex.printStackTrace();
		}
	}
	public static void main(String[] args) {
		PaypalTest test = new PaypalTest();
		test.doTest();
	}

    }

**Comment by tomwhipple** [comment]
First, you will want to make sure that your client id & secret match the environment you are testing against (live vs sandbox -- they are different!). You will also need to ensure that your return URLs match what you have configured in the [developer portal](https://developer.paypal.com/developer/applications/).

If that is not successful, you will want to collect the debug ID returned in the error response and [open a support issue](https://www.paypal-techsupport.com/app/ask/), as the support team is in a much better position to look at your requests and account settings.
