### ISSUE TITLE
Proxy settings are ignored by IPNMessage>>validate

### ISSUE THREAD

**Issue by zeroflag** [paypal/PayPal-Java-SDK#127]
It seems that the IPNMessage completely ignores the given proxy settings.

Map<String, String> config = new HashMap<>();
config.put("http.UseProxy", "true");
config.put("http.ProxyHost", host);
config.put("http.ProxyPort", port),;
...
IPNMessage ipn = new IPNMessage(raw, config);
ipn.validate(); // always uses no proxy

In the IPNMessage>>initialize(), an HttpConfiguration is instantiated. The endpoint url, connection timeout and some other parameters are set, but the proxy settings are not set. Later this httpConfiguration is used in the validate method. 

I see no way to set the proxy settings.

**Comment by juwlee** [comment]
@zeroflag thanks for pointing this out. Actually, IPN is used by classic SDKs and not by this REST SDK. Instead of IPN, REST SDKs have webhooks. Please see [this doc](https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/) for more info.
