### ISSUE TITLE
Payment Data Transfer supported?

### ISSUE THREAD

**Issue by mwladysiak** [paypal/PayPal-Java-SDK#130]
Hi,
although I plan to use IPNs mostly, I want to be able to show the customers returning from PP to my shop their order number. From what I have understood, I would insert the soon-to-be order number in the Transaction.custom variable, which would later be accessible to me per a Payment Data Transfer query. 

Does your SDK support PDTs yet? I could not find any relevant class / method that would imply so, nor any information in the Readme. 
Thanks in advance for your help!

**Comment by ppmtscory** [comment]
PDT is used for classic PayPal Payments Standard.  For these SDKs and REST APIs in general, you can either use [Webhooks](https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/#event-type-support) or you could simply do a [GET call on the payment resource](https://developer.paypal.com/docs/api/#look-up-a-payment-resource) to get the transaction information you need.
