### ISSUE TITLE
Tokeninfo.createFromRefreshTokenForFpp  is broken

### ISSUE THREAD

**Issue by gauravcsun** [paypal/PayPal-Java-SDK#131]
Hi,

While trying to consume the` createFromRefreshTokenForFpp`   method I  figured out that 

`RESTUtil.formatURIPath` does not work correctly because the `grant_type` query string value is already set up, the `splitParameters` method of `RestUtils` class put the refresh token value at 1st place instead of 0th  in the return array 
and  this build up bad url as below instead of replacing refresh token

`String pattern = "v1/oauth2/token?grant_type=refresh_token&refresh_token={0}";`

`Output :  'v1/oauth2/token?grant_type=refresh_token`

Simple Java Program to test

```
String pattern = "v1/oauth2/token?grant_type=refresh_token&refresh_token={0}";
Map<String, String> paramsMap = new HashMap<String, String>();
try {
	paramsMap.put("refresh_token", URLEncoder.encode("Ohw0tEN8fYHO5GfEN8W0iq0r6rTvkT19YARyNGzUDwm2k5B306ovyTZrC5D20Z8ovPrXPFCRV05-s-xwNQxg8b19wTo",
					Constants.ENCODING_FORMAT));
	} catch (UnsupportedEncodingException ex) {
			// Ignore
	}
		
	Object[] parameters = new Object[] { paramsMap };
	String resourcePath = RESTUtil.formatURIPath(pattern, parameters);
		
	System.out.println(resourcePath);
```

**Comment by juwlee** [comment]
@gauravcsun thanks for pointing this out. We will have a look.

**Comment by juwlee** [comment]
@gauravcsun [the fix](https://github.com/paypal/PayPal-Java-SDK/commit/c026a1642da938e55775ab3ec8a08514416b9eb7) will be shipped in the next release.
