### ISSUE TITLE
Validate returning unverified when transaction exists

### ISSUE THREAD

**Issue by jostster** [paypal/PayPal-Java-SDK#132]
```
IPNMessage ipnlistener = new IPNMessage(request, configurationMap);
boolean isIpnVerified = ipnlistener.validate();
```

isIpnVerified is returning false sometimes when the transaction really exists in paypal.

**Comment by juwlee** [comment]
@jostster which SDK are you having this problem with?

**Comment by jostster** [comment]
@juwlee we are using 
```
compile "com.paypal.sdk:paypal-core:1.6.9"
compile "com.paypal.sdk:merchantsdk:2.14.117"
```

**Comment by jostster** [comment]
@juwlee seems there may be a bigger issue. The transaction shows completed in Paypal but it is not listed in the IPN History... Maybe that is why it isn't coming back as verified?

**Comment by jostster** [comment]
NVM, switched to classic mode and the IPN was there. so not sure why it shows invalid sometimes

**Comment by jostster** [comment]
Seems to be related to special characters https://github.com/paypal/merchant-sdk-java/issues/18

**Comment by jostster** [comment]
Created this for the wrong project. Closing and moving to merchant-sdk
