### ISSUE TITLE
remove log4j.properties

### ISSUE THREAD

**Issue by Geniy00** [paypal/PayPal-Java-SDK#133]
Hi all,

I use this sdk in my project. You can see that there is rest-api-sdk/src/main/resources/log4j.properties to configure logging level.
In my big project I have slf4j and lockback as implementation. My logging is configured by logback.xml.

The problem is that I can't change(override) logging in paypal SDK. It was set to DEBUG level by default in your log4j.properties. I tried to use different bridges log4j -> logback, but it has not result.

In my opinion, it isn't good to have logging config in any SDK.
Could you please remove rest-api-sdk/src/main/resources/log4j.properties  file?

P.S. I've found only one solution. Rebuild your project without log4j.properties and upload it to nexus

**Comment by juwlee** [comment]
@Geniy00 thanks for the suggestion. `log4j.properties` is rather a sample configuration to give an idea as to how to set up log4j than an actual configuration that this SDK uses. The file was moved in commit 62bf39e and will be shipped in the next release.
