### ISSUE TITLE
Question/Issue: Payment.get(...), update_time 

### ISSUE THREAD

**Issue by dili91** [paypal/PayPal-Java-SDK#136]
I noticed today that the look-up REST response (GET /v1/payments/payment/<Payment-Id>) does not include an "update_time" field anymore in the JSON object's root, as described here https://developer.paypal.com/docs/api/#payment-object 

Can someone tell me if this is an expected result? if so, where can I find a changelog ? 

Anyway I think is not related to the Java SDK, so excuse me for posting this here

**Comment by juwlee** [comment]
Hi @dili91 Thanks for reporting. Yes, payment API has been updated and this SDK needs changes accordingly. It probably will not go into the next version which is about to be released, but it will be in the following version. We will keep this issue open until the changes are pushed.

**Comment by dili91** [comment]
Ok! thank you for the quick reply! @juwlee

**Comment by juwlee** [comment]
@dili91 it has been added [here](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/api/payments/Payment.java#L107). I am closing this issue now. Thanks again for reporting.
