### ISSUE TITLE
Response Code : 400 change log level to DEBUG for details.

### ISSUE THREAD

**Issue by dbethel** [paypal/PayPal-Java-SDK#137]
I was getting a 400 error code back when submitting a price with a decimal point.  The client logs `Response Code : 400 change log level to DEBUG for details.`, but does not actually log the exception returned from the rest API no matter what level I set the debugging to.

**Comment by ashim-jung-khadka** [comment]
@dbethel  Did you solve this problem?

**Comment by ashim-jung-khadka** [comment]
@dbethel did you find any solution for this?

**Comment by dbethel** [comment]
This appears to have been fixed in the source code, but you have to build it yourself.  At least it had not been pushed to Maven when I last looked at it.  I ended up with the following for a payment amount string: 

double amount = 10.00;
new DecimalFormat("0.00").format(amount);

**Comment by ashim-jung-khadka** [comment]
Thank You @dbethel Now it is provided in maven. I also ended up using the method.

**Comment by juwlee** [comment]
@dbethel as @ashim-jung-khadka said, it should be included in the latest version on maven central. Please try it out.
