### ISSUE TITLE
Payment with store credit card is not working

### ISSUE THREAD

**Issue by ashim-jung-khadka** [paypal/PayPal-Java-SDK#140]
I am trying to do a payment, but it is not working. It gives me :
```
Response code: 400	Error response: {"name":"UNKNOWN_ERROR","message":"An unknown error has occurred",
"information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR",
"debug_id":"1128bfe63fea1"}
```

I can do a payment upto $60,000 using sandbox account but if I go above than it gives me an exception.
Maybe its because of account limit but I am not sure.

**Comment by juwlee** [comment]
Hi @ashim-jung-khadka [PayPal MTS](https://ppmts.custhelp.com/app/answers/list) would be able to help you with the error.
