### ISSUE TITLE
 payment.execute

### ISSUE THREAD

**Issue by ara0** [paypal/PayPal-Java-SDK#141]
I have two problems with payment.executed
1. payment.execute(apiContext, paymentExecute);
Response code: 500	Error response: {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"3447948040c89
2.payment.execute(accessToken, paymentExecute)
> ru.myx.ae3.exec.ExecErrorDefault
    > null
    > com.paypal.base.rest.PayPalRESTException
        > null
        > java.net.MalformedURLException
            > null
            > java.lang.NullPointerException
              : java.net.URL.<init>(URL.java:524)
              : java.net.URL.<init>(URL.java:482)
              : java.net.URL.<init>(URL.java:431)
              : com.paypal.base.DefaultHttpConnection.createAndconfigureHttpConnection(DefaultHttpConnection.java:55)
              : com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:406)
              : com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:267)
              : com.paypal.api.payments.Payment.execute(Payment.java:402)
              : com.paypal.api.payments.Payment.execute(Payment.java:368)

**Comment by juwlee** [comment]
Hi @ara0 for the first issue, please reach out to PayPal MTS.
For the second, it seems the endpoint URL is null. Did you override and set a new URL? Or are you using a default from config file?

**Comment by ara0** [comment]
2. use only defaults.

**Comment by juwlee** [comment]
Can you double check the value in config file and see if it is the same as the one in this repo?

**Comment by ara0** [comment]
I checked.We downloaded and compiled.I have not changed anything in the configuration files.

**Comment by juwlee** [comment]
Have you tried to dump the value before NPE? Also, what version of SDK are you using?

**Comment by ara0** [comment]
which variables you need? version 1.3.1

**Comment by ppmtscory** [comment]
apiContext is what should be used so the issue causing the Internal Error should've corrected this issue.  As I don't see an update here, hopefully you were able to reach out and get assistance from PayPal MTS team.  If not, and you still are receiving Internal Error with `apiContext` then feel free to let us know.
