### ISSUE TITLE
Does SDK support express checkout?

### ISSUE THREAD

**Issue by msalman86** [paypal/PayPal-Java-SDK#146]
Hey everyone, 

My company is looking to upgrade to newer rest sdk from old soap sdk (merchant, adaptivepayment etc). Does new sdk support express checkout and if so is there an example? If it doesn't support it, does it mean we have to keep using the old merchantsdk?

Thank you

**Comment by juwlee** [comment]
Hi @msalman86 by the old soap sdk, do you mean [this one](https://github.com/paypal/merchant-sdk-java)? Samples are available [here](https://github.com/paypal/PayPal-Java-SDK/tree/master/rest-api-sample)

**Comment by msalman86** [comment]
Hey @juwlee, thanks for your feedback. Yes, I meant the exact sdk you linked above. I didn't find any sample code on express checkout in the newer sdk. I may have missed it. Could you please point me to the exact file, it would be much appreciated? thank you.

**Comment by jaypatel512** [comment]
Probably this might help: https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sample/src/main/java/com/paypal/api/payments/servlet/PaymentWithPayPalServlet.java

Also, you might be interested in checkout out the sample project itself. you can execute this locally, and it will create an easy to understand sample webpage, which will take you through each of these scenarios. Here is the documentation to start the project: https://github.com/paypal/PayPal-Java-SDK/tree/master/rest-api-sample
