### ISSUE TITLE
Language Problem

### ISSUE THREAD

**Issue by sahinyanlik** [paypal/PayPal-Java-SDK#147]
Hello I have been using Paypal-java-sdk for a while. When my user try to pay money, he just see page in Turkish(my store in Turkey but i want everyone to see page in English), I have searched for it and found out i can set it with this 
 lc =
* US
* GB
* NL
* DE
* IT
* FR

How can i set this values ? I searched codebase but there is no example about it.

Thanks

**Comment by juwlee** [comment]
Hi @sahinyanlik please see [this answer on stackoverflow](http://stackoverflow.com/questions/23524011/paypal-rest-api-how-to-control-the-display-language).
