### ISSUE TITLE
PayPalRESTException getDetails().getCode() returns null

### ISSUE THREAD

**Issue by dili91** [paypal/PayPal-Java-SDK#148]
[v 1.4.1]
Hi, 
In order to gracefully handle a refund request on a transaction that has already been refunded, I should have the possibility to check  the exact error code returned by PayPal REST API in case of a captureObject.refund(apiContext, refund) method call.
As mentioned [here](https://developer.paypal.com/docs/classic/api/errorcodes/), I should look for error 10009, but getDetails().getCode() on an PayPalRESTException returns null in this case.

Thanks, 
Andrea

**Comment by juwlee** [comment]
Hi @dili91 this SDK is a REST SDK which is different from our classic products. Please see [REST error docs](https://developer.paypal.com/webapps/developer/docs/api/#errors) for REST errors.

**Comment by dili91** [comment]
Ok, thanks. Anyway this an example response.
As you can see, due to the generic "TRANSACTION_REFUSED" details.name, I can't assume that the error returned is the one I'm looking for. (I should check the details.message string....)
is it an expected result?

response-code: 400	
details:
     name: TRANSACTION_REFUSED
     message: The request was refused.This transaction has already been fully refunded	
     details: null
     debug-id: ac3f35482f120
    information-link:https://developer.paypal.com/webapps/developer/docs/api/#TRANSACTION_REFUSED

**Comment by juwlee** [comment]
@dili91 it does look like a valid error response. You would need to see `details`, `name`, and `message` in order to figure out the details of the error.

In this case, the error indicates that the transaction has been already refunded. If that is not the case or if there is any issue, please reach out to [PayPal MTS](https://manager.paypal.com/jsp/common/contactUs.jsp)

**Comment by dili91** [comment]
Ok @juwlee, thanks again.
I did the same request directly to the REST API(https://api.sandbox.paypal.com/v1/payments/capture/{captureid}/refund) and as you can see from the JSON response body below, it seems that actually the REST API does not provide a strong identifier for this error(I also checked the response HTTP headers).  I don't think that inspecting the "message" string is the right solution so I will try to address the request directly to the REST api dev team. judging byt the message string, it seems that the API can discriminate that specific type of error so I bet they could also give us back a more meaningful response(i mean, not only human readable)

Thanks,
Andrea

{
  "name": "TRANSACTION_REFUSED",
  "message": "The request was refused.This transaction has already been fully refunded",
  "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#TRANSACTION_REFUSED",
  "debug_id": "e3f52374ef2e7"
}

**Comment by juwlee** [comment]
@dili91 thanks for the suggestion. In REST, errors have hierarchical structure. They are mapped to HTTP codes to provide an idea at high-level as to what went wrong. In error responses, there are also fields that provide details.

With that said, the best way to make a suggestion or to contact an API team is through PayPal MTS.
