### ISSUE TITLE
Im puzzled

### ISSUE THREAD

**Issue by xBeezleBugx** [paypal/PayPal-Java-SDK#149]
I am coding a payment service in scala using this sdk. 
What happens is:
val transaction = new Transaction
logs to: "transactions": []
then when i call:
transaction.setAmount(amount)
it logs to:  "transactions": [],
      "amount": {
        "currency": "USD",
        "total": "12"
      }

And of course paypal responds:
ERROR - PayPalRESTException Response code: 400  Error response: {"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].item_list.items[0].tax","issue":             "Currency amount must be non-negative number, may optionally contain exactly 2 decimal places separated by '.', optional thousands separator ',', limited to 7 d             igits before the decimal point and currency which is a valid ISO Currency Code"},{"field":"transactions","issue":"Item currency codes should be same as the tran             saction currency code in all buckets"},{"field":"transactions[0].item_list.items[0].currency","issue":"Required field missing"},{"field":"transactions[0].item_l             ist.items[0].price","issue":"Currency amount must be non-negative number, may optionally contain exactly 2 decimal places separated by '.', optional thousands s             eparator ',', limited to 7 digits before the decimal point and currency which is a valid ISO Currency Code"}],"message":"Invalid request - see details","informa             tion_link":"https://developer.paypal.com/webapps/developer/docs/api/#VALIDATION_ERROR","debug_id":"912e594c547b7"}

I am pretty sure this happens because of new Transaction creating transactions : [] .
The question is is it a problem of using scala ? What puzzles me is why is the transaction constructer constructing a transactions ArrayList (is it just bad naming or do i just dont get it)

Another thing that puzzles me why has the Transaction constuctor a method : setTransactions allowing to add a list of Transaction to the transactions object

Pls help because i can figure out how to construct a simple Transaction

**Comment by pp-randy** [comment]
The JSON being generated should end up looking like
transactions":[{"item_list":{"items":[{"price":"1.00","name":"Test Item","quantity":"1","currency":"USD"}]

Does Scala have a way for you to add your transaction to the transactions array? 

From the Java example you can see it being done here: https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sample/src/main/java/com/paypal/api/payments/servlet/PaymentWithPayPalServlet.java#L164

**Comment by xBeezleBugx** [comment]
I use (scala): 
val transaction = new Transactions 
witch corresponds to (java):
Transaction transaction = new Transaction(); 
i imported the java lib.
This call triggers the constructor:
	public Transaction() {
		transactions = new ArrayList<Transaction>();
	}
If I log transaction after after calling constuctor I get:
"transactions" : []
if i then say transaction.setAmount(amount) and log transaction I get:
"transactions" : [],
"amount" : {....}

for more detail see : 
http://stackoverflow.com/questions/34787949/scala-java-paypal-sdk-cant-construct-valid-transaction

**Comment by juwlee** [comment]
@xBeezleBugx Payment class has [setTransactions() setter](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/api/payments/Payment.java#L246)

**Comment by xBeezleBugx** [comment]
ok I will try to explain again:
yes there is the setTransactions() setter that expects List<Transaction>
BUT:
the Transaction constructor:
	public Transaction() {
		transactions = new ArrayList<Transaction>();
	}
returns a list of itself
for instance following code is perfectly valid:
val transaction = new Transaction
transaction.setTransactions((new Transaction).getTransactions)
BUT there is no way to construct Transaction.
From my point of view Transaction.java would have to be:
package com.paypal.api.payments;

import java.util.ArrayList;
import java.util.List;

public class Transaction extends TransactionBase {
	/**
	 * Default Constructor
	public Transaction() {
	}
}

instead of :
package com.paypal.api.payments;

import java.util.ArrayList;
import java.util.List;

public class Transaction extends TransactionBase {

	/**
	 * Additional transactions for complex payment scenarios.
	 */
	private List<Transaction> transactions;

	/**
	 * Default Constructor
	 */
	public Transaction() {
		transactions = new ArrayList<Transaction>();
	}


	/**
	 * Setter for transactions
	 */
	public Transaction setTransactions(List<Transaction> transactions) {
		this.transactions = transactions;
		return this;
	}

	/**
	 * Getter for transactions
	 */
	public List<Transaction> getTransactions() {
		return this.transactions;
	}


}
