### ISSUE TITLE
Nullpointer Exception in HttpConnection when invalid oauth token sent in REST request

### ISSUE THREAD

**Issue by lcoppeaux** [paypal/PayPal-Java-SDK#150]
In com.paypal.base.HttpConnection (1.4.1), when an invalid oauth token is used, the paypal REST server answers a 4XX http response code.

But the client paypal java sdk hides the root cause of the error and throws a NullPointerException because the error stream of the http connection is null. 
The following code (HttpConnection) must be modified to test if the error stream is null before trying to read it : 

					} else if (responsecode >= 300 && responsecode < 500) {
						reader = new BufferedReader(new InputStreamReader(
								connection.getErrorStream(),
								Constants.ENCODING_FORMAT));
						errorResponse = read(reader);
						String msg = "Response code: " + responsecode + "\tError response: " + errorResponse;
						throw new ClientActionRequiredException(responsecode, errorResponse, msg, new IOException(msg));
					} else if (responsecode >= 500) {
						reader = new BufferedReader(new InputStreamReader(
								connection.getErrorStream(),
								Constants.ENCODING_FORMAT));
						errorResponse = read(reader);
						String msg = "Response code: " + responsecode + "\tError response: " + errorResponse;
						throw new HttpErrorException(responsecode, errorResponse, msg, new IOException(msg));
					}

**Comment by jaypatel512** [comment]
This commit should fix the issue:
https://github.com/paypal/PayPal-Java-SDK/commit/c091c10dc46fc48a14c687654818a35b714a4125.

Can you please see if you can verify it too ! We will make a release soon.

**Comment by jaypatel512** [comment]
Release [v1.4.2](https://github.com/paypal/PayPal-Java-SDK/releases/tag/v1.4.2) should fix the issue for you now.
