### ISSUE TITLE
RestAPI code sample /Or Test class for 'Checkout with Paypal' button

### ISSUE THREAD

**Issue by rrepaka** [paypal/PayPal-Java-SDK#151]
Is there any RestAPI code sample /Or Test class for 'Checkout with Paypal' button ?

a. Go to URL : https://demo.paypal.com/us/navigation?merchant=beauty&page=paymentStandardLogin
b. Click on 'Skip the demo , Get code'
c. I have down loaded the SDK from : https://github.com/paypal/PayPal-Java-SDK
d. But i do not see any RestAPI code sample /Or Test class for 'Checkout with Paypal' button

Could you please point out your code sample for 'Checkout with Paypal' button REST API samples.

![checkoutwithpaypal](https://cloud.githubusercontent.com/assets/15839195/12833559/5bac8c94-cb56-11e5-90ed-185b4668fb6e.png)

**Comment by jaypatel512** [comment]
You can run samples that comes packaged with Java-SDK. Please follow the instructions [shown here](https://github.com/paypal/PayPal-Java-SDK/tree/master/rest-api-sample), and you should be able to setup a simple web server, which will provide you with a lot of samples, including "Express Checkout" or "Payment with PayPal as payment source" which is the same as "Checkout with PayPal".
