### ISSUE TITLE
Payment with stored credit card in LIVE mode returning UNKNOWN_ERROR (not helpful message)

### ISSUE THREAD

**Issue by sw3lai** [paypal/PayPal-Java-SDK#152]
I'm in attempt of an end-to-end test with payment using a stored credit card in the LIVE environment. What I receive is a response with UNKNOWN_ERROR, this message is not helpful as it does not give any hint to where the issue could be. Please advise.

=======================
Response code: 400
Error response: {"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"aa8ba19e22ff1"}

**Comment by bluk** [comment]
@sw3lai I would verify that the vaulted credit card details are correct (number, expiration date, CVV2). It seems there is difficulty validating the credit card. Please contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com) for more details. I'll open an internal ticket to give more details in the error rather than just "Unknown Error".

**Comment by sw3lai** [comment]
@bluk thanks for the response. You've indicated there is difficulty validating the credit card. However, my team has tried 3 valid credit card carefully and resulting in UNKNOWN_ERROR. What is more concerning, is that the our request work in sandbox. If our integration worked in sandbox, then naturally we'd expect the same to pass in live.

Can you please help give more details on what field (or lack of field) is causing the UNKNOWN_ERROR, as we have very little to go on to resolve this ourselves, just a bit more help is much appreciated. Thanks in advance.

**Comment by bluk** [comment]
@sw3lai The CVV2 field is failing validation but it may be a combination of the other credit card details or missing information. PayPal Merchant Technical Support would have access to more details.
