### ISSUE TITLE
Paypal-Java-SDK jar 

### ISSUE THREAD

**Issue by rrepaka** [paypal/PayPal-Java-SDK#153]
we don't use maven in our project. 
can i download Paypal-Java-SDK jar file from paypal developer site which includes all the source code and dependent jar files ?

**Comment by bluk** [comment]
You can use http://search.maven.org to find JARs uploaded to Maven. For instance, http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22rest-api-sdk%22 allows you to download the JAR for the paypal rest-api-sdk.
