### ISSUE TITLE
Webhooks can't be validated

### ISSUE THREAD

**Issue by IgnacioHR** [paypal/PayPal-Java-SDK#157]
Hi,

I'm having an issue validating the webhook using the provided examples and my own app. The issue is documented here http://stackoverflow.com/questions/35759815/validate-webhook-using-java-event-validatereceivedevent-always-fails-signature-v 

I'm trying to focus the problem. 

looking at the documentation here https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/#event-signature and debugging my application just after digital signature validation I can confirm the seed for the signature is this:
464163d0-e0ae-11e5-af72-51ae350aaff1|2016-03-02T19:38:01Z|3W2725225F637605K|3555709430

on this page
https://developer.paypal.com/developer/webhooksSimulator/ 
I can see some information about the webhook sent to my application but the CRC32 is missing!

I wonder if the crc32 I calculate differs from the crc32 calculated at paypal simulator due to spaces to pretty-print the json on the PayPal web site, codepages or whatever other reason...

**Comment by IgnacioHR** [comment]
So, question is, are you sure webhook messages are properly signed? I've replaced some lines of code in my app with same values from lines 37 to 43 from this page https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/test/java/com/paypal/base/ValidateCertTest.java and validation success. so now I think paypal sandbox is not property signing or computing the crc32

**Comment by IgnacioHR** [comment]
Self contained testing application
`/*
 * © 2016 by Ignacio Hernandez-Ros.
 *
 * This file is property of Reporting Standard S.L. http://www.reportingstandard.com and shall not be used outside the company unless you
 * have written permissions for different purposes.
 *
 * If you have received this file from Reporting Standard, you may have the following permissions:
 *
 * This work may be reproduced and redistributed, in whole or in part, 
 * without alteration and without prior written permission, 
 * solely by educational institutions for nonprofit administrative 
 * or educational purposes provided all copies contain the 
 * following statement: 
 * "© 2016 Ignacio Hernandez-Ros. This work is reproduced and distributed with the permission of Ignacio Hernandez-Ros. No other use is permitted without the express prior written permission of Ignacio Hernandez-Ros. For permission, contact ignacio at reportingstandard dot com"
 *
 * File creation date 3 de mar. de 2016
 */
/**
 * 
 */
package com.rsws.renew;

import java.io.InputStream;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.SignatureException;
import java.util.HashMap;
import java.util.Map;

import com.paypal.api.payments.Event;
import com.paypal.base.Constants;
import com.paypal.base.rest.APIContext;
import com.paypal.base.rest.PayPalRESTException;
import com.paypal.base.rest.PayPalResource;

/**
 * @author Ignacio
 *
 */
public class TestWebHook {
	
	 public static void main(String[] argv) {
		 
		try {
			InputStream is = InvoicePaid.class 
					.getResourceAsStream("/sdk_config.properties"); 
			try { 
				PayPalResource.initConfig(is); 
			} catch (PayPalRESTException e) { 
				e.printStackTrace();
			} 
			
			APIContext apiContext = new APIContext();
			Map<String, String> map = new HashMap<>(PayPalResource.getConfigurations());
			apiContext.setConfigurationMap(map);
			   
			Map<String,String> headers = new HashMap<String,String>();
			
			// this is the data provided by PayPal sandbox
			map.put(Constants.PAYPAL_WEBHOOK_ID, "3W2725225F637605K");
			String payload = "{\"id\":\"WH-0T490472X6099635W-7LJ29748BW389372K\",\"create_time\":\"2015-09-25T23:14:14Z\",\"resource_type\":\"invoices\",\"event_type\":\"INVOICING.INVOICE.PAID\",\"summary\":\"An invoice was created\",\"resource\":{\"id\":\"INV2-8FSD-3HT6-BRHR-UHYV\",\"number\":\"MM00063\",\"status\":\"PAID\",\"merchant_info\":{\"email\":\"example@outlook.com\",\"first_name\":\"Dennis\",\"last_name\":\"Doctor\",\"business_name\":\"Medical Professional LLC\",\"address\":{\"line1\":\"1234 Main St\",\"line2\":\"Apt 302\",\"city\":\"Portland\",\"state\":\"OR\",\"postal_code\":\"97217\",\"country_code\":\"US\"}},\"billing_info\":[{\"email\":\"example@example.com\",\"business_name\":\"Medical Professionals LLC\",\"language\":\"en_US\"}],\"items\":[{\"name\":\"Sample Item\",\"quantity\":1,\"unit_price\":{\"currency\":\"USD\",\"value\":\"1.00\"},\"unit_of_measure\":\"QUANTITY\"}],\"invoice_date\":\"2015-09-28 PDT\",\"payment_term\":{\"term_type\":\"DUE_ON_RECEIPT\",\"due_date\":\"2015-09-28 PDT\"},\"tax_calculated_after_discount\":true,\"tax_inclusive\":false,\"total_amount\":{\"currency\":\"USD\",\"value\":\"1.00\"},\"payments\":[{\"type\":\"PAYPAL\",\"transaction_id\":\"22592127VV907111U\",\"transaction_type\":\"SALE\",\"method\":\"PAYPAL\",\"date\":\"2015-09-28 14:37:13 PDT\"}],\"metadata\":{\"created_date\":\"2015-09-28 14:35:46 PDT\",\"last_updated_date\":\"2015-09-28 14:37:13 PDT\",\"first_sent_date\":\"2015-09-28 14:35:47 PDT\",\"last_sent_date\":\"2015-09-28 14:35:47 PDT\"},\"paid_amount\":{\"paypal\":{\"currency\":\"USD\",\"value\":\"1.00\"}},\"links\":[{\"rel\":\"self\",\"href\":\"https://api.paypal.com/v1/invoicing/invoices/INV2-8FSD-3HT6-BRHR-UHYV\",\"method\":\"GET\"}]},\"links\":[{\"href\":\"https://api.paypal.com/v1/notifications/webhooks-events/WH-0T490472X6099635W-7LJ29748BW389372K\",\"rel\":\"self\",\"method\":\"GET\"},{\"href\":\"https://api.paypal.com/v1/notifications/webhooks-events/WH-0T490472X6099635W-7LJ29748BW389372K/resend\",\"rel\":\"resend\",\"method\":\"POST\"}]}";
			headers.put("PAYPAL-CERT-URL", "https://api.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-df8cd2d5");
			headers.put("PAYPAL-TRANSMISSION-ID", "464163d0-e0ae-11e5-af72-51ae350aaff1");
			headers.put("PAYPAL-TRANSMISSION-TIME", "2016-03-02T19:38:01Z");
			headers.put("PAYPAL-AUTH-ALGO", "SHA256withRSA");
			headers.put("PAYPAL-TRANSMISSION-SIG", "S3AjY87GLp1MP/UsGAWPoEes+laa7xbV4X7pMi9PdC0QR7MoNC/L/O2UThAh1IBzDZ5DGXvkEDvXK9fF0IfoS2QtLJUBm5+UFoo1jJMlH+QCiJUEHSuio2UrFGbxoqaIPcA1PN0tmd5FwikDRPCnpht6pvMvCZV1FEQbBMr9ld3d3XoWBKeWQG+oxAWSTNYJiKQIrM6l/8+hKVQ1LZID8dtR3c7y6eFxNFsDQ3WgwChZZ15vpyhDWQ4t08m3PsWFyjvsQmNRyXQyUeAC8xw96sBwGmHsgwKJwbAamVrWicQqQ/tXuUcqx9Y0pg3P4LuGNPFKzktq9L3ZImTEJxpRLA==");
			// this shows invalid
			System.out.println(Event.validateReceivedEvent(apiContext, headers, payload) ? "valid" : "invalid");
		
			// this is the data provided in the sdk examples https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/test/java/com/paypal/base/ValidateCertTest.java
			map.put(Constants.PAYPAL_WEBHOOK_ID, "3RN13029J36659323");
			payload = "{\"id\":\"WH-2W7266712B616591M-36507203HX6402335\",\"create_time\":\"2015-05-12T18:14:14Z\",\"resource_type\":\"sale\",\"event_type\":\"PAYMENT.SALE.COMPLETED\",\"summary\":\"Payment completed for $ 20.0 USD\",\"resource\":{\"id\":\"7DW85331GX749735N\",\"create_time\":\"2015-05-12T18:13:18Z\",\"update_time\":\"2015-05-12T18:13:36Z\",\"amount\":{\"total\":\"20.00\",\"currency\":\"USD\"},\"payment_mode\":\"INSTANT_TRANSFER\",\"state\":\"completed\",\"protection_eligibility\":\"ELIGIBLE\",\"protection_eligibility_type\":\"ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE\",\"parent_payment\":\"PAY-1A142943SV880364LKVJEFPQ\",\"transaction_fee\":{\"value\":\"0.88\",\"currency\":\"USD\"},\"links\":[{\"href\":\"https://api.sandbox.paypal.com/v1/payments/sale/7DW85331GX749735N\",\"rel\":\"self\",\"method\":\"GET\"},{\"href\":\"https://api.sandbox.paypal.com/v1/payments/sale/7DW85331GX749735N/refund\",\"rel\":\"refund\",\"method\":\"POST\"},{\"href\":\"https://api.sandbox.paypal.com/v1/payments/payment/PAY-1A142943SV880364LKVJEFPQ\",\"rel\":\"parent_payment\",\"method\":\"GET\"}]},\"links\":[{\"href\":\"https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-2W7266712B616591M-36507203HX6402335\",\"rel\":\"self\",\"method\":\"GET\"},{\"href\":\"https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-2W7266712B616591M-36507203HX6402335/resend\",\"rel\":\"resend\",\"method\":\"POST\"}]}";			
			headers.put("PAYPAL-CERT-URL", "https://api.sandbox.paypal.com/v1/notifications/certs/CERT-360caa42-fca2a594-a5cafa77");
			headers.put("PAYPAL-TRANSMISSION-ID", "b2384410-f8d2-11e4-8bf3-77339302725b");
			headers.put("PAYPAL-TRANSMISSION-TIME", "2015-05-12T18:14:14Z");
			headers.put("PAYPAL-AUTH-ALGO", "SHA256withRSA");
			headers.put("PAYPAL-TRANSMISSION-SIG", "vSOIQFIZQHv8G2vpbOpD/4fSC4/MYhdHyv+AmgJyeJQq6q5avWyHIe/zL6qO5hle192HSqKbYveLoFXGJun2od2zXN3Q45VBXwdX3woXYGaNq532flAtiYin+tQ/0pNwRDsVIufCxa3a8HskaXy+YEfXNnwCSL287esD3HgOHmuAs0mYKQdbR4e8Evk8XOOQaZzGeV7GNXXz19gzzvyHbsbHmDz5VoRl9so5OoHqvnc5RtgjZfG8KA9lXh2MTPSbtdTLQb9ikKYnOGM+FasFMxk5stJisgmxaefpO9Q1qm3rCjaJ29aAOyDNr3Q7WkeN3w4bSXtFMwyRBOF28pJg9g==");			
			// this shows valid
			System.out.println(Event.validateReceivedEvent(apiContext, headers, payload) ? "valid" : "invalid");
			
		} catch (InvalidKeyException e) {
			e.printStackTrace();
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		} catch (SignatureException e) {
			e.printStackTrace();
		} catch (PayPalRESTException e) {
			e.printStackTrace();
		}
	}
}
`
Validating data from the examples success but validating data from PayPal sandbox fails. Copy and paste the data you receive and drop a note. thanks

**Comment by IgnacioHR** [comment]
Knock Knock, anybody out there?

**Comment by jaypatel512** [comment]
So, when you saw `// this is the data provided by PayPal sandbox`, do you mean this data is retrieved from webhook simulator, or when you actually paid an invoice in paypal sandbox to create that event, and it returned that ?

**Comment by jaypatel512** [comment]
I just tested the `sale.completed` scenario, where I created a sale payment, executed it, and obtained a new webhook event. I tested that with the above code, and it passed successfully.

**Comment by IgnacioHR** [comment]
Hi,

> So, when you saw // this is the data provided by PayPal sandbox, do you mean this data is retrieved from webhook simulator,

This process I'm doing step by step for testing:
1) Head the browser (safari) to developer.paypal.com and log to my company account.
2) click on Dashboard
3) click on REST API Apps and on the only one application created
4) under sandbox webhooks, I copy the URL I defined for my webhook to the clipboard
5) On the left, in the sandox menu, click on the Webhooks Simulator
6) on the webhooks URL I paste the URL
7) on the Event Type I select the only one event that my app can process which is Invoicing Invoicie paid
8) I click on "Send Test" button
9) this is doing two things: 
  1 - it shows Event Data Sent
  2 - it actually fires the wehook
10) on my application, it fails validation, I can see the parameters received in a log file so I copy and paste the received parameters in the application you have on top on this thread and it fails too.

In any case, I'm going to test as you suggest, by actually paying the invoice using the {account}-buyer account and see if the webhook is generated and validated.

**Comment by IgnacioHR** [comment]
FYI:

> In any case, I'm going to test as you suggest, by actually paying the invoice using the {account}-buyer account and see if the webhook is generated and validated.

This does not fire the webhook

**Comment by ppmtscory** [comment]
@IgnacioHR I am going to close this issue out as it's not anything specific to the SDK itself.  If you are still having issues with Webhook validation, please reach out to our Merchant Technical Support team by filing a ticket [here](https://www.paypal-techsupport.com/app/ask).
