### ISSUE TITLE
Sale request doesn't work with stored card due to CreditCardToken implementing expireMonth  and expireYear as primitives

### ISSUE THREAD

**Issue by yegor-yenikyeyev-pilgrim** [paypal/PayPal-Java-SDK#160]
The  class CreditCardToken implements  private int expireMonth and  private int expireYear as int primitives. This allows and automatically sets zero values for the fields.
Later the JSON serializer produces the following:"credit_card_token": {
          "credit_card_id": "CARD-65G747419F4910610K3QXXJA",
          "expire_month": 0,
          "expire_year": 0
        }
As you can see zero-value fields are included here even though it doesn't make any sense and breaks sale request with a stored card!

The backend rejects this request (its 100% generated via Java SDK:
Request: {
  "intent": "sale",
  "payer": {
    "payment_method": "credit_card",
    "funding_instruments": [
      {
        "credit_card_token": {
          "credit_card_id": "CARD-65G747419F4910610K3QXXJA",
          "expire_month": 0,
          "expire_year": 0
        }
      }
    ]
  },
  "transactions": [
    {
      "transactions": [],
      "amount": {
        "currency": "USD",
        "total": "104.17"
      }
    }
  ]
}

I'm getting error:
Response code: 400 Error response: {"name":"UNKNOWN_ERROR","message":"An unknown error has occurre
d","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"5d8ebc9788246"}

Is it something that only our team mentioned? How it works for the other companies using Java SDK?

It must be very easy to fix by refactoring these fields from int to Short or Integer. Alternatively you guys need to teach the serializer to ignore zero values. I can't imagine a situation when exp month/year can be zero. ;-)

Is it quick fix? Should we do it and create pull request? Sorry to lazy to read your policies and really need a fix ASAP!!!

**Comment by pp-randy** [comment]
I'm trying to reproduce this, the 0 values seem to be ignored in favor of the values stored.  I then tried to add the extra transaction array here.  However, this is also working. 

"transactions": [
{
**"transactions": [],**
"amount": {
"currency": "USD",
"total": "104.17"
}


I do not have access to see the card number you are using in the sandbox.  Are you vaulting a common test card like 4111111111111111?  If so can you try a generated card from here https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1413&expand=true&locale=en_US

**Comment by pp-randy** [comment]
I was able to reproduce your error by turning on negative testing for my sandbox account and passing in your amount.  Does your call work with a 1.00 amount? 

This shouldn't trigger the negative testing feature if its turned on.  You can turn this off by logging into your developer account and going here: https://developer.paypal.com/developer/accounts/ and in the Profile popup -> Settings tab.

**Comment by yegor-yenikyeyev-pilgrim** [comment]
Well yes more detailed research cofirmed that zero values are NOT the reason of UNKNOWN_ERROR. 
This is what PayPal tech support wrote and i just retransmitted here, sorry :-) I'm referencing this ticket https://www.paypal-techsupport.com/app/account/questions/detail/i_id/1227460 

The actual reason of the error is combination of negative testing enabled in sanbox and amount set to 104.17 
However the values are still included into JSON (even thought it doesn't affect anything). From code perspective we do this to instantiate object:
CreditCardToken creditCardToken = new CreditCardToken();
creditCardToken.setCreditCardId( userBillingInfo.getCreditCardId() );
And it _still_ produces the JSON i've posted with zero values (at least with version 1.4.1)

P.S. Do you have any negative test source code examples? Maybe enum/constants for error codes? The documentation for error codes is a huge mess and tech support is actually not "tech" enough. We still didn't figure out why for instance 10417 give s UKNOWN_ERROR and what's the code for INSUFFICIENT_FUNDS.

**Comment by yegor-yenikyeyev-pilgrim** [comment]
Yes it worked well for $1.00

**Comment by pp-randy** [comment]
I do not have an example but will check around. I will look into and see if we have an amount that will decline a credit card payment. 

According to the document here https://developer.paypal.com/docs/rest/api/payments/?mark=INSUFFICIENT_FUNDS  
Insufficient_funds would be for PayPal payments.

**Comment by yegor-yenikyeyev-pilgrim** [comment]
Yeah but unfortunately i didn't find a way to get this error id returned for stored credit card payment when we charge a buyer. Thanks anyway!
