### ISSUE TITLE
Item amount must add up to specified amount subtotal (or total if amount details not specified)

### ISSUE THREAD

**Issue by mslinn** [paypal/PayPal-Java-SDK#165]
I am using v1.4.2 of the SDK. This is Scala code:

````
import java.util.{ArrayList => JArrayList, _}

val details = new Details
details.setSubtotal(cart.total.toString())
details.setShipping("0")
details.setTax("0")

val amount = new Amount
amount.setCurrency("USD")
amount.setTotal(cart.total.toString()) // no tax, no shipping
// amount.setDetails(details) // makes no difference if this is commented or not

val items = new JArrayList[Item]
cart.items.foreach { cartItem =>
  val item = new Item()
    .setName(cartItem.sku)
    .setQuantity(cartItem.quantity.toString)
    .setCurrency("USD")
    .setPrice(cartItem.price.toString())
  items.add(item)
}
val itemList = new ItemList
itemList.setItems(items)

val transaction = new Transaction
transaction.setAmount(amount)
transaction.setDescription("Scala training courses.")
transaction.setItemList(itemList)

val transactions = new JArrayList[Transaction]
transactions.add(transaction)

val payer: Payer = new Payer
payer.setPaymentMethod("paypal")

val payment: Payment = new Payment
payment.setIntent("sale")
payment.setPayer(payer)
payment.setTransactions(transactions)

val redirectUrls: RedirectUrls = new RedirectUrls

val guid: String = UUID.randomUUID.toString.replaceAll("-", "")
val urlPrefix = "http://" + request.host // todo deal with https
redirectUrls.setCancelUrl(urlPrefix + PayPalRoutes.cancel(guid).url)
redirectUrls.setReturnUrl(urlPrefix + PayPalRoutes.approve(guid).url)
payment.setRedirectUrls(redirectUrls)
````

The Payment JSON seems odd: the transactions array contains an inner transactions array which is empty:

````
{
  "intent": "sale",
  "payer": {
    "payment_method": "paypal"
  },
  "transactions": [
    {
      "transactions": [],
      "amount": {
        "currency": "USD",
        "total": "770.00"
      },
      "description": "Scala training courses.",
      "item_list": {
        "items": [
          {
            "name": "course_scalaIntro",
            "quantity": "1",
            "price": "495.00",
            "currency": "USD"
          },
          {
            "name": "course_scalaIntermediate",
            "quantity": "1",
            "price": "495.00",
            "currency": "USD"
          },
          {
            "name": "course_playIntroScala",
            "quantity": "1",
            "price": "275.00",
            "currency": "USD"
          }
        ]
      }
    }
  ],
  "redirect_urls": {
    "return_url": "http://localhost:9443/store/paypalApprove/ba0eba5d55254b0ea88f73a29d151901",
    "cancel_url": "http://localhost:9443/store/paypalCancel/ba0eba5d55254b0ea88f73a29d151901"
  }
}
````

Here is the error:

````
{
  "name" : "VALIDATION_ERROR",
  "details" : [ {
    "field" : "transactions[0]",
    "issue" : "Item amount must add up to specified amount subtotal (or total if amount details not specified)"
  } ],
  "message" : "Invalid request - see details",
  "information_link" : "https://developer.paypal.com/docs/api/#VALIDATION_ERROR",
  "debug_id" : "6a1006b296934"
}
````

**Comment by juwlee** [comment]
@mslinn Thanks for reporting this. We will have a look and report back.

**Comment by mslinn** [comment]
Any findings yet?

**Comment by pp-randy** [comment]
@mslinn the cart total "770.00" should be "1265.00" it's missing one of the 495 it the calculation. 

How is this being calculated? amount.setTotal(cart.total.toString())

**Comment by mslinn** [comment]
Thank you for your second pair of eyes. Problem solved :)

**Comment by hunglt44** [comment]
Thank you. (same bug)

**Comment by AhmedSayedSk** [comment]
Thank you. (same bug) :+1:

**Comment by Ingosmar89219** [comment]
some one can help me? (same bug)
Completed 500 Internal Server Error in 2794ms (ActiveRecord: 3.0ms)

RuntimeError (--- !ruby/hash:PayPal::SDK::REST::ErrorHash
name: VALIDATION_ERROR
details:
- !ruby/hash:PayPal::SDK::REST::ErrorHash
  field: transactions[0]
  issue: Item amount must add up to specified amount subtotal (or total if amoun
t
    details not specified)
message: Invalid request - see details
information_link: https://developer.paypal.com/docs/api/payments/#errors
debug_id: fc64a49f7c1c9
):
  app/controllers/payments_controller.rb:47:in `create'

Well i have a website where i have a model ShoppingCart, InShoppingCart, Payment and Product. when i add InshoppingCarts to ShoppingCart i get a number of products, always is 1 product for each InShoppingCart into ShoppingCart but the user can update the number of products from the view. The issue happens when the user updates the number of products > 1 for example: 2,3,4,5...n but if the number is 1 all works fine :(, the view is this:

view CODE: 
=render "payments/card_data"
.col-lg-10.col-lg-offset-1.col-md-10.col-md-offset-1.col-sm-10.col-sm-offset-1.col-xs-12.bottom.top-space
 .card.large-padding  
  .table-responsive
   %table.table.table-bordered.table-hover.medium#table_shopping_cart
    %thead
     %td.success Producto
     %td.success Costo
     %td.success Cantidad
     %td.success Acciones
    %tbody     
     -@shopping_cart.in_shopping_carts.each do |i_sh|
      -product = i_sh.product
      %tr{id: "#{product.id}"}
       %td= product.name
       %td= product.pricing / 100
       %td
        = form_tag i_sh, method: :put, class:"top-space" do    
         .form-group     
          =number_field_tag :num_products,nil, class:"form-control floating-label", placeholder: "#{i_sh.num_products}", required: true
          =content_tag :button, type: :submit, class:"btn btn-primary bold" do
           Actualizar       
       %td
        %button.red-text.button-active-pink.no-underline{'data-toggle': "modal", 'data-target': "#"+"#{product.id}"}
         Eliminar        
      .modal.fade{id: "#{product.id}", tabindex:"-1", role:"dialog", 'aria-labelledby': "#{product.id}"}
       .modal-dialog{role: "document"}
        .modal-content
         .modal-header
          %button.close{type: "button", 'data-dismiss': "modal", 'aria-label': "Close"}
           %span{'aria-hidden': "true"}
            &times;
          %h4.modal-title.red-text{id: "#{product.id}"} Alerta              
         .modal-body
          %h4.text-center ¿Estas seguro de eliminar el producto del carrito?              
         .modal-footer
          %button.btn.btn-warning.bold{type: "button", 'data-dismiss': "modal"}
           Cerrar
          = link_to "Aceptar",i_sh, method: :delete,class: "btn btn-success bold margin-bottom"                        
  .top-scape.large-padding.text-center#payment_form
   %p.medium
    %strong
     - if @shopping_cart.total != 0
      Total: $
      = @shopping_cart.total / 100
      USD
     - elsif @shopping_cart.total == 0 || @shopping_cart.total == nil     
      %h3 Compra con confianza en naturecode.com
  .top-space
   - if @shopping_cart.total != 0
    =render "payments/buttons"
   - elsif @shopping_cart.total == 0 || @shopping_cart.total == nil
    =link_to "Agregar producto", products_path, class: "btn btn-primary bold"

Product
class Product < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :attachments  
  validates_presence_of :name,:user,:pricing
  validates :pricing, numericality: { greater_than: 0 }

  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100"},default_url: "missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def paypal_form
    {name: name,sku: :item, price: (pricing / 100),currency:"USD",quantity:1}
  end

i believe that the issue happens for this: the quantity is one but when the user updates the inshoppingcart for example 2 products,3,4,5...n i get the error :/

def paypal_form {name: name,sku: :item, price: (pricing / 100),currency:"USD",quantity:1}

ShoppingCart
class ShoppingCart < ActiveRecord::Base
    include AASM
    has_many :products,  through: :in_shopping_carts
    has_many :in_shopping_carts

    aasm column: "status" do
        state :created, initial: true
        state :payed
        state :failed

        event :pay do
            after do
                # TO DO
            end
            transitions from: :created, to: :payed
        end
    end

    def items
        self.products.map{ |product| product.paypal_form }
    end

    def total
        $res=0
        self.in_shopping_carts.map { |i_sh|
            product = i_sh.product 
            $res += product.pricing * i_sh.num_products         
        }
        return $res
    end 
end

InShoppingCart
class InShoppingCart < ActiveRecord::Base
  belongs_to :product
  belongs_to :shopping_cart
  has_one :user, through: :product  
end

Mypayment
class MyPayment < ActiveRecord::Base
    belongs_to :shopping_cart
    include AASM 

    aasm column: "status" do
        state :created, initial: true
        state :payed
        state :failed

        event :pay do
            after do
                shopping_cart.pay!
                self.update_stock_products()
            end
            transitions from: :created, to: :payed
        end
    end

    def update_stock_products       
        self.shopping_cart.in_shopping_carts.map { |i_sh|
            product = i_sh.product                  
            res = product.stock - i_sh.num_products 
            Product.update(product.id,stock: res)                   
        }       
    end
end

PaymentsController

class PaymentsController < ApplicationController  

  def checkout
    @my_payment = MyPayment.find_by(paypal_id: params[:paymentId])
    if @my_payment.nil?
        redirect_to "/carrito"
    else    
        Stores::Paypal.checkout(params[:PayerID],params[:paymentId]) do     
            @my_payment.pay!
            redirect_to ok_path, notice: "Se proceso el pago con Paypal"
            return 
      end   
        redirect_to carrito_path, notice:"Hubo un error al procesar el pago"        
    end
  end
  def process_card
    paypal_helper = Stores::Paypal.new(@shopping_cart.total,
                                       @shopping_cart.items,
                                       return_url: checkout_url,
                                       cancel_url: carrito_url)
    if paypal_helper.process_card(params).create
        @my_payment = MyPayment.create!(paypal_id: paypal_helper.payment.id,
                                        ip:request.remote_ip,
                                        email: params[:email],
                                        shopping_cart_id: cookies[:shopping_cart_id])
        @my_payment.pay!
        redirect_to carrito_path, notice:"El pago se realizo correctamente"
    else
        redirect_to carrito_path, notice: paypal_helper.payment.error
    end         
  end
  def create
    paypal_helper = Stores::Paypal.new(@shopping_cart.total,
                                       @shopping_cart.items,
                                       return_url: checkout_url,
                                       cancel_url: carrito_url)
    if paypal_helper.proccess_payment.create

        @my_payment = MyPayment.create!(paypal_id: paypal_helper.payment.id,
                                        ip:request.remote_ip,
                                        shopping_cart_id: cookies[:shopping_cart_id])
        redirect_to paypal_helper.payment.links.find{|v| v.method == "REDIRECT" }.href
    else
        raise paypal_helper.payment.error.to_yaml
    end
  end
end

StackoverFlow: http://stackoverflow.com/questions/43299511/i-cant-get-the-total-money-of-the-shopping-cart-when-i-update-the-number-of-prod

**Comment by fanambinantsoa** [comment]
orry, I use the SDK-PayPal is I have a problem on this case (Codeingiter 3).
```
PayPal\Exception\PayPalConnectionException Object ( [url:PayPal\Exception\PayPalConnectionException:private] => https://api.sandbox.paypal.com/v1/payments/payment [data:PayPal\Exception\PayPalConnectionException:private] => {"name":"VALIDATION_ERROR","details":[{"field":"transactions[0]","issue":"Item amount must add up to specified amount subtotal (or total if amount details not specified)"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"cf9326de68646"} [message:protected] => Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment. [string:Exception:private] => [code:protected] => 400 [file:protected] => E:\Xampp\htdocs\madsc\vendor\paypal\rest-api-sdk-php\lib\PayPal\Core\PayPalHttpConnection.php [line:protected] => 207 [trace:Exception:private] => Array ( [0] => Array ( [file] => E:\Xampp\htdocs\madsc\vendor\paypal\rest-api-sdk-php\lib\PayPal\Transport\PayPalRestCall.php [line] => 78 [function] => execute [class] => PayPal\Core\PayPalHttpConnection [type] => -> [args] => Array ( [0] => {"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://localhost/madsc/paypal/getPaymentStatus","cancel_url":"http://localhost/madsc/paypal/getPaymentStatus"},"transactions":[{"description":"Achat de page sur Mad Services Consulting","amount":{"currency":"EUR","total":755,"details":{"tax":126,"subtotal":629}},"invoice_number":"5de90cbd5c9fd","item_list":{"items":[{"name":"Art'AgriMAD - pleine page Quadri HT sans choix de page- qte 1page
Art'AgriMAD - pleine page Quadri derniere page de couverture- qte 1page
","sku":"12345","description":"Art'AgriMAD - pleine page Quadri HT sans choix de page- qte 1page
Art'AgriMAD - pleine page Quadri derniere page de couverture- qte 1page
","currency":"EUR","quantity":2,"price":629}]}}]} ) ) [1] => Array ( [file] => E:\Xampp\htdocs\madsc\vendor\paypal\rest-api-sdk-php\lib\PayPal\Common\PayPalResourceModel.php [line] => 104 [function] => execute [class] => PayPal\Transport\PayPalRestCall [type] => -> [args] => Array ( [0] => Array ( [0] => PayPal\Handler\RestHandler ) [1] => /v1/payments/payment [2] => POST [3] => {"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://localhost/madsc/paypal/getPaymentStatus","cancel_url":"http://localhost/madsc/paypal/getPaymentStatus"},"transactions":[{"description":"Achat de page sur Mad Services Consulting","amount":{"currency":"EUR","total":755,"details":{"tax":126,"subtotal":629}},"invoice_number":"5de90cbd5c9fd","item_list":{"items":[{"name":"Art'AgriMAD - pleine page Quadri HT sans choix de page- qte 1page
Art'AgriMAD - pleine page Quadri derniere page de couverture- qte 1page
","sku":"12345","description":"Art'AgriMAD - pleine page Quadri HT sans choix de page- qte 1page
Art'AgriMAD - pleine page Quadri derniere page de couverture- qte 1page
","currency":"EUR","quantity":2,"price":629}]}}]} [4] => Array ( ) ) ) [2] => Array ( [file] => E:\Xampp\htdocs\madsc\vendor\paypal\rest-api-sdk-php\lib\PayPal\Api\Payment.php [line] => 571 [function] => executeCall [class] => PayPal\Common\PayPalResourceModel [type] => :: [args] => Array ( [0] => /v1/payments/payment [1] => POST [2] => {"intent":"sale","payer":{"payment_method":"paypal"},"redirect_urls":{"return_url":"http://localhost/madsc/paypal/getPaymentStatus","cancel_url":"http://localhost/madsc/paypal/getPaymentStatus"},"transactions":[{"description":"Achat de page sur Mad Services Consulting","amount":{"currency":"EUR","total":755,"details":{"tax":126,"subtotal":629}},"invoice_number":"5de90cbd5c9fd","item_list":{"items":[{"name":"Art'AgriMAD - pleine page Quadri HT sans choix de page- qte 1page
Art'AgriMAD - pleine page Quadri derniere page de couverture- qte 1page
","sku":"12345","description":"Art'AgriMAD - pleine page Quadri HT sans choix de page- qte 1page
Art'AgriMAD - pleine page Quadri derniere page de couverture- qte 1page
","currency":"EUR","quantity":2,"price":629}]}}]} [3] => [4] => PayPal\Rest\ApiContext Object ( [requestId:PayPal\Rest\ApiContext:private] => [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object ( [clientId:PayPal\Auth\OAuthTokenCredential:private] => ASTB0CEXGvvsh9_-ScNVC0wB1S20MkvDsgeFNR9fXCZk-RzUt6CmRI_zM5L27WjkQtvA4kRFrLKvxVO_ [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EJzls85gIUxv0eXzJEW7faDIG40TPSyPxhXqvIaSyGVDUu1fIiOGevuhMTFRCzZYaa3vWQuC25KYcMon [targetSubject:PayPal\Auth\OAuthTokenCredential:private] => [accessToken:PayPal\Auth\OAuthTokenCredential:private] => A21AAHps76brAwupURCtYGK_sQq_3HwWHbyA-iQXIIIyN9X-SrR4qCvRwitrdJnm7_-j5Aj9AiaWfyPmeYRPUgZAObtaahphw [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 29303 [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 1575554241 [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object ( [secretKey:PayPal\Security\Cipher:private] => EJzls85gIUxv0eXzJEW7faDIG40TPSyPxhXqvIaSyGVDUu1fIiOGevuhMTFRCzZYaa3vWQuC25KYcMon ) [_propMap:PayPal\Common\PayPalModel:private] => Array ( ) ) ) [5] => PayPal\Transport\PayPalRestCall Object ( [logger:PayPal\Transport\PayPalRestCall:private] => PayPal\Core\PayPalLoggingManager Object ( [logger:PayPal\Core\PayPalLoggingManager:private] => PayPal\Log\PayPalLogger Object ( [loggingLevels:PayPal\Log\PayPalLogger:private] => Array ( [0] => emergency [1] => alert [2] => critical [3] => error [4] => warning [5] => notice [6] => info [7] => debug ) [loggingLevel:PayPal\Log\PayPalLogger:private] => info [loggerFile:PayPal\Log\PayPalLogger:private] => application/logs/paypal.log [isLoggingEnabled:PayPal\Log\PayPalLogger:private] => 1 [loggerName:PayPal\Log\PayPalLogger:private] => PayPal\Transport\PayPalRestCall ) [loggerName:PayPal\Core\PayPalLoggingManager:private] => PayPal\Transport\PayPalRestCall ) [apiContext:PayPal\Transport\PayPalRestCall:private] => PayPal\Rest\ApiContext Object ( [requestId:PayPal\Rest\ApiContext:private] => [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object ( [clientId:PayPal\Auth\OAuthTokenCredential:private] => ASTB0CEXGvvsh9_-ScNVC0wB1S20MkvDsgeFNR9fXCZk-RzUt6CmRI_zM5L27WjkQtvA4kRFrLKvxVO_ [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EJzls85gIUxv0eXzJEW7faDIG40TPSyPxhXqvIaSyGVDUu1fIiOGevuhMTFRCzZYaa3vWQuC25KYcMon [targetSubject:PayPal\Auth\OAuthTokenCredential:private] => [accessToken:PayPal\Auth\OAuthTokenCredential:private] => A21AAHps76brAwupURCtYGK_sQq_3HwWHbyA-iQXIIIyN9X-SrR4qCvRwitrdJnm7_-j5Aj9AiaWfyPmeYRPUgZAObtaahphw [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 29303 [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 1575554241 [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object ( [secretKey:PayPal\Security\Cipher:private] => EJzls85gIUxv0eXzJEW7faDIG40TPSyPxhXqvIaSyGVDUu1fIiOGevuhMTFRCzZYaa3vWQuC25KYcMon ) [_propMap:PayPal\Common\PayPalModel:private] => Array ( ) ) ) ) ) ) [3] => Array ( [file] => E:\Xampp\htdocs\madsc\application\controllers\Paypal.php [line] => 163 [function] => create [class] => PayPal\Api\Payment [type] => -> [args] => Array ( [0] => PayPal\Rest\ApiContext Object ( [requestId:PayPal\Rest\ApiContext:private] => [credential:PayPal\Rest\ApiContext:private] => PayPal\Auth\OAuthTokenCredential Object ( [clientId:PayPal\Auth\OAuthTokenCredential:private] => ASTB0CEXGvvsh9_-ScNVC0wB1S20MkvDsgeFNR9fXCZk-RzUt6CmRI_zM5L27WjkQtvA4kRFrLKvxVO_ [clientSecret:PayPal\Auth\OAuthTokenCredential:private] => EJzls85gIUxv0eXzJEW7faDIG40TPSyPxhXqvIaSyGVDUu1fIiOGevuhMTFRCzZYaa3vWQuC25KYcMon [targetSubject:PayPal\Auth\OAuthTokenCredential:private] => [accessToken:PayPal\Auth\OAuthTokenCredential:private] => A21AAHps76brAwupURCtYGK_sQq_3HwWHbyA-iQXIIIyN9X-SrR4qCvRwitrdJnm7_-j5Aj9AiaWfyPmeYRPUgZAObtaahphw [tokenExpiresIn:PayPal\Auth\OAuthTokenCredential:private] => 29303 [tokenCreateTime:PayPal\Auth\OAuthTokenCredential:private] => 1575554241 [cipher:PayPal\Auth\OAuthTokenCredential:private] => PayPal\Security\Cipher Object ( [secretKey:PayPal\Security\Cipher:private] => EJzls85gIUxv0eXzJEW7faDIG40TPSyPxhXqvIaSyGVDUu1fIiOGevuhMTFRCzZYaa3vWQuC25KYcMon ) [_propMap:PayPal\Common\PayPalModel:private] => Array ( ) ) ) ) ) [4] => Array ( [file] => E:\Xampp\htdocs\madsc\system\core\CodeIgniter.php [line] => 532 [function] => create_payment_with_paypal [class] => Paypal [type] => -> [args] => Array ( ) ) [5] => Array ( [file] => E:\Xampp\htdocs\madsc\index.php [line] => 315 [args] => Array ( [0] => E:\Xampp\htdocs\madsc\system\core\CodeIgniter.php ) [function] => require_once ) ) [previous:Exception:private] => )
```


Reponse json dans Log

```
05-12-2019 14:57:23] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 400
[05-12-2019 14:57:24] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment. {"name":"VALIDATION_ERROR","details":[{"field":"transactions[0]","issue":"Item amount must add up to specified amount subtotal (or total if amount details not specified)"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"cf9326de68646"}

```
Can you help me please?

**Comment by prakash-gangadharan** [comment]
Hi @fanambinantsoa,  this issue was closed a long ago,  can you open a new issue to check it further.
