### ISSUE TITLE
Support for multiple recipients (parallel payments)

### ISSUE THREAD

**Issue by mslinn** [paypal/PayPal-Java-SDK#166]
Is there support for splitting the payment amongst multiple recipients?

**Comment by juwlee** [comment]
Hi @mslinn [PayPal AdaptivePayment SDK](https://github.com/paypal/adaptivepayments-sdk-java) supports the functionality.

**Comment by mslinn** [comment]
My point is that the REST library does not, and I would like to request that the capability be added to the REST library.

**Comment by juwlee** [comment]
Thanks @mslinn for clarifying. The request is being tracked under [this issue](https://github.com/paypal/PayPal-iOS-SDK/issues/9)
