### ISSUE TITLE
Resource Not Found (./src/main/resources/sdk_config.properties)

### ISSUE THREAD

**Issue by namack75** [paypal/PayPal-Java-SDK#184]
### General Information

- Mode (Sandbox/Live):
- PayPal-Debug-ID(s) (from any logs):
- Version of Java used: 1.8
- SDK Version: 1.6

### Issue Description

WIth the update to 1.6, am now getting a file not found error (./src/main/resources/sdk_config.properties). 

We don't use the sdk_config file, rather we generate our own Map and hand it off to the OAuthTokenCredential class.

**Comment by jaypatel512** [comment]
Currently, it is mandatory to have sdk_config.properties file in your resource directory. We have seen that this feature has become outdated now, and should be removed. We have a current PR https://github.com/paypal/PayPal-Java-SDK/pull/182 which makes this optional. I am currently reviewing the PR. It would be great if you can help us test and verify if the PR works for you. This should help me get beta testing done, and merge that pull request faster.

However, for now, you will need to have an sdk_config.properties file. An empty file should also do the trick for now.

**Comment by sankarbhavanib** [comment]
@namack75  Can you please check out the code from master branch and test your scenario and let us know if you still facing Resource Not Found issue

**Comment by sankarbhavanib** [comment]
@namack75 This change will be on our next release .  please let us know or re-open if the problem persists
