### ISSUE TITLE
REST response must be logged in live mode for debugging

### ISSUE THREAD

**Issue by reinholdbentele** [paypal/PayPal-Java-SDK#188]
### General Information

- Mode (Sandbox/Live): Live
- PayPal-Debug-ID(s) (from any logs): -
- Version of Java used: 1.8
- SDK Version: 1.3.0

#### Summary
We experienced cases in live mode in which a `FuturePayment` could not be created (with `Payment#create`) because null was returned and no exception was raised.

#### Details
We use `FuturePayment#create(APIContext)` in our code and have this call embedded in a try-catch for `PayPalRESTException`. We also check if the result from the method call returns null. Recently, we had a case where null was returned and no exception was raised. In `PayPalResource#execute`, requests and responses are not logged in live mode.

_Since nothing was logged, how should we find out what happened and why we could not charge the customer?_

**Comment by jaypatel512** [comment]
You can use `PayPalResource.getLastRequest()` and `PayPalResource.getLastResponse()` to log the live messages. However, keep in mind the security implications of logging live data, specially the request, which may contain full credit card numbers.
