### ISSUE TITLE
@deprecated are not including alternatives or recommended alternatives.

### ISSUE THREAD

**Issue by silentsnooc** [paypal/PayPal-Java-SDK#197]
This just a minor suggestion for `v1.7.0`: Please provide more information for deprecated methods e.g. like

1) What to use instead
2) (optional) How long support will ve kept for deprecated functionality

For example in `ConfigManager` we see:

```java
	/**
	 * Returns a value for the corresponding key
	 * 
	 * @deprecated
	 * 
	 * @param key
	 *            String key
	 * @return String value
	 */
	public String getValue(String key) {
		return properties.getProperty(key);
	}
``` 

but no additional information.

**Comment by jaypatel512** [comment]
Hey @silentsnooc !

I completely agree. I would definitely add more information about the deprecation. I  will make sure to add more details to any newer deprecations, and will work on updating the existing ones. 

In the mean time, if you feel optimistic, and would like to help us out, feel free to send us a PR. 

Thanks again for pointing this out.

**Comment by silentsnooc** [comment]
Hi! :) 

Thanks for the reply! Yes, at least the information where else to turn instead would be very useful. As any other developer I guess I try to avoid using deprecated functionality right away if possible.

I do not have the time to actively contribute unfortunately but should I ever find or see something critical I will of course let you guys know or fix it and provide a PR if possible! :)

I'd have one more additional suggestion: Looking for something to create a billing plan I saw that the appropriate class currently seems to be currently `com.paypal.api.payments.Plan`. It's just a nice to have but if the classes would follow the naming from the actual REST API it would be easier to get to know the library and would also prevent confusion. So in this case I would suggest the renaming of `Plan` into `BillingPlan` if that makes sense.

BR; Stefan

**Comment by jaypatel512** [comment]
Hey @silentsnooc !

We have added proper deprecation messages to all the methods/fields we have deprecated ever. Please let us know if you find any which we missed. Thanks for helping.
