### ISSUE TITLE
"Payments using credit card information" sample - UNKNOWN_ERROR

### ISSUE THREAD

**Issue by dormitionskete** [paypal/PayPal-Java-SDK#198]
### General Information

- Mode (Sandbox/Live):  Sandbox
- PayPal-Debug-ID(s) (from any logs): 162ee4c61d70f
- Version of Java used: java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)
- SDK Version: Should be the same.

- IDE: NetBeans 8.0.1 on Mac OSX 10.9.5
- Tomcat 7.0.64

### Issue Description

I downloaded the PayPal Rest API code on June 21st.  With a fresh install of that code, with no changes whatsoever made to it, I can run the "PayPal Payments" sample, and at least get the token back.  

However, when I try to run the "Payments using credit card information" sample, all I ever get back is something along the lines of this:

```
Response Object

Error code : 400 with response : {"name":"UNKNOWN_ERROR","message":"An unknown error has occurred","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"162ee4c61d70f"}

```
That message is strictly from your code with no changes.  I've also tried it with our sandbox credentials, using credit card information from one of our test accounts with similar results.

Can someone please shed some light on this "unknown error"?  If so, we'd *greatly* appreciate it.

We're having a whole different problem with some code that used to work in the Sandbox test environment last January, so we're trying to go back to "ground zero", i.e. we're trying to go back to strictly PayPal code, and even it isn't working for us any more.  

So, if somebody could please shed some light on this, we'd really appreciate it.

**Comment by jaypatel512** [comment]
In sandbox, we have had issues with overused credit card numbers. 

Please use link 4 of https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1413&viewlocale=en_US&direct=en, and generate a new credit card number, and try the sample again. 

Please re-open the issue if this issue still persists.
