### ISSUE TITLE
Billing agreement start_date is set different in paypal from what is provided in billing agreement JSON request

### ISSUE THREAD

**Issue by viper-pranish** [paypal/PayPal-Java-SDK#207]
### Agreement Date Details

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs):
- Version of Java used: 1.8.0_91
- SDK Version: 1.8.0

When creating a billing agreement, I provided start_date in ISO 8601 GMT format as required by paypal. 

Here is my JSON request for billing agreement

```json
{
 "agreementName":"Final Billing Agreement for testing daily agreements",
"agreementDescription":"This final agreement is daily payment agreement used for testing. Amount 99.99",
"agreementStartDate":"2016-07-06T03:00:23Z",
"payerEmail": "pranish-final@email.com",
"payerFirstName":"Pranish",
"payerLastName":"Shrestha",
"payerPaymentMethod":"credit_card",
"shippingCity":"Saratoga",
"shippingState":"CA",
"shippingCountryCode":"US",
"shippingPostalCode":"95070",
"shippingPhone":"9807561045",
"shippingLine1":"27 Ason Tole"
}
```

Well as you see these are the values provided in DTO which will be set to the correspondent attributes for agreement when it gets executed. I have the following details on time when comparing  webhook, paypal and JSON request values.

`agreement created on 	:- 2016-07-06T03:59:39Z		(According to webhook detail)	`
`agreement created on 	:- 09:45:31 A.M 	                       (According to paypal notification from https://developer.paypal.com/developer/notifications/)`	`agreement start date 	:- 2016-07-06T04:00:23Z		(Provided while creating agreement)`
`agreement start date	:- 2016-07-06T11:00:23Z		(According to webhook detail)`
`Next billing Date       	:- 2016-07-06T10:00:00Z		(According to webhook detail)`
`Final Payment Due Date :- 2016-07-14T10:00:00Z		(According to webhook detail)`

The time difference between GMT and my local time is 05:45 hrs.

**Comment by pp-randy** [comment]
I tested and I am also seeing this behavior.  I will follow up internally for more details and follow up further here when I have more information.

**Comment by viper-pranish** [comment]
Thank you @pp-randy . Its been about a month I posted this issue and still I am not being able to solve this. Please reply as soon as possible.

**Comment by pp-randy** [comment]
@viper-pranish my sandbox account is in Pacific Daylight Time, my start_date is being treated as PDT  although that is not my physical timezone.  My response is then in GMT and 7 hours ahead.

**Comment by viper-pranish** [comment]
Yes. My sandbox account is of US so it uses PDT and I am from nepal. I convert the nepali time to GMT and set is as a start_date. Then again paypal returns time in PDT timezone by adding 7 hours.

**Comment by pp-randy** [comment]
@viper-pranish sorry for the delay.  I created a UK test sandbox account with BET timezone, and my start_date was not acting exactly how I expected.  I also need to apologize as I didn't fully understand how start_date was behaving and I was confounded by coincidence of testing around 7 AM Pacific time. 

Here is how start date is being handled. 
1. Input 2016-10-25 09:16:13  <- Pacific Time
2. **PayPal truncates the input to the start of the day** so the time is now 2016-10-25 00:00:00 Pacific Time.

start_date in the Agreement Details Lookup, this is where Account Timezone comes in. 
Pacific Account: 2016-10-25 07:00:00(UTC) (2016-10-25 00:00:00 Pacific)
London Account: 2016-10-24 23:00:00(UTC) (2016-10-25 00:00:00 BET/London)
