### ISSUE TITLE
tokenservice is broken

### ISSUE THREAD

**Issue by bmartin1134** [paypal/PayPal-Java-SDK#208]
### General Information

- Mode Sandbox:
- PayPal-Debug-ID(s) (from any logs): unknown
- Version of Java used: 1.8
- SDK Version: LATEST

### Issue Description

>  The login with paypal items seem broke to me, specifically tokenservice. The TokenInfo class IMO should create an api context and return that. Instead it is initiating an apicontext and then trying to resolve the tokeninfo with an authorization header instead of the user client:secret.

**Proper tokenservice request:**
curl command: 
curl -v 'https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice' \
-u "{CLIENT}:{SECRET}" \
-d "grant_type=authorization_code&code=-YIibARVKKyRfhhKSBudWgEpI9xKQ3EGQLjVWlQbOLtYMbdPKx5FELNqY37Z0blMcVHn3jKJ_-y428L-q3cwzmxLzmrUBXIhkiAN_szd3TMK3MdWQ2byC8PEzr46w6XGNRVN1R_P2abWwWAKT8CU89R1Eyqia0E1Zprt6jGDmAvfFhnu3gIhA48E6Mrt1BEaSiH8Jr-lEt-G1teX"

**API generated request:**
curl command: 
curl -v 'https://api.sandbox.paypal.com/v1/identity/openidconnect/tokenservice' \
-H "Authorization: Basic QVlHUEQxTHBodzRhT1dCQWZ1VzFYbDlCNl9LMGN5MjludGtINUJiZXFGemhBQXdkZnk1THFfWlJhalRLWkZZUlpNaUkzZk4yeGhmc28xcFM6RUd0VDJMczBnX2RCSlA2VXg2cTBvOU80ZV9lMl8yakNSUk9nOXJ2aVNnVkZnLV9sUjJDSVNIQ3dNXy1UWnlSRHBGZ29pTXFGazNra29zNGc=" \
-H "User-Agent: PayPalSDK/  (v=1.8.0_25; vendor=Oracle Corporation; bit=64; os=Mac_OS_X 10.11.5)" \
-H "Accept: application/json" \
-H "Content-Type: application/json" \
-d 'code=uzvBwIqVPVJAJE6dpbSUrn-EOVwPwc4fNR1aovuq9Vpj5aFNNGGOD2vuvPwiieQV8A4VQLpCC-ARlY35FmkeqcU9g2U4GmNYzHwi53gy4JIKqi7-g_Tr0yqsa15bHSpVwPfS5D5_lyLXsrTYRSd37_kYICW6rCreCEFZrsGOUwtueNSijkl2rv9YXM66oZjzPwaykvzp9Wl2iku6&grant_type=authorization_code'

**Comment by jaypatel512** [comment]
Hello @bmartin1134 !

Passsing `-u {clientId}:{secret}` will yield the same result as `Authorization` header. It should not make a difference in the calls. However, are you seeing any errors when making calls to openIdConnect. We have been working on making major changes to how you integrate. We have done that for normal API payments (except identity). 

Ideally, we should be sending the `apiContext` as you mentioned to the call, and make it easy to use.

**Comment by bmartin1134** [comment]
I don't think the endpoint for tokenservice will accept -H "Authorization: Basic ...".

The main error that gets thrown is "grant_type" is null, even though it is a part of the payload.

**Comment by jaypatel512** [comment]
Closing this issue for now. Please re-open if the new release still does not fix your issue.

**Comment by bmartin1134** [comment]
I'm offsite until later this evening but I will check then. Thanks for the speediness!
