### ISSUE TITLE
Reference field is missing from Invoice

### ISSUE THREAD

**Issue by ziglee** [paypal/PayPal-Java-SDK#211]
Reference field is missing from Invoice. That's pretty much it.

**Comment by jaypatel512** [comment]
Hey @ziglee !

Do you mean the `reference_id` in the Authorization Object ?

**Comment by ziglee** [comment]
No. This one: https://developer.paypal.com/docs/api/invoicing/#invoices_create

> reference string
> Reference` data, such as PO number, to add to the invoice. Maximum length is 60 characters.

`cc_info` field is missing too

**Comment by jaypatel512** [comment]
Thanks @ziglee !

I will go ahead and quickly fix that :) It should be available in next release.
