### ISSUE TITLE
service.EndPoint is not honored

### ISSUE THREAD

**Issue by EtonDoze** [paypal/PayPal-Java-SDK#220]
### General Information

- Mode (Sandbox/Live): Other
- PayPal-Debug-ID(s) (from any logs):
- Version of Java used: 1.8
- SDK Version: LATEST

### Issue Description
I understand that SDK expects `sdk_config.properties` to store constants. The value for `service.EndPoint` from  `sdk_config.properties` is ignored at runtime and a hardcoded value from [com.paypal.base.Constants#REST_SANDBOX_ENDPOINT](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/Constants.java#L187) is used.

It would be nice to allow `mode`  to take values other then `sandbox` or `live` and honor `service.EndPoint` from `sdk_config.properties`

```
public APIContext(String clientID, String clientSecret, String mode)
```

**Comment by jaypatel512** [comment]
Hey @EtonDoze !

We are moving away from the need to have a sdk_config.properties files. Generally, paypal serves only two environments "Sanbox" and "Live" currently. We do not have any plans at all to support different environments. 

We are trying to make it extremely simple for developers to integrate this SDK, and `mode` serves the purpose perfectly. We have added a wiki section to demonstrate how to integrate the latest SDKs, shown here in [Making First Call](https://github.com/paypal/PayPal-Java-SDK/wiki/Making-First-Call).

**Comment by aquarelius-** [comment]
Hi @jaypatel512,

I understand the purpose of removing service.EndPoint from properties, but I am dependent on IPN events for which I may need to change service.EndPoint value. 

Specifically you latest API lacks support for WebHooks (see ticket https://github.com/paypal/PayPal-Python-SDK/issues/132), so with your latest changes there is no workaround for me anymore to use IPN events until you deliver WebHooks implementation.

Any idea?

Thanks

**Comment by jaypatel512** [comment]
IPN are the part of [Classic SDKs](https://github.com/paypal/sdk-core-java), and it uses SDK Core Java project to make calls for any SOAP/XML based APIs. You should be able to still continue to use SDK Core Java to fetch IPN operations in the mean time. 

I will go ahead and try to see if I could get the service.Endpoint to work properly. Ideally, if you do not set the `mode`, we look for `service.Endpoint` value, even right now as shown here: https://github.com/paypal/PayPal-Java-SDK/blob/2f0f1dbab6a419131bb4d58f84fa05c3ea4fa17c/rest-api-sdk/src/main/java/com/paypal/base/rest/RESTAPICallPreHandler.java#L202
