### ISSUE TITLE
Validating Event Signature

### ISSUE THREAD

**Issue by theyuv** [paypal/PayPal-Java-SDK#222]
### General Information

- sandbox
- jdk1.8.05
- rest-api-sdk-1.8.1

### Issue Description

Should I be able to use the SDK to validate an event signature?
I tried calling `Event.validateReceivedEvent()` with the appropriate params:
APIContext - generated with my client_id, secret and mode.
headers - retrieved from the request.
body - retrieved as outlined in the `getBody()` method here:
https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sample/src/main/java/com/paypal/api/payments/servlet/ValidateWebhookServlet.java

However, I get a `NumberFormatException` in `SSLUtil.downloadCertificateFromPath()`. Specifically, on line 245 where the connection timeout is set.
Perhaps I need to configure some specific parameters like the webhook-ID? Or does the SDK know how to retrieve that?

Can I use the SDK for validating an event? Or do I need to code the validation myself as outlined here:
https://developer.paypal.com/docs/integration/direct/rest-webhooks-overview/#event-security

Thank you.

**Comment by jaypatel512** [comment]
You will need to add your webhook Id as a configuration in your apiContext. You can do so using 

`apiContext.addConfiguration(Constants.PAYPAL_WEBHOOK_ID, WebhookId);`.

**Comment by theyuv** [comment]
Hello Jay and thank you for replying.

I actually tried adding that configuration to the APIContext Object earlier.
However, I still got the same NumberFormatException.

Anything else missing in my call?

**Comment by jaypatel512** [comment]
Hey @theyuv !

I tried to reproduce the webhook validation just now, and was able to reproduce the error you are seeing. We made some substantial improvements to APIContext/Access Token objects to make it extremely simple to integrate. 

I have created a new PR for [webhook validation](https://github.com/paypal/PayPal-Java-SDK/pull/223) just now, and will finish it up extremely soon. Once this is released (which should be really fast), you should be able to update your code to make this easy to read and fix the issue you are seeing. Thanks for your patience. 

I do recommend taking a look at the PR and see if there is anything I could do to improve it even further.

**Comment by jaypatel512** [comment]
Hey @theyuv !

Will you be able to help us confirm the changes that we did, works for you properly. I have merged the PR into the master. If you could use the master branch and let us know if this fixed your issue, we can go ahead and make a release. 

Thanks again for your patience.

**Comment by theyuv** [comment]
Hey and thanks for attending to the issue.
I'm a little new to GitHub.
When I downloaded the SDK I simply downloaded the jar from the Maven repository (and separately downloaded the jars of the dependencies).
If I want to test out the changes that you've committed, how would I go about doing this?
Do I download it from GitHub and then use Maven to build it?

In general if you have a recommendation for how better to work with GitHub I'd be happy to hear it.

Thanks again.

**Comment by jaypatel512** [comment]
These are the steps to create a new jar from the master branch. These would be the steps:

1. If you know `git clone`, do `git clone git@github.com:paypal/PayPal-Java-SDK.git` or just download the `master` branch directly [from here](https://github.com/paypal/PayPal-Java-SDK/archive/master.zip). 
2. Unzip if required.
3. In command line, run `./gradlew clean build`.
4. This will run few unit tests, and compile some stuffs. 
5. Once completed, you should be able to get a new jar at `rest-api-sdk/build/libs/rest-api-sdk-1.9.1.jar` location. Please use that jar instead of the one you download from maven. 

Let me know if that works for you.

**Comment by theyuv** [comment]
Thank you.
I tried this and the build failed (`org.apache.logging.slf4j.Log4jLoggerFactory cannot be cast to org.gradle.logging.internal.slf4j.OutputEventListenerBackedLoggerContext`)
I also tried to build with Maven but wasn't sure how to create the POM file correctly.
Sorry.
Once the jar file is available on Maven I'll gladly test it out.

**Comment by jaypatel512** [comment]
Hey @theyuv !

The [new release 1.9.2](https://github.com/paypal/PayPal-Java-SDK/releases/tag/v1.9.2) have been made with this enhancement.
