### ISSUE TITLE
Webhook event for payment approval

### ISSUE THREAD

**Issue by theyuv** [paypal/PayPal-Java-SDK#224]
### General Information

- sandbox
- jdk1.8.05
- rest-api-sdk-1.8.1

### Issue Description

I use the REST API to create a payment and redirect the payer to the approval link.
Once the payer approves the payment, he is redirected back to the return url (on my website) and the payment is executed.
Rather than relying entirely on the redirect url for executing a payment (after it is approved), I would like to execute the payment based on a webhook event.
This way, if something goes wrong and the payer isn't redirected to the return url (after approving the payment), my application can still execute his payment after it is approved.
Is there an event that can notify me when a payment is approved?
Or, can I trust that the payer will always be redirected to the return url and therefore I do not need a webhook event to notify me of the payment's approval? 
(With the Classic API, I used an IPN in this case because it was suggested not to rely on the payer returning to the return url).

Thank you.

**Comment by theyuv** [comment]
This is intentional. 
Before the payer approves the payment, the form says "You're almost done, you will be redirected for final approval".
Meaning approval is based on the payer hitting the return url.

**Comment by jaypatel512** [comment]
You cannot execute the payment without a successful redirect. You can be sure that the buyer will always be redirected correctly. However, I like the idea of adding another event when the user agrees to the payment, just before the redirect. I will pass along the idea to the API team, and let them think a bit more into it. 

However, for now, you should be fine waiting for the redirect. Make sure you consider both cases where the user agrees to pay, and also the case where the user denies to pay.

**Comment by theyuv** [comment]
Thanks a lot.
I think actually think this might be by design, because it says something like "You will be redirected to the website for final approval" at the bottom of the payer's form on PayPal when he's approving the payment.
Meaning PayPal intentionally wants the user to return to my website before the payment is executed.
But I'd be interested in hearing what the API team has to say.

Thanks.
