### ISSUE TITLE
No log4j2 configuration file found

### ISSUE THREAD

**Issue by theyuv** [paypal/PayPal-Java-SDK#225]
### General Information

- sandbox
- jdk1.8.05
- paypal-rest-api-1.8.1

### Issue Description

I get the following message printed to my server console when using the PayPal REST SDK:

`ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.`

How can I fix this so that the error doesn't get printed?

Thank you.

**Comment by bluk** [comment]
See the [log4j2 Configuration documentation](http://logging.apache.org/log4j/2.x/manual/configuration.html) for ways to set the config.

The PayPal-Java-SDK uses [SLF4J](http://www.slf4j.org)'s logging bridge to log4j2. If you wish to use a different logger, you can exclude the [log4j2](https://github.com/paypal/PayPal-Java-SDK/blob/fbe1b5fc1f5c0e770249c3471f461e46d6546890/build.gradle#L58) dependencies using [Gradle](http://stackoverflow.com/questions/21764128/how-do-i-exclude-all-instances-of-a-transitive-dependency-when-using-gradle) or [Maven](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) depending on your build tool. Then you should include the appropriate SLF4J logging implementation.

**Comment by jaypatel512** [comment]
Hey @theyuv !

I think you get some help running the sample project too. It has a [sample log4j2.xml](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sample/src/main/resources/log4j2.xml) that you could start with.

**Comment by theyuv** [comment]
@bluk Thank you.
According to the documentation you referenced (specifically: http://logging.apache.org/log4j/2.x/log4j-jcl/index.html), I need the bridge jar and the log4j jar in my classpath, which I have.
I have slf4j-api, log4j-slf4j, log4j-core and log4j-api jars as per the dependencies of the REST API.
Am I still missing something?

@jaypatel512 Thanks.
If I were to include the same sample log4j2.xml file that you referenced, where would I include it in my project? In which directory?

Thanks a lot.

**Comment by jaypatel512** [comment]
Generally it goes into `src/main/resource`.

This is how your dependencies would look like:

```gradle
dependencies {
        ...
        compile 'log4j:log4j:1.2.14'
        compile 'org.apache.logging.log4j:log4j-api:2.1'
        compile 'org.apache.logging.log4j:log4j-core:2.1'
    }
```

**Comment by FesenkoAnton** [comment]
Thank you

**Comment by roman4ello** [comment]
Thank you guys!
