### ISSUE TITLE
"Billing Plan" examples for Java API

### ISSUE THREAD

**Issue by silentsnooc** [paypal/PayPal-Java-SDK#226]
Under [PayPal-Java-SDK/rest-api-sample/src/main/java/com/paypal/api/payments/servlet](https://github.com/paypal/PayPal-Java-SDK/tree/master/rest-api-sample/src/main/java/com/paypal/api/payments/servlet) on can find some great examples for the usage of the REST API.

Unfortunately there's yet no example for recurring payments. 

It would be great to have at least one basic example for recurring payments there.

Btw: Imho the name `com.paypal.api.payments.Plan` is not a very good choice. I'd suggest to rename this to `com.paypal.api.payments.PaymentPlan` or `com.paypal.api.payments.RecurringPayment` and related classes accordingly.

**Comment by silentsnooc** [comment]
Found it: https://github.com/paypal/codesamples-java/blob/master/src/main/java/com/sample/merchant/CreateRecurringPaymentsProfile.java

Just looked at the wrong place. ^^

**Comment by sankarbhavanib** [comment]
@silentsnooc Thank you for the suggestion on class names, right now it's auto generated based on schema names and used across all SDKs. I will surely provide this feedback to API teams in cases they want to consider for next major release

Regarding the sample this is the closest we have at this point of time ‘https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sample/src/main/java/com/paypal/api/sample/SubscriptionSample.java`. We are working on adding more samples, I will let you know once they are ready

**Comment by silentsnooc** [comment]
Hi @sankarbhavanib ! Thanks, I'd be glad to get notified on updates :) I didn't know that this is generated but it makes sense of course. If it's being used across in all SDKs then it would probably be good to stick with the current naming :) 

Btw: I'm currently asking something about [patching](http://stackoverflow.com/questions/38642140/billing-plan-patch-http-400-invalid-path-provided) on stackoverflow if by chance you want to take a look at it. ^^

**Comment by sankarbhavanib** [comment]
@silentsnooc  It seems you resolved the patching issue also, I am closing this issue
