### ISSUE TITLE
Keep getting MissingCredentialException

### ISSUE THREAD

**Issue by silentsnooc** [paypal/PayPal-Java-SDK#227]
I'm sorry to post this here but I'm simply not getting what the problem is with my settings. I've created an application and selected a BUSINESS account that I created before for this app.

Then I simply used the credentials in my `sdk_config.properties` and tried to create a recurring payment.

```properties
# API accounts
acct1.UserName=business_api1.example.com
acct1.Password=xxxxxxxxxxxxxxxxxxxxx
acct1.Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
acct1.AppId=application-name
acct1.Subject=

# Credentials
clientId=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
clientSecret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

But for some reason I keep getting

```
com.paypal.exception.MissingCredentialException: No API accounts have been configured in application properties
	at com.paypal.core.CredentialManager.getCredentialObject(CredentialManager.java:47)
	at com.paypal.core.soap.MerchantAPICallPreHandler.getCredentials(MerchantAPICallPreHandler.java:388)
	at com.paypal.core.soap.MerchantAPICallPreHandler.initCredential(MerchantAPICallPreHandler.java:430)
	at com.paypal.core.soap.MerchantAPICallPreHandler.<init>(MerchantAPICallPreHandler.java:222)
	at urn.ebay.api.PayPalAPI.PayPalAPIInterfaceServiceService.createRecurringPaymentsProfile(PayPalAPIInterfaceServiceService.java:3436)
	at urn.ebay.api.PayPalAPI.PayPalAPIInterfaceServiceService.createRecurringPaymentsProfile(PayPalAPIInterfaceServiceService.java:3389)
```

I've deleted and recreated the App and the business account several times now but I'm still getting this exception and I don't see the problem.

The same question is on [stackoverflow](http://stackoverflow.com/questions/38556870/missingcredentialexception-no-api-accounts-have-been-configured-in-application) if you want to take a look at it there.

**Comment by jaypatel512** [comment]
Hey @silentsnooc !

We are deprecating the need for `sdk_config.properties` file. However, the code should work either way.

I would however recommend using the code snippet as shown here at [Making First Call in PayPal-Java-SDK](https://github.com/paypal/PayPal-Java-SDK/wiki/Making-First-Call).

```java

// Replace these values with your clientId and secret. You can use these to get started right now.
        String clientId = "AYSq3RDGsmBLJE-otTkBtM-jBRd1TCQwFf9RGfwddNXWz0uFU9ztymylOhRS";
        String clientSecret = "EGnHDxD_qRPdaLdZz8iCr8N7_MzF-YHPTkjs6NKYQvQSBngp4PTTVWkPZRbL";

        APIContext context = new APIContext(clientId, clientSecret, "sandbox");
```

and use that context when making any calls.
```java
try {
            card.create(context);
            System.out.println(card);
        } catch (PayPalRESTException e) {
            System.err.println(e.getDetails());
        }
```

**Comment by silentsnooc** [comment]
Hi @jaypatel512 and thanks for the quick response.

I figured out the issue was this

```java
Properties defaultProperties = ConfigManager.getDefaultProperties();

    service = new PayPalAPIInterfaceServiceService(defaultProperties);
```

Setting the path to the `sdk_config.properties` file instead fixed the problem.

What is the alternative going to look like *without* a `.properties` file actually?

**Comment by jaypatel512** [comment]
From the looks of the code, it feels like you are using Classic SDKs, and not REST API. In that case, you will have to use the sdk_config.properties file.
