### ISSUE TITLE
Old Codes in the sample need removing

### ISSUE THREAD

**Issue by phxism** [paypal/PayPal-Java-SDK#231]
### General Information

- Mode (Sandbox/Live):BOTH
- PayPal-Debug-ID(s) (from any logs):
- Version of Java used:1,6
- SDK Version:MASTER

### Issue Description
One.
init method to load sdk_config file in rest-api-sample\src\main\java\com\paypal\api\payments\servlet\GetPaymentHistoryServlet is no need,
Two 
script in index.html <script src="http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/md5.js"></script> is gone,404.change to an valid url such as 'https://cdn.bootcss.com/crypto-js/3.1.2/rollups/md5.js'
> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

**Comment by sankarbhavanib** [comment]
@phxism Thank you for the feedback , We will update the samples
