### ISSUE TITLE
Empty Exception Thrown by Paypal

### ISSUE THREAD

**Issue by fernando-lopez** [paypal/PayPal-Java-SDK#233]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs):error
"response-code: 0	details: null"
- Version of Java used: 1.7
- SDK Version: 1.7.0

### Issue Description

Trying to create an example subscription plan I get an exception with no details. This is the error message I get:

error "response-code: 0	details: null"

I'm getting the error in the line setupPlan = p.create(context);

This is my server code 

	String clientID = "XXXXX";
	String clientSecret = "XXXXX";										
	String ServerName = req.getServerName();					
	String ServerURL = "";					
	if (req.getServerName().toLowerCase() == "localhost")
		ServerURL = "http://localhost:8888/payment";
	else
		ServerURL = req.getProtocol() + "://" + req.getServerName() + "/payment";	

					
					
					

	SubscriptionPayment subscriptionPlan = new SubscriptionPayment();		
	Map<String, String> sdkConfig = new HashMap<String, String>();
	sdkConfig.put("mode", "sandbox");
	String accessToken = null;					
	try {
		accessToken = new OAuthTokenCredential(clientID, clientSecret, sdkConfig).getAccessToken();				
	} catch (PayPalRESTException e) {e.printStackTrace();}					
					
					
	com.paypal.api.payments.Plan p = new Plan();
	p.setName("T-Shirt of the Month Club Plan");
	p.setDescription("Template creation.");
	p.setType("fixed");
					
	//payment_definitions
	com.paypal.api.payments.PaymentDefinition payDef = new PaymentDefinition();
	payDef.setName("Regular Payments");
	payDef.setType("REGULAR");
	payDef.setFrequency("MONTH");
	payDef.setFrequencyInterval("1");					
	payDef.setCycles("12");
					
	com.paypal.api.payments.Currency curr = new Currency();
	curr.setCurrency("USD");
	curr.setValue("20");					
	payDef.setAmount(curr);
					
	//charge_models
	com.paypal.api.payments.ChargeModels cModel = new com.paypal.api.payments.ChargeModels();
	cModel.setType("SHIPPING");
	cModel.setAmount(curr);					
	List<ChargeModels> lcharModels = new ArrayList<ChargeModels>();					
	lcharModels.add(cModel);
	payDef.setChargeModels(lcharModels);															
										
	List<PaymentDefinition> lPayDef = new ArrayList<PaymentDefinition>();					
	lPayDef.add(payDef);					
	p.setPaymentDefinitions(lPayDef);					
					
					//merchant_preferences
	com.paypal.api.payments.MerchantPreferences pMerPer = new MerchantPreferences();					
	pMerPer.setSetupFee(curr);					
	pMerPer.setCancelUrl(ServerURL + "?action=paymentresponse&status=success");
	pMerPer.setReturnUrl(ServerURL + "?action=paymentresponse&status=cancel");
	pMerPer.setMaxFailAttempts("0");
	pMerPer.setAutoBillAmount("YES");
	pMerPer.setInitialFailAmountAction("CONTINUE");
					
	p.setMerchantPreferences(pMerPer);													
					
	APIContext context = new APIContext(accessToken);
	com.paypal.api.payments.Plan setupPlan = null;
					
	String error = "";
					
	try {
		setupPlan = p.create(context);				
	} catch (Exception e) {		
		error = e.toString();						
		log.info("setupPlan error - " + error);						
		resp.getWriter().print(e.toString());
		e.printStackTrace();
	}

**Comment by sankarbhavanib** [comment]
@fernando-lopez  Can you try below code 

```
		String SANDBOX_CLIENT_ID = "AYSq3RDGsmBLJE-otTkBtM-jBRd1TCQwFf9RGfwddNXWz0uFU9ztymylOhRS";
		String SANDBOX_CLIENT_SECRET = "EGnHDxD_qRPdaLdZz8iCr8N7_MzF-YHPTkjs6NKYQvQSBngp4PTTVWkPZRbL";
		APIContext SANDBOX_CONTEXT = new APIContext(SANDBOX_CLIENT_ID, SANDBOX_CLIENT_SECRET, "sandbox");

		com.paypal.api.payments.Plan p = new Plan();
		p.setName("T-Shirt of the Month Club Plan");
		p.setDescription("Template creation.");
		p.setType("fixed");

		//payment_definitions
		com.paypal.api.payments.PaymentDefinition payDef = new PaymentDefinition();
		payDef.setName("Regular Payments");
		payDef.setType("REGULAR");
		payDef.setFrequency("MONTH");
		payDef.setFrequencyInterval("1");
		payDef.setCycles("12");

		com.paypal.api.payments.Currency curr = new Currency();
		curr.setCurrency("USD");
		curr.setValue("20");
		payDef.setAmount(curr);

		//charge_models
		com.paypal.api.payments.ChargeModels cModel = new com.paypal.api.payments.ChargeModels();
		cModel.setType("SHIPPING");
		cModel.setAmount(curr);
		List<ChargeModels> lcharModels = new ArrayList<ChargeModels>();
		lcharModels.add(cModel);
		payDef.setChargeModels(lcharModels);

		List<PaymentDefinition> lPayDef = new ArrayList<PaymentDefinition>();
		lPayDef.add(payDef);
		p.setPaymentDefinitions(lPayDef);

		//merchant_preferences
		com.paypal.api.payments.MerchantPreferences pMerPer = new MerchantPreferences();
		pMerPer.setSetupFee(curr);
		pMerPer.setCancelUrl("http://www.cancel.com");
		pMerPer.setReturnUrl("http://www.return.com");
		pMerPer.setMaxFailAttempts("0");
		pMerPer.setAutoBillAmount("YES");
		pMerPer.setInitialFailAmountAction("CONTINUE");

		p.setMerchantPreferences(pMerPer);

		com.paypal.api.payments.Plan setupPlan = null;

		String error = "";

		try {
			setupPlan = p.create(SANDBOX_CONTEXT);
		} catch (Exception e) {
			error = e.toString();
			e.printStackTrace();
		}
```

**Comment by fernando-lopez** [comment]
APIContext doens't allow to me 3 parameters

![image](https://cloud.githubusercontent.com/assets/7783253/17588128/1350f1ae-5fcd-11e6-9d38-a5bae00402e5.png)

These are the libraries I'm using it

![image](https://cloud.githubusercontent.com/assets/7783253/17588141/28f5392a-5fcd-11e6-8b9e-2645be89e5cc.png)

**Comment by fernando-lopez** [comment]
I have updated the library to version 1.9.2 and I have now a much more clear error message:

![image](https://cloud.githubusercontent.com/assets/7783253/17588380/b8a215f6-5fce-11e6-85fa-4575750bb8d5.png)

I can continue working. You can close this thread.

Thank you!

**Comment by sankarbhavanib** [comment]
@fernando-lopez  glad to hear that you are able to make it work
