### ISSUE TITLE
payment page can jump, but the payment failed

### ISSUE THREAD

**Issue by bianlizuozishu** [paypal/PayPal-Java-SDK#238]
### General Information

- Mode (Live):
- PayPal-Debug-ID(s) (from any logs):
- Version of Java used:
- SDK Version:
new
### Issue Description
中文:
我使用demo中的代码来集成我的网站,但是我可以输入的api只有clientId  clientSecret
![image](https://cloud.githubusercontent.com/assets/12652543/17992726/7b14fa82-6b7c-11e6-864f-3036655ae82c.png)
![image](https://cloud.githubusercontent.com/assets/12652543/17992737/93005560-6b7c-11e6-9697-62265a06d6da.png)
只有这两个从开发者网站上查到的apiid 但是我在我paypal后台申请的api访问却不知道在什么地方填写.
所以想问一下我申请的api凭证在哪里填写

英文
I use in the demo code to integrate my website, but I can enter your API only clientId clientSecret

Only the two from the developer's website to apiid but I in my paypal backend application API access but don't know where to fill out.
So I want to ask me where is the application of API credentials to fill in

**Comment by pp-randy** [comment]
If your account is eligible you can create a REST API App here, which is where the Client Id and Secret come from.  If you want a production account you will want to log into the developer site with that account to create the REST API App https://developer.paypal.com/developer/applications/create/.

If you would prefer you can also request help from PayPal Technical Support which provides support in Chinese here: https://cn.paypal-techsupport.com/  to file a ticket the link is https://cn.paypal-techsupport.com/app/ask/
