### ISSUE TITLE
Error when trying to get a plan

### ISSUE THREAD

**Issue by alerad** [paypal/PayPal-Java-SDK#240]
### General Information

- Mode (Sandbox/Live): Live
- PayPal-Debug-ID(s) (from any logs): f311f5f7b4176 and 2a6bee807e80a
- Version of Java used: 1.7.0_79
- SDK Version: 1.9.1

### Issue Description

Hey, i'm getting an error on this line:
`APIContext context = getApiContext();
		plan = plan.create(context);

		PatchRequest patchRequest = new PatchRequest();
		patchRequest.setOp("replace");
		patchRequest.setPath("/");
		List<Patch> patch = Lists.newArrayList();
		patch.add(new Patch().setPath("/")
				.setValue(new Value())
				.setOp("replace"));

		plan.update(context,patch);
		plan = Plan.get(context, plan.getId());`

The following error is produced on the last line (Plan.get)

Response code: 500  	Error response: {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"f311f5f7b4176"}

**Comment by alerad** [comment]
The issue was fixed overnight, working again without any changes in code.

**Comment by pp-randy** [comment]
Thank you for following up @alerad.  I apologize for the delay and glad this is now resolved.
