### ISSUE TITLE
SandBox PayPal is Returning Production Approval URL's

### ISSUE THREAD

**Issue by CrackerStealth** [paypal/PayPal-Java-SDK#246]
### General Information

- Mode (Sandbox/Live): SandBox
- PayPal-Debug-ID(s) (from any logs): none
- Version of Java used: 1.8.0 U91
- SDK Version: Latest

### Issue Description

I am testing an application in SandBox mode. The PayPal service appears to be responding with correct sandbox URL's for the "self" and "execute" links, but the "approval" links are returning production links.

Example, creating a payment gives me:

Self URL: https://api.sandbox.paypal.com/v1/payments/payment/_ID_
Approval URL: https://www.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=_ID_
Execute URL: https://api.sandbox.paypal.com/v1/payments/payment/_ID_/execute

Where the Approval URL I should be receiving from the PayPal service is: https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=_ID_

**Comment by bluk** [comment]
Thank you for reporting this sandbox issue. We have an internal ticket PPPLMER-20280 to track this, and teams are working on a solution. We will report back when this issue is fixed.

**Comment by pp-randy** [comment]
The issue is resolved at this point in time.  Thank you for your patience and I apologize for any inconvenience.
