### ISSUE TITLE
Current dependencies will introduce libraries that may break log4j

### ISSUE THREAD

**Issue by charl8182** [paypal/PayPal-Java-SDK#250]
### General Information

- SDK Version: 1.9.3

### Issue Description

The current version of the SDK has the library log4j-slf4j-impl-2.1.jar as a dependency. This will stop logging in some environments.

In order to fix this I had to explicitly exclude the dependency in my pom.xml.

I think this kind of third party libraries shouldn't be declared in the SDK's pom file with the scope 'compile'

**Comment by bluk** [comment]
@charl8182 I 100% agree with your suggestion. The problem now is that if we change the scope, we may break other integrations's expectations that we have the jar as a dependency. I've added this to the SDK team backlog.

**Comment by jaypatel512** [comment]
Released in 1.11.0. Please update.
