### ISSUE TITLE
Payment verification message is INVALID

### ISSUE THREAD

**Issue by piotrazz87** [paypal/PayPal-Java-SDK#254]
From yesterday I have problem with verification of pay pal payment on SANDBOX. Everything was working well till yesterday.  Below request of payment:

> https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_xclick&business=**************&no_shipping=1&currency_code=EUR&item_name=**************&amount=11.57&rm=2&return=**************&custom=**************&cancel_return=*************

and payload to paypall :

> cmd=_notify-validate&orderState=null&custom=*****&txn_id=***&mc_currency=EUR&mc_fee=*** &mc_gross=***&protection_eligibility=ELIGIBLE&payment_date=***&payment_fee=8**&payment_gross=***&payment_status=Completed&payment_type=INSTANT_TRANSFER&business=***&receiver_id=****&payer_email=****&payer_id=***&payer_status=VERIFIED&first_name=Test&last_name=Buyer&item_name=****&quantity=1&charset=UTF-8

Below is a fragment of code for transaction verification:
```
 final HttpConnection connection = ConnectionManager.getInstance().getConnection();
        try {
            connection.createAndconfigureHttpConnection(httpConfiguration);
            headerMap.put("Host", new URL("https://www.sandbox.paypal.com/cgi-bin/webscr").getHost());
             final String  paymentResponseResult = connection.execute(null, payload.toString(), headerMap);    // payload is above
        } catch (Exception e) {
            LoggingManager.debug(CustomIPNMessage.class, e.getMessage());
        }
```

versions:
compile group: 'com.paypal.sdk', name: 'merchantsdk', version:"2.5.106"

can you help me?

**Comment by jaypatel512** [comment]
This does not look like a PayPal Java REST SDK. Please open this in correct repository: https://github.com/paypal/merchant-sdk-java
