### ISSUE TITLE
Header request got override by sdk

### ISSUE THREAD

**Issue by tenaz3** [paypal/PayPal-Java-SDK#255]
### General Information

- Mode (Sandbox):
- PayPal-Debug-ID(s) (from any logs):
- Version of Java used:
- SDK Version: 1.9.2

### Issue Description

> 
Why on this file you are always forcing "application/json" header? https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/rest/OAuthTokenCredential.java#L406

When you try to go onboarding:
The problem is when you try to use  _PayPalResource.configureAndExecute_ 
and you have payload = "grant_type=client_credentials"; and this require header: "application/x-www-form-urlencoded"; then I always get 415 from server. This is correct behavior?

**Comment by tenaz3** [comment]
Yes, I'm trying to go onboarding with this call.
`curl -X POST -H "Accept: application/json" -H "Cache-Control: no-cache" -H "Content-Type: application/x-www-form-urlencoded" -d 'grant_type=client_credentials' "https://api.sandbox.paypal.com/v1/oauth2/token"`
But using sdk to execute this call:
`PayPalResource.configureAndExecute(request.getApiContext(), request.getHttpMethod(), request.getTargetResource(), request.getRequestBody(), clazz);`

**Comment by jaypatel512** [comment]
You do not have to place that call to get the access token. PayPalResource.configureAndExecute call is specifically used for internally calls only, and are only really used externally for complex integrations. For normal integrations, you can follow the steps provided here at : https://github.com/paypal/PayPal-Java-SDK/wiki/Making-First-Call

Thanks,
Jay
