### ISSUE TITLE
Digital goods or service recurring payment / subscriptions

### ISSUE THREAD

**Issue by voneddy** [paypal/PayPal-Java-SDK#259]
### General Information

- Mode (Sandbox/Live): Both
- Version of Java used: 1.8
- SDK Version: 1.5 Java REST API SDK

### Issue Description

Hey, been banging my head against this one for a while now!
Is there a way to set up recurring payments / subscriptions as digital goods (or as a service) using this SDK?

Our products are all digital goods, i.e. access to our site but cant see any way of setting this on the Agreement / Plan / Payment Definition / Merchant Preferences etc?

If this is not possible with this SDK what should I be using? I've been looking at the Merchant SDK but a line on your docs say:

"Express Checkout Digital Goods is no longer available for new integrations. This feature remains available for merchant accounts that already have Express Checkout Digital Goods enabled".

Does this mean that the Merchant SDK and Express Checkout both also no longer work as digital goods?

Fingers crossed for a simple fix!

### Some Extra Details (not essential):

I understand if i can set our Agreements as digital good / services I'll get a better rate with PayPal and the major issue is that if a user wants to dispute a sale for example they have the option to say they never received the goods, but as its digital goods we obviously have no postal receipt to back up our side of the claim. 
When we invoice directly via PayPal (not via the SDK) we can set the type as a service and this removes the option to have to back up the dispute with a postal receipt....

**Comment by pp-randy** [comment]
I don't want to say it would be impossible to do this with this SDK, but I was not able to locate documentation and will need to look further.  It appears to be well documented for the Merchant SDK and Express Checkout. 

I also found this page in the business section that might be helpful it does show a micropayment section which indicates the lower rates: 
https://www.paypal.com/us/webapps/mpp/digital-products
https://www.paypal.com/us/webapps/mpp/merchant-fees

**Comment by voneddy** [comment]
Hi thanks for looking into this for me, any news?

Also just to be clear does this mean the "lower rates" are only available for "micropayments"? I thought all Digital Products were applicable...

I did find some good docs on recurring payemnens using the Merchant SDK as digital products [here](https://github.com/paypal/merchant-sdk-java/blob/master/merchantsample/src/main/java/com/sample/usecase/RecurringPaymentServlet.java) is anyones looking

**Comment by pp-randy** [comment]
@voneddy you should call the number on this page https://www.paypal.com/us/webapps/mpp/digital-products as they would be able to assist you with rate questions.   

This SDK has not been integrated with the digital goods flows. But I did see this under the Payment Experience
https://developer.paypal.com/docs/api/payment-experience/
https://developer.paypal.com/docs/api/payment-experience/#definition-input_fields
![image](https://cloud.githubusercontent.com/assets/6819909/20929837/03af1e68-bb91-11e6-8e34-5dfa8f803bbf.png)

**Comment by pp-randy** [comment]
But Payment Experience is not yet integrated for Billing Agreements, so Merchant SDK might be the best fit at this time.
