### ISSUE TITLE
Google App Engine - Update Billing Plan - Invalid HTTP method: PATCH

### ISSUE THREAD

**Issue by washowasho** [paypal/PayPal-Java-SDK#262]
### General Information

- Mode (Sandbox/Live): Sandbox
- PayPal-Debug-ID(s) (from any logs): None, can't get that far
- Version of Java used: jdk 1.7.0_79 & Google App Engine
- SDK Version: 1.13.0

### Issue Description

This works fine:
```
APIContext context = new APIContext(clientID, clientSecret, "sandbox");
context.usingGoogleAppEngine(true);
Plan plan = create(context);
```
However, when I call my update function:
```
plan = update(context, plan);
```
Which is:

```
public Plan update(APIContext context, Plan plan) throws PayPalRESTException, IOException 
{
	List<Patch> patchRequestList = new ArrayList<Patch>();
	Map<String, String> value = new HashMap<String, String>();
	value.put("state", "ACTIVE");
	
	Patch patch = new Patch();
	
	patch.setPath("/");
	patch.setValue(value);
	patch.setOp("replace");
	patchRequestList.add(patch);

	try{
		plan.update(context, patchRequestList);
	}
	catch (PayPalRESTException e) {
		log.warning("PayPalRESTException!: " + e.getMessage());
	}
	System.out.println("updated. now returning.");
	
	return plan;
}
```

I get the following PayPalRESTException from Google App Engine logs: 

Invalid HTTP method: PATCH

**Comment by washowasho** [comment]
Any update on this?

**Comment by pp-randy** [comment]
@washowasho I am following up further on this to see what the options are with this SDK. 

Testing outside of this SDK, I was able to POST and use `X-HTTP-Method-Override` header as `PATCH` as a workaround.

**Comment by jaypatel512** [comment]
Hey @washowasho !

We are working on adding a fix to this bug, and currently making progress in https://github.com/paypal/PayPal-Java-SDK/commits/gae-x-http-override. 

We will soon create a PR, once we have additional tests in place, and merge them after review. 👍

**Comment by washowasho** [comment]
Awesome. Thank you.

**Comment by jaypatel512** [comment]
Hey @washowasho !

The new release [v1.13.1](https://github.com/paypal/PayPal-Java-SDK/releases/tag/v1.13.1), includes the PR that fixes this issue. Thank you for your help.
