### ISSUE TITLE
Idea run sample error (JDK1.8)

### ISSUE THREAD

**Issue by spiritelf** [paypal/PayPal-Java-SDK#265]
Error:(4, 14) java: 程序包lombok不存在

**Comment by spiritelf** [comment]
![image](https://cloud.githubusercontent.com/assets/8556186/21494358/df66cdb4-cc4b-11e6-94cb-eee673865ea5.png)

**Comment by jaypatel512** [comment]
You may have to install lombok plugin if you want to load that in IDE to load properly. 

In terminal, `./gradlew clean build` should work as expected. Please re-open if still having the issue.

**Comment by spiritelf** [comment]
window8   ./gradlew clean build  work？

i use this  
![image](https://cloud.githubusercontent.com/assets/8556186/21514690/f63abb42-cd02-11e6-870a-6526254784c6.png)

**Comment by spiritelf** [comment]
> Loading > settings > Compiling C:\Users\huang\Desktop\奖金制度\在线支付\PayPal-Java-
> Loading > settings > Compiling C:\Users\huang\Desktop\奖金制度\在线支付\PayPal-Java-
> Configuring > 0/3 projects > root project > Compiling C:\Users\huang\Desktop\奖金制    
> Configuring > 0/3 projects > root project > Compiling C:\Users\huang\Desktop\奖金制    
> Configuring > 0/3 projects > root project > Compiling C:\Users\huang\Desktop\奖金制    
:clean                                     
:rest-api-sample:clean                
:rest-api-sdk:clean                
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar                 
:assemble     
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build
:rest-api-sdk:compileJava                                                            
警告: [options] 未与 -source 1.6 一起设置引导类路径                                   
C:\Users\huang\Desktop\奖金制度\在线支付\PayPal-Java-SDK-master\PayPal-Java-SDK-master
\rest-api-sdk\src\main\java\com\paypal\base\ReflectionUtil.java:65: 警告: 最后一个参数
使用了不准确的变量类型的 varargs 方法的非 varargs 调用;                               
                                                                returnObject = m.invok
e(responseType, null);

                ^
  对于 varargs 调用, 应使用 Object                                                    
  对于非 varargs 调用, 应使用 Object[], 这样也可以抑制此警告                          
C:\Users\huang\Desktop\奖金制度\在线支付\PayPal-Java-SDK-master\PayPal-Java-SDK-master
\rest-api-sdk\src\main\java\com\paypal\base\ReflectionUtil.java:97: 警告: 最后一个参数
使用了不准确的变量类型的 varargs 方法的非 varargs 调用;                               
                                                                returnObject = m.invok
e(responseType, null);

                ^
  对于 varargs 调用, 应使用 Object                                                    
  对于非 varargs 调用, 应使用 Object[], 这样也可以抑制此警告                          
C:\Users\huang\Desktop\奖金制度\在线支付\PayPal-Java-SDK-master\PayPal-Java-SDK-master
\rest-api-sdk\src\main\java\com\paypal\base\ReflectionUtil.java:106: 警告: 最后一个参 
数使用了不准确的变量类型的 varargs 方法的非 varargs 调用;                             

                                                  null)

                                                  ^
  对于 varargs 调用, 应使用 Class<?>                                                  
  对于非 varargs 调用, 应使用 Class<?>[], 这样也可以抑制此警告                        
C:\Users\huang\Desktop\奖金制度\在线支付\PayPal-Java-SDK-master\PayPal-Java-SDK-master
\rest-api-sdk\src\main\java\com\paypal\base\ReflectionUtil.java:108: 警告: 最后一个参 
数使用了不准确的变量类型的 varargs 方法的非 varargs 调用;                             

                                                  null));

                                                  ^
  对于 varargs 调用, 应使用 Object                                                    
  对于非 varargs 调用, 应使用 Object[], 这样也可以抑制此警告                          
C:\Users\huang\Desktop\奖金制度\在线支付\PayPal-Java-SDK-master\PayPal-Java-SDK-master
\rest-api-sdk\src\main\java\com\paypal\base\ReflectionUtil.java:121: 警告: 最后一个参 
数使用了不准确的变量类型的 varargs 方法的非 varargs 调用;                             
                                                                        m.invoke(klazz
.newInstance(), null));

                ^
  对于 varargs 调用, 应使用 Object                                                    
  对于非 varargs 调用, 应使用 Object[], 这样也可以抑制此警告                          
注: 某些输入文件使用或覆盖了已过时的 API。                                            
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                                
5 个警告                                                                              
:rest-api-sdk:processResources            
:rest-api-sdk:classes
:rest-api-sdk:jar                 
:rest-api-sample:compileJava                                                         
警告: [options] 未与 -source 1.6 一起设置引导类路径                                   
C:\Users\huang\Desktop\奖金制度\在线支付\PayPal-Java-SDK-master\PayPal-Java-SDK-master
\rest-api-sample\src\main\java\com\paypal\api\payments\servlet\AuthorizationCaptureSer
vlet.java:84: 错误: 编码GBK的不可映射字符                                             
                        // instrument. Default is 锟絝alse锟?.                        
                                                         ^
C:\Users\huang\Desktop\奖金制度\在线支付\PayPal-Java-SDK-master\PayPal-Java-SDK-master
\rest-api-sample\src\main\java\com\paypal\api\payments\servlet\GetCaptureServlet.java:
108: 错误: 编码GBK的不可映射字符                                                      
                // instrument. Default is 锟絝alse锟?.                                
                                                 ^
C:\Users\huang\Desktop\奖金制度\在线支付\PayPal-Java-SDK-master\PayPal-Java-SDK-master
\rest-api-sample\src\main\java\com\paypal\api\payments\servlet\RefundCaptureServlet.ja
va:104: 错误: 编码GBK的不可映射字符                                                   
                // instrument. Default is 锟絝alse锟?.                                
                                                 ^
注: 某些输入文件使用或覆盖了已过时的 API。                                                              
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                                
:rest-api-sample:processResources                 
:rest-api-sample:classes
:rest-api-sample:war                 
:rest-api-sample:assemble
:rest-api-sample:compileTestJava UP-TO-DATE
:rest-api-sample:processTestResources UP-TO-DATE
:rest-api-sample:testClasses UP-TO-DATE
:rest-api-sample:test UP-TO-DATE
:rest-api-sample:check UP-TO-DATE
:rest-api-sample:build
:rest-api-sdk:delombok FAILED

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\huang\Desktop\奖金制度\在线支付\PayPal-Java-SDK-master\PayPal-Java-SD
K-master\rest-api-sdk\lombok.gradle' line: 36

* What went wrong:
Execution failed for task ':rest-api-sdk:delombok'.
> Illegal null value provided in this collection: [null, delombok]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option
 to get more log output.

BUILD FAILED

Total time: 41.791 secs
