### ISSUE TITLE
Error code : 401 with response : Server returned HTTP response code: 401 for URL: https://api.paypal.com/v1/payments/payment

### ISSUE THREAD

**Issue by l7777777b** [paypal/PayPal-Java-SDK#266]
### General Information

- Mode (Sandbox/Live): Live
- PayPal-Debug-ID(s) (from any logs): none
- Version of Java used: 1.8
- SDK Version: 1.4.2

### Issue Description

I have my cart implementation on my web hosted on AWS, using this sdk to integrate paypal.
Last night paypal payment working fine but today it cant event continue to the paypal page.
But when i tried to run the web locally on my pc, the payment working fine using both live and sandbox configuration.
My current solution was create new app on my paypal developer page and used the new client and secret on my web then the paypal payment back to work. but anyone knows why? (it's working right now though)
The stack trace below.
```
response-code: 401	details: null
	at com.paypal.base.rest.PayPalRESTException.createFromHttpErrorException(PayPalRESTException.java:72)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:439)
	at com.paypal.base.rest.PayPalResource.configureAndExecute(PayPalResource.java:267)
	at com.paypal.api.payments.Payment.create(Payment.java:484)

Caused by: com.paypal.base.exception.HttpErrorException: Error code : 401 with response : Server returned HTTP response code: 401 for URL: https://api.paypal.com/v1/payments/payment
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:174)
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:67)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:425)
	... 49 more
Caused by: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.paypal.com/v1/payments/payment
```

**Comment by jaypatel512** [comment]
If it is failing in live with 401, the most common cause is if you use the access token yourself, and try to pass that in for request. 

Please make sure you are using `apiContext` as shown in the example: https://github.com/paypal/PayPal-Java-SDK/wiki/Making-First-Call

**Comment by l7777777b** [comment]
Hello,
I'm not using this code
`APIContext context = new APIContext(clientId, clientSecret, "sandbox");`
do i need to use it instead of this one? because i'm using this one.
```
String accessToken = getAccessToken();
String requestId = UUID.randomUUID().toString();
APIContext apiContext = new APIContext(accessToken, requestId);
apiContext.setConfigurationMap(configurationMap);
return payment.create(apiContext);
```
not only on payment.create but every time before api call.

its working in live but locally (my pc). the problem occured when i uploaded the web on AWS.
but it's not happening anymore since i created new app on the developer page and used the new clientid & clientsecret. that made it more confusing for me.

**Comment by jaypatel512** [comment]
Weird. 

Let us know if that happens again, before deleting the app in developer page. We might be able to figure out if it happens again. 

Closing this issue for now.

**Comment by l7777777b** [comment]
i didnt delete the app, i only create a new one. what information do you need? i might be able to give it to you.

**Comment by l7777777b** [comment]
@jaypatel512 currently it's happening again with the newly created app. it's working for 2 days and the same error happened. and then when i change back to the previously created app's clientid and secret, it worked. makes me think that i might just need to restart the tomcat to fix it. but do you have any idea what could be the problem here?
now i'll try to use the exact code from here.
[https://github.com/paypal/PayPal-Java-SDK/wiki/Making-First-Call](https://github.com/paypal/PayPal-Java-SDK/wiki/Making-First-Call)
and update the library version to 1.13.0.

**Comment by jaypatel512** [comment]
Generally, the access token that you fetch from PayPal has a life of 8 hours. The value of which is handled properly if you APIContext the way we have shown in Wiki documentation. In your case, you might be fetching the access token once, and using it forever. This would work for you around 8 hours just fine, but would start failing after that. 

I would highly recommend using wiki instructions to integrate.
