### ISSUE TITLE
how to run sample？

### ISSUE THREAD

**Issue by spiritelf** [paypal/PayPal-Java-SDK#267]

**Comment by jaypatel512** [comment]
Please follow the instructions at: https://github.com/paypal/PayPal-Java-SDK/tree/master/rest-api-sample#build-and-run-the-samples

**Comment by spiritelf** [comment]
how to do  Simply run ./gradlew clean jettyRun to start jetty server.？

i user  idea  
![image](https://cloud.githubusercontent.com/assets/8556186/21514709/1ecce4cc-cd03-11e6-954c-db050b647931.png)

**Comment by spiritelf** [comment]
how to  Access http://localhost:<jetty-port>/rest-api-sample/ in your browser to view samples.
