### ISSUE TITLE
UNKNOWN_ERROR - CreditCardPayment

### ISSUE THREAD

**Issue by ovasgus** [paypal/PayPal-Java-SDK#269]
I was testing PaymentWithCreditCard and it was working very well, but suddenly it stopped working.

The PayPal API response was:
> Response code: 400	Error response: {"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"37307e157a392"}

Searching I found this issue https://github.com/paypal/PayPal-Ruby-SDK/issues/134 and tried with a different sandbox account, and the error still happening.

Here are some debug_id:
 - 37307e157a392
 - 20c623da57ca4
 - c2b5c64c6b661
 - ee939f735d7

**Comment by bluk** [comment]
@ovasgus Just to be clear, did you create a completely new sandbox account which you can [create here](https://developer.paypal.com/developer/accounts/) and use the credit card associated with that account? The debug IDs seem to indicate that the buyer accounts have an issue (possibly overused) which can happen with test accounts (especially those in the samples and shared in these issues).

**Comment by ovasgus** [comment]
@bluk I used a com

**Comment by ovasgus** [comment]
@bluk I used a completely new account, and new sand-box and I used an example creditcard number like 411111111111111111111.

Should I used the credit card number of the accounts I have created?
And, how can I use the account again without the overuse

**Comment by bluk** [comment]
Can you please try the credit card number in the sandbox account you created? Example credit card numbers like `4111111111111111` do not work in sandbox since they are "overused".

If you keep the credit card number private, it is usually difficult to overuse the credit card.

**Comment by ovasgus** [comment]
Should I use the creditcard number for the facilator account or should create a new account, like client, and use that creditcard number?

**Comment by bluk** [comment]
You should use a new `buyer` account and the credit card number generated from that account. Also, please ensure that your account has [Direct credit cards enabled](https://developer.paypal.com/developer/accountStatus/).

**Comment by ovasgus** [comment]
@bluk I tried with the creditcard number of a buyer account created in the sandbox and it worked without errors.

thank you for your help
