### ISSUE TITLE
How to show agreement price?

### ISSUE THREAD

**Issue by jpereira06** [paypal/PayPal-Java-SDK#271]
### General Information

- Mode (Sandbox/Live): Sandox
- PayPal-Debug-ID(s) (from any logs):
- Version of Java used: Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
- SDK Version: 1.13.0

### Issue Description

I'm dealing with regular payments but I need to include the item list and price in the agreement, is it possible? Sorry but I'm unable to find out the way of showing this info.  Please find attached screenshoot with my current status:

![captura de pantalla 2017-01-24 a las 17 57 04](https://cloud.githubusercontent.com/assets/13746642/22258694/e325e28c-e262-11e6-94fd-d82eecaab281.png)

Here is my code:
`
	private Plan createBillingPlan(APIContext apiContext, SERVICE_TYPE serviceType, double vat, String origin, String customerId, String shopId) throws PayPalRESTException {
		Plan plan = new Plan();
		plan.setName("Vikinguard Premium");
		plan.setDescription("Vikinguard monthly subscription");
		plan.setType("infinite");

		//payment_definitions
		PaymentDefinition paymentDefinition = new PaymentDefinition();
		paymentDefinition.setName("Regular Payments");
		paymentDefinition.setType("REGULAR");
		paymentDefinition.setFrequency("MONTH");
		paymentDefinition.setFrequencyInterval("1");
		paymentDefinition.setCycles("0");

		//currency
		double iva = serviceType.getPrice() * vat;
		double totalPrice = serviceType.getPrice() + iva;
		
		Currency currency = new Currency();
		currency.setCurrency("EUR"); 
		currency.setValue(Double.toString(totalPrice));
		paymentDefinition.setAmount(currency);

		//charge_models
		if (vat > 0){
			ChargeModels chargeModels = new com.paypal.api.payments.ChargeModels();
			chargeModels.setType("TAX");
			Currency ivaCurrency = new Currency("EUR", Double.toString(iva));
			chargeModels.setAmount(ivaCurrency);
			List<ChargeModels> chargeModelsList = new ArrayList<ChargeModels>();
			chargeModelsList.add(chargeModels);
			paymentDefinition.setChargeModels(chargeModelsList);
		}

		//payment_definition
		List<PaymentDefinition> paymentDefinitionList = new ArrayList<PaymentDefinition>();
		paymentDefinitionList.add(paymentDefinition);
		plan.setPaymentDefinitions(paymentDefinitionList);

		
		//merchant_preferences
		MerchantPreferences merchantPreferences = new MerchantPreferences();
		merchantPreferences.setSetupFee(currency);
		merchantPreferences.setCancelUrl(cancelUrl); ¡
		merchantPreferences.setReturnUrl(returnUrl);
		merchantPreferences.setMaxFailAttempts("3");
		merchantPreferences.setAutoBillAmount("YES");
		merchantPreferences.setInitialFailAmountAction("CANCEL");
		plan.setMerchantPreferences(merchantPreferences);

		Plan billingPlan = plan.create(apiContext);
		String id = billingPlan.getId();
		String state = billingPlan.getState();
		log.info("Paypal plan created! id:"+id+"; status:"+state);
		return billingPlan;
	}
	
	private void activatePlan(APIContext apiContext, Plan billingPlan) throws PayPalRESTException {
		List<Patch> patchRequestList = new ArrayList<Patch>();
		Map<String, String> value = new HashMap<String, String>();
		value.put("state", "ACTIVE");

		Patch patch = new Patch();
		patch.setPath("/");
		patch.setValue(value);
		patch.setOp("replace");
		patchRequestList.add(patch);

		billingPlan.update(apiContext, patchRequestList);
		log.info("Plan activated properly");
	}
	

	private String createAgreement(APIContext apiContext, Plan billingPlan) throws MalformedURLException, UnsupportedEncodingException, PayPalRESTException {
		Agreement agreement = new Agreement();
	
		Currency amount = billingPlan.getPaymentDefinitions().get(0).getAmount();
		agreement.setName("Premium Subscription");
		agreement.setDescription("Premium Subscription ");

		Plan plan = new Plan();
		plan.setId(billingPlan.getId());
		agreement.setPlan(plan);
		Payer payer = new Payer();
		payer.setPaymentMethod("paypal");
		agreement.setPayer(payer);
		Calendar calendar = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
		calendar.add(Calendar.MINUTE, 5); //date have to be future
		String date = simpleDateFormat.format(calendar.getTime()) ;
		agreement.setStartDate(date);
		
		Agreement create = agreement.create(apiContext);
		
		String approvalUrl = null;
		List<Links> links = create.getLinks();
		for (Links link : links){
			if ("approval_url".equals(link.getRel())){
				approvalUrl = link.getHref();
				break;
			}
		}
		
		log.info("Agreement created! url:"+approvalUrl);
		return approvalUrl;
	}`

This 3 methods are called consecutively like:
`			Plan billingPlan = createBillingPlan(apiContext, serviceType, vat, origin, customerId, shopId);
			
			activatePlan(apiContext,billingPlan);
			
			String approvalUrl = createAgreement(apiContext, billingPlan);`

**Comment by pp-randy** [comment]
I apologize for the delay and in regards to the feature because it is currently not supported and the issue is being tracked here https://github.com/paypal/PayPal-PHP-SDK/issues/149
