### ISSUE TITLE
MalFormedRequest exception whey specifying certain fields

### ISSUE THREAD

**Issue by snimavat** [paypal/PayPal-Java-SDK#274]
### General Information

- Mode (Sandbox):
- PayPal-Debug-ID(s) (c9a76d9e7e992):
- Version of Java used: 1.8
- SDK Version: latest

### Issue Description

While creating a new payment, if i set transaction.referenceId or transaction.purchaseUnitReferenceId 
I get below error

`ERROR base.HttpConnection  - Response code: 400	Error response: {"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"c9a76d9e7e992"}`

**Comment by pp-randy** [comment]
This is probably a documentation issue and those fields are read only.  I see that you opened up a new issue https://github.com/paypal/PayPal-Java-SDK/issues/275 in regards to invoice number and custom which is what I would advise you use.  I will look aver that issue next.  I apologize for the delay in response.
