### ISSUE TITLE
SSLUtil.downloadCertificateFromPath ignores proxy configuration

### ISSUE THREAD

**Issue by mortonl** [paypal/PayPal-Java-SDK#276]
### General Information

- Mode (Sandbox/Live): Any
- PayPal-Debug-ID(s) (from any logs):
- Version of Java used: 1.8.0_101
- SDK Version: 1.13.0

### Issue Description

> Please include as many details (logs, steps to reproduce, frameworks/dependencies) as you can to help us reproduce this issue faster.

SSLUtil.downloadCertificateFromPath ignores proxy configuration, configurations passed via the parameter configurations are mapped into a new HttpConfiguration this is then passed into DefaultHttpConnection.createAndconfigureHttpConnection which looks for proxyHost and ProxyPort but these will always be blank.

This means that anywhere the sdk is deployed where a proxy is required will be ignored, The code in createAndconfigureHttpConnection makes the jvm proxy settings be ignored as well.

**Comment by mortonl** [comment]
Can anyone have a look at this please, i have implemented a solution and created a pull request.

**Comment by jaypatel512** [comment]
Hey @mortonl !

Thanks for your PR. We really appreciate your help on this. Let me add this PR to our planning, and will ask few of our folks to review and approve the changes 👍

**Comment by jaypatel512** [comment]
The PR is merged ! Thanks again @mortonl for sending us your PR.
