### ISSUE TITLE
Please improve the README

### ISSUE THREAD

**Issue by pixelogik** [paypal/PayPal-Java-SDK#28]
The README is really weak and does not help to get started. 

It seems that clientID and clientSecret are stored in the properties file and can be loaded like this: 

    Payment.initConfig(new File("../sdk_config.properties"));

Right after this part in the README it says that you have to create the OAuth token like this:

    String accessToken = new OAuthTokenCredential(clientID,   clientSecret).getAccessToken();

Why do I have to specify clientID and clientSecret here again when I already loaded the config file? Why are these credentials in the config file then? 

Also why should somebody add jars locally? You should only add the ONE dependency to your maven dependency file (Build.scala for example) and that's it, that is the idea of maven usage after all. 

The version in the README is 0.8.0, there is however already a 0.9.0 tagged version.

**Comment by juwlee** [comment]
Please see the updated docs. Now Payment.initConfig() returns an OAuthTokenCredential with clientID/clientSecret loaded from the config file, so you do not need to provide them again.
