### ISSUE TITLE
Payee Null

### ISSUE THREAD

**Issue by rafaeluchoa** [paypal/PayPal-Java-SDK#280]
#### Library version: 
		<dependency>
		    <groupId>com.paypal.sdk</groupId>
		    <artifactId>rest-api-sdk</artifactId>
		    <version>1.13.1</version>
		</dependency>

#### Language, language version, and OS: 

Red Hat Enterprise Linux Server release 6.7 (Santiago)
Linux ex-std-node701.prod.rhcloud.com 2.6.32-642.13.1.el6.x86_64 #1 SMP Wed Nov 23 16:03:01 EST 2016 x86_64 x86_64 x86_64 GNU/Linux

jdk1.8.0_77

### Issue description

The json doesn't return the payee within transaction of the same payer with the same value. 

![error-paypal-03-03-2017](https://cloud.githubusercontent.com/assets/196591/23553002/64ae15ce-fffd-11e6-8876-9224df70b49d.PNG)

**Comment by xiaoleih41** [comment]
Thank you for your question, Do you have a Debug ID associated with the API call? Does this situation only happen in live or it happens in sandbox situation as well?

**Comment by rafaeluchoa** [comment]
Environment: Live (Production)

The request processed with success, then, it doesn't have Debug ID.

Just in Live. The sandbox returns correctly with payee data.

Today (14/03/2017), I talked with customer and he returned me about the problem and it doesn't happened again, i.e., he executed the payment with same values and same account. 

Thus, I'm closing the issue.

Thanks a lot.
