### ISSUE TITLE
OAuthTokenCredential leaks ACCESS_TOKENS map

### ISSUE THREAD

**Issue by KittyChan** [paypal/PayPal-Java-SDK#281]
ACCESS_TOKENS never gets cleared.

**Comment by xiaoleih41** [comment]
Thank you for your question.  Please help provide more detail and steps to replicate your issue. If you have a debug ID, it will help us as well. Thanks, Xiaolei

**Comment by jaypatel512** [comment]
Hey @KittyChan !

We do replace the accessToken value if it gets expired. We do not remove the entry, as there is no way for us to know if the entry is not used anymore. 

However, mostly, the integrations would only have a certain number of `clientIds`, which should be okay. Do you have an integration in mind, where this may not be true ?

**Comment by pp-randy** [comment]
Closing the issue as inactive.  If you are able to provide additional details we would appreciate it.
