### ISSUE TITLE
consistent naming of mode/env between javascript and java

### ISSUE THREAD

**Issue by snimavat** [paypal/PayPal-Java-SDK#282]
In JavaSDK the production environment is called **live**, wherever on paypal express checkout js, the production environment is called "**production**" shouldnt this be consistent on both places ?
This creates confusion.

Any thoughts ?

**Comment by jaypatel512** [comment]
Hey @snimavat !

I completely agree with you. We had a consistent naming convention across all our server SDKs. However, this would be a breaking change for us now. We are planning to do a major release, and we have taken that in consideration. 

Thanks for your input. Really appreciated it.
