### ISSUE TITLE
OAuth TokenCredential error at first call - Error response: {"error":"unsupported_grant_type","error_description":"Grant Type is NULL"}

### ISSUE THREAD

**Issue by AlexKbaum** [paypal/PayPal-Java-SDK#284]
### General information

* SDK/Library version: 1.13.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: null
* Language, language version, and OS: Java 1.8. , Windows 7

### Issue description

When calling the sdk for the first time it tries to initiate the OAuth flow but on the first call I get a Grant Type is NULL

16:57:54,683 DEBUG [com.paypal.base.rest.OAuthTokenCredential] (EJB default - 10) {53222497-97ad-4262-bab0-29a1f4b63e84.b5623750-ea54-4403-a472-40eb8903104f} request header: {Authorization=Basic OAuth Code xxxx, Accept=application/json, User-Agent=PayPalSDK/PayPal-Java-SDK 1.13.1 (v=1.8.0_40; vendor=Oracle Corporation; bit=64; os=Windows_7 6.1), Content-Type=application/x-www-form-urlencoded}
16:57:54,683 DEBUG [com.paypal.base.rest.OAuthTokenCredential] (EJB default - 10) {53222497-97ad-4262-bab0-29a1f4b63e84.b5623750-ea54-4403-a472-40eb8903104f} request body: grant_type=client_credentials
16:57:54,684 DEBUG [com.paypal.base.HttpConnection] (EJB default - 10) {53222497-97ad-4262-bab0-29a1f4b63e84.b5623750-ea54-4403-a472-40eb8903104f} curl command:
curl -v 'https://api.sandbox.paypal.com/v1/oauth2/token' \
-H "Authorization: Basic OAuth Code xxxx \
-H "Accept: application/json" \
-H "User-Agent: PayPalSDK/PayPal-Java-SDK 1.13.1 (v=1.8.0_40; vendor=Oracle Corporation; bit=64; os=Windows_7 6.1)" \
-H "Content-Type: application/x-www-form-urlencoded" \
-d 'grant_type=client_credentials'

Error Message:
Error response: {"error":"unsupported_grant_type","error_description":"Grant Type is NULL"}

Subsequent calls are successful since the access token will be cached.

**Comment by pp-randy** [comment]
@AlexKbaum can you clarify a bit.  You are seeing an issue in the SDK and reproduced in curl as well?  I ran your curl code and it worked for me.

**Comment by xiaoleih41** [comment]
Please let us know if you have any further questions. We are closing this as it doesn't seem to be a bug. Thanks, Xiaolei
