### ISSUE TITLE
Validation Error in Merchant email

### ISSUE THREAD

**Issue by hacksut3l** [paypal/PayPal-Java-SDK#289]
Good Day, What causes the validation error in the merchant email. My email is correct. It happened in sandbox and my debug id is c9a84d2635339. I am using the paypal rest api in creating an invoice.

**Comment by jaypatel512** [comment]
Can you please make sure you are using related clientId and secret associated with that email ?

**Comment by pp-randy** [comment]
As @jaypatel512 suggests the email address does not match the REST account being used.  Just replace `@gmail.com` with `-facilitator@gmail.com` in the email address you provided and you should be good to go.
