### ISSUE TITLE
500 Internal Service Error while creating Agreement with paypal user

### ISSUE THREAD

**Issue by SimoneMSR** [paypal/PayPal-Java-SDK#290]
My steps
1) create plan (having an id X and the following characteristics)
1.1) plan.type=infinite
1.2) plan.paymentDefinition.type=regular
1.3) plan.paymentDefinition[0].chargeModels[0]=TAX
1.4) plan.merchangPreferensec.setReturnUrl setted to an **accessible URL**
2) create the agreement with this code 

```
Agreement agreement = new Agreement();
agreement.setName...
agreement.setDescription...
agreement.setStartDate...
agreement.setDescription...

Plan plan = Plan.get(context, X);

// Add payer details
Payer payer = new Payer();
payer.setPaymentMethod("paypal");
agreement.setPayer(payer);

// Set shipping address information
ShippingAddress shipping = new ShippingAddress();
shipping.setLine1("111 First Street");
shipping.setCity("Saratoga");
shipping.setState("CA");
shipping.setPostalCode("95070");
shipping.setCountryCode("US");
agreement.setShippingAddress(shipping);

agreement.create(context); // this won't work
```
Please help me

**Comment by pp-randy** [comment]
Are you calling `agreement.setPlan(plan);` somewhere?

**Comment by SimoneMSR** [comment]
You are right!
But here's what's the problem now:
`Invalid Fields passed in plan. Pass only a valid plan-id.`

after having done this:

```
Plan plan = Plan.get(context, planId); //plan !=null && !plan.Id.empty()
agreement.setPlan(plan);
```

**Comment by SimoneMSR** [comment]
Yes. Now it works.

Thank you very much @pp-randy !

**Comment by pp-randy** [comment]
That is odd.  So you used Plan.get `Plan plan = Plan.get(context, planId);`  Did it retrieve your plan?  It should set the Id if it found it.   

Granted setting `plan.setId(planId);` like you did could be used to reduce an API request since the plan isn't being retrieved using Plan.get.

**Comment by SimoneMSR** [comment]
As I have written in the posted code, this returned false Plan.get(context, planId).getId.isEmpty(), i.e. I have the planId from the get
