### ISSUE TITLE
Override of service.Endpoint not possible because of mode enforcement

### ISSUE THREAD

**Issue by derarmin** [paypal/PayPal-Java-SDK#293]
### General information

* SDK/Library version: 1.13.1
* Environment: Sandbox/Local testing
* Language, language version, and OS: Java 1.8.0_102-b13 on OSX

### Issue description

I am trying to override the endpoint.Url for local testing(mockserver is acting as PayPal to localhost).
I am setting the configuration map property while creating the _APIContext(clientId, clientSecret, mode, configurationMap)_.

Well, the problem is, that the mode only can be _sandbox_ or _live_ and in the class _RESTAPIPreHandler_ the function _getBaseUrl_ will only use my custom url, if the mode is not _live_ or _sandbox_ .
https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/rest/RESTAPICallPreHandler.java#L202

This code
_String urlString = this.configurationMap.get(Constants.ENDPOINT);_ will always be reassigned because of the mode restrictions!
https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/rest/APIContext.java#L160

Either add another mode or check if the urlString property is not null(length) and give it a higher prio then defaulting to the mode constants.

Cheers

**Comment by derarmin** [comment]
The error was introduced here https://github.com/paypal/PayPal-Java-SDK/commit/feb69ccb00fecb6dcef9f12b5bffbd5a45d801e2#diff-75b38f1af85d5805edb77a5c861e9ca8R210

**Comment by trainerbill** [comment]
@derarmin Can you just override your hosts files for the paypal urls when testing locally?

**Comment by derarmin** [comment]
@trainerbill No - thats definitely not the way I will go. The library should be fixed instead.

**Comment by jaypatel512** [comment]
Hey @derarmin !

You are absolutely right. Thank you so much for your detailed issue. I will go ahead and create a PR, and get that merged in soon.

**Comment by rburton** [comment]
I was actually looking into this last night. Is there an ETA when this will be merged and released?

**Comment by derarmin** [comment]
@rburton dunno, recommended some changes, waiting for feedback

**Comment by rburton** [comment]
As a work around, you can extend APIContext and override APIContext#setMode(String)  then in the subclass, you could then do this.getConfigurationMap().put(Constants.MODE, mode); and this.getConfigurationMap().put(Constants.ENDPOINT, url);

HTH
