### ISSUE TITLE
Update jetty gradle plugin to gretty

### ISSUE THREAD

**Issue by radistao** [paypal/PayPal-Java-SDK#296]
### Issue description
Currently used default [gradle Jetty](https://docs.gradle.org/3.3/userguide/jetty_plugin.html) plugin should be changed because of the following reasons:
  
  - the plugin is reported as _deprecated_ and will be removed soon from the gradle distribution, see https://docs.gradle.org/3.3/userguide/jetty_plugin.html
  - debugging in this plugin is obfuscated.

Instead of this one gradle developers propose to use [Gretty plugin](https://github.com/akhikhl/gretty). And this one has default _debug_ tasks, see:
  - http://akhikhl.github.io/gretty-doc/Debugger-support.html
  - http://akhikhl.github.io/gretty-doc/Gretty-tasks

**Comment by xiaoleih41** [comment]
This doesn't appear to be a PayPal repository. Please contact the plugin owner directly on regarding the above issue.

**Comment by andrii-kovalenko-ct** [comment]
sorry, may be you understood me wrong: i propose to update Jetty plugin in the build script of this repository to make debugging for your consumers (Paypal SDK consumers)

**Comment by andrii-kovalenko-ct** [comment]
* that's [the trick you should do](https://stackoverflow.com/a/9648945/907576) if you want to debug Paypal SDK samples:
    
  ```bash
  ./gradlew jettyRun -Xdebug -Xrunjdwp:transport=dt_socket,address=9999,server=y,suspend=n
  ```

  or

  ```bash
  export GRADLE_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=9999,server=y,suspend=n"
  ./gradlew jettyRun
  ```

* that's how you run debug mode in the new proposed plugin (recommended by gradle developers):

  ```bash
  ./gradlew jettyRunDebug
  ```

**Comment by trainerbill** [comment]
@andrii-kovalenko-ct there is a PR for this change.  Would you recommend any additional changes?

https://github.com/paypal/PayPal-Java-SDK/pull/297

**Comment by andrii-kovalenko-ct** [comment]
this is my PR :)

i put there exactly everything i wanted

**Comment by andrii-kovalenko-ct** [comment]
aaaa, i found: i reported from one account, but submitted PR from another one. my bad - sorry (one is private, one is working)

**Comment by trainerbill** [comment]
Thanks for the PR!

**Comment by avinashpothula** [comment]
hi this is avinash. i make 0.6 transaction with PayPal sdk i getting this error.
Response code: 400
 Error response:
 {"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].amount","issue":"Transaction amount details (subtotal, tax, shipping)
 must add up to specified amount total"}],"message":"Invalid request -
 see details","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"45b889f983c9"}


 **my code response is**

{"transactions":[],"amount":{"currency":"USD","total":"0.9","details":{
      "shipping":"0","subtotal":"0.6","tax":"0.31"}},"description":
  "This is the payment transaction description.","item_list":{"items":[{
        "name":"Item for Purchase","quantity":"1","price":"0.6","currency":
        "USD"}]}}
  any one please help me

**Comment by jaypatel512** [comment]
The PR is merged, and should be released soon.

**Comment by radistao** [comment]
I see, thanks :)
