### ISSUE TITLE
Paypal REST API

### ISSUE THREAD

**Issue by mayank9294** [paypal/PayPal-Java-SDK#301]
Hello Team,
We are using PayPal rest API to maintain our payments of clients.
We have created Plan and Subscription using REST API.

Now we have requirement where We need to update billing Plan Price.
When we tried to update active PLAN, API is responding with "Updation of a template only allowed in CREATED state." and when we try to update Plan in billing subscription it is throwing this field can not be patched.
Is there any way to update billing agreement/billing plan price using REST API or any other way to do this?

**Comment by xiaoleih41** [comment]
Billing plan is not patchable. Please refer to https://github.com/paypal/PayPal-Ruby-SDK/issues/262 for more info.

**Comment by xiaoleih41** [comment]
close this issue as it's a duplicated issue.
