### ISSUE TITLE
Can't pay with an American Express Card

### ISSUE THREAD

**Issue by ovasgus** [paypal/PayPal-Java-SDK#302]
### General information
I am using the PayPal-Java-sdk to tokenize and make payments with credit cards.
The tokenization with cards like Visa, MasterCard and American Express work without any problems. 
I make the payment with the token sent by PayPal when I use the vault.

### Issue description
The problem is when I try to make a payment. In sandbox mode with Visa and MasterCard card, the transaction works, but with American Express card I got the next error:
**Response code: 400	Error response: {"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR","debug_id":"5fb998cacaf4"}**

Searching in the Dashboard API calls of PayPal the information the system gave me is not enough to know what I am doing wrong.

It is possible that PayPal don't process payments via American Express?

**Comment by xiaoleih41** [comment]
The REST API direct credit card processing will only be supported in Japan going forward. If you are not processing payment in Japan, please consider looking into [Braintree Vault](https://articles.braintreepayments.com/support/control-panel/vault/overview) instead.

**Comment by ovasgus** [comment]
But only with American Express card or any type of card?
I had processed payments with Visa and MasterCard tokens without any problem, the problem is when I try to process American Express cards.
All of my test is on sandbox mode in live mode the payments with Visa and MasterCard tokens will fail?

**Comment by xiaoleih41** [comment]
It is with the product regardless the card type. The product is deprecated and we don't encourage new integration anymore.

**Comment by xiaoleih41** [comment]
Close this issue as the question has been answered.
