### ISSUE TITLE
Sanbox Webhook Events not generating SALE.COMPLETED event

### ISSUE THREAD

**Issue by mayank9294** [paypal/PayPal-Java-SDK#303]
Hello Team,
I have webhook configured for my application and from the last week they are not generating SALE.COMPLETED event for initial set up amount for billing subscription.I can see billing plan and agreement events are getting generated correctly but it is not generating event for payment.
Lat amount transaction : 
		
Subscription Payment Received (Unique Transaction ID # 30V18230DM505443K)

Please help urgently.Facing this issue from last week else events are getting generated post payment within 1 minute.

**Comment by pp-randy** [comment]
@mayank9294 thank you for reporting the issue.  I apologize for the inconvenience.  

Please follow  https://github.com/paypal/PayPal-REST-API-issues/issues/103 for further updates on this issue.

**Comment by mayank9294** [comment]
Facing same issue.Can you please check from your end?Or event notification is not trust able?

**Comment by xiaoleih41** [comment]
@mayank9294 Please check https://github.com/paypal/PayPal-REST-API-issues/issues/103 for updates.
