### ISSUE TITLE
paypal payment 

### ISSUE THREAD

**Issue by avinashpothula** [paypal/PayPal-Java-SDK#306]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by avinashpothula** [comment]
acct1.CertPath=src/test/resources/sdk-cert.p12
acct1.CertKey=password
acct1.AppId= APP-80W284485P519543T
#acct1.UserName = certuser_biz_api1.paypal.com
acct1.UserName =exaact.test-facilitator_api1.gmail.com
acct1.Password=QVGRELNVTRJW8CR9
acct1.Signature =AFcWxV21C7fd0v3bYYYRCpSSRl31AESi3WLKIdTEilJ8dD07IPl.99yP
acct1.AppId= APP-80W284485P519543T

# Connection Information
http.ConnectionTimeOut=5000
http.Retry=2
http.ReadTimeOut=30000
http.MaxConnection=100
http.IPAddress=127.0.0.1


# HTTP Proxy configuration
# If you are using proxy set http.UseProxy to true and replace the following values with your proxy parameters
http.ProxyPort=8080
http.ProxyHost=127.0.0.1
http.UseProxy=false
http.ProxyUserName=null
http.ProxyPassword=null

#Set this property to true if you are using the PayPal SDK within a Google App Engine java app
http.GoogleAppEngine = false

# Service Configuration
service.EndPoint=https://svcs.sandbox.paypal.com/
openid.RedirectUri=https://www.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize

# For TLS 1.2 testing, change endpoint to one from the below
service.TestSvcsEndPoint=https://test-svcs.sandbox.paypal.com
service.TestApi3tEndPoint=https://test-api-3t.sandbox.paypal.com
service.TestIpnpbEndPoint=https://test-ipnpb.sandbox.paypal.com
service.TestApisEndPoint=https://test-apis.sandbox.paypal.com

# Credentials
clientId=ASHkLGkejXZp3x9LW4E1WCIT6ebCjKZHHOCok-XrlHjpGmkapgEEU7-KplUfCPLd0nUu8A_Cu3m4x9Pa
clientSecret=ECcLoLq-NSB0k9kVk5uNngdVC8zFTjV-_1DaJyl81C7jnzhwVI2gWFaLB8Zk-j3IKMlFBnxiSfSxkp9C

# SSLUtil
sslutil.jre=SunJSSE
sslutil.protocol=TLSv1.2

# ------------------------------SANDBOX------------------------------ #
service.RedirectURL=https://www.sandbox.paypal.com/webscr&cmd=
service.DevCentralURL=https://developer.paypal.com
# ------------------------------PRODUCTION------------------------------ #
#service.RedirectURL=https://www.paypal.com/webscr&cmd=
# ------------------------------SANDBOX------------------------------ #
service.IPNEndpoint=https://www.sandbox.paypal.com/cgi-bin/webscr
# ------------------------------PRODUCTION------------------------------ #
#service.IPNEndpoint=https://www.paypal.com/cgi-bin/webscr

#Sandbox Details
sandbox.EmailAddress=Platform.sdk.seller@gmail.com

# Multiple end-points configuration, while using multiple SDKs in combination, like Merchant and Permissions etc..
# configure the endpoints as shown below one for each service used, The existing service.EndPoint property is still 
# supported for backward compatibility (using a single SDK)
# ------------------------------SANDBOX------------------------------ #
# Merchant/Button Manager Service (3 Token)
# service.EndPoint.PayPalAPI=https://api-3t.sandbox.paypal.com/2.0
# service.EndPoint.PayPalAPIAA=https://api-3t.sandbox.paypal.com/2.0

# Merchant/Button Manager Service (Certificate)
# service.EndPoint.PayPalAPI=https://api.sandbox.paypal.com/2.0
# service.EndPoint.PayPalAPIAA=https://api.sandbox.paypal.com/2.0

# AdaptiveAccounts Platform Service
# service.EndPoint.AdaptiveAccounts=https://svcs.sandbox.paypal.com/

# AdaptivePayments Platform Service
# service.EndPoint.AdaptivePayments=https://svcs.sandbox.paypal.com/

# Invoice Platform Service
# service.EndPoint.Invoice=https://svcs.sandbox.paypal.com/

# Permissions Platform Service
# service.EndPoint.Permissions=https://svcs.sandbox.paypal.com/

# ------------------------------PRODUCTION------------------------------ #
# Merchant/Button Manager Service (3 Token)
# service.EndPoint.PayPalAPI=https://api-3t.paypal.com/2.0
# service.EndPoint.PayPalAPIAA=https://api-3t.paypal.com/2.0

# Merchant/Button Manager Service (Certificate)
# service.EndPoint.PayPalAPI=https://api.paypal.com/2.0
# service.EndPoint.PayPalAPIAA=https://api.paypal.com/2.0

# AdaptiveAccounts Platform Service
# service.EndPoint.AdaptiveAccounts=https://svcs.paypal.com/

# AdaptivePayments Platform Service
# service.EndPoint.AdaptivePayments=https://svcs.paypal.com/

# Invoice Platform Service
# service.EndPoint.Invoice=https://svcs.paypal.com/

# Permissions Platform Service
# service.EndPoint.Permissions=https://svcs.paypal.com/

this is my sdk config but i am getting https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-565506906D207290L#/checkout/genericError?code=REVGQVVMVA%3D%3D this isuue

**Comment by pp-randy** [comment]
What SDK are you using?  I thought it was the Java repository.  Can you provide the link? 

This is a lot of configuration, and I expect you are not using this particular repo.

**Comment by avinashpothula** [comment]
https://github.com/paypal/sdk-core-java this resipo i am using

**Comment by avinashpothula** [comment]
Request URL:https://www.sandbox.paypal.com/webapps/hermes/api/batch/setbuyer
Request Method:POST
Status Code:400 Bad Request
Remote Address:173.0.82.77:443
Referrer Policy:no-referrer-when-downgrade

**Comment by avinashpothula** [comment]
what was it how can i fix this. i could not get any idea about that

**Comment by pp-randy** [comment]
What are the API calls you are wanting to make?  If it is PayPal Payments or Express Checkout switch to this repo https://github.com/paypal/PayPal-Java-SDK/ and review the [sample for a PayPal Payment](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sample/src/main/java/com/paypal/api/payments/servlet/PaymentWithPayPalServlet.java).

**Comment by pp-randy** [comment]
I was able to find your error, it appears related to the Currency Code you are using. 

What currency code are you using?  You can find the supported ones here https://developer.paypal.com/docs/classic/api/currency_codes/.

**Comment by avinashpothula** [comment]
thanks randy

**Comment by avinashpothula** [comment]
i want to make paypal with payment but i did not getting response.
my responce is  Request URL:https://www.sandbox.paypal.com/webapps/hermes/api/batch/setbuyer

**Comment by avinashpothula** [comment]
when i do with paypal with credit card working .but coming to paypal with payment i did not getting response

**Comment by avinashpothula** [comment]
i getting this tesponce when i call this link i getting 
We’re sorry
Things don’t appear to be working at the moment. this responce 
https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_express-checkout&token=EC-9PD693984L732913V what is error how can i fix this any one please help .i did not getting proper answer

**Comment by pp-randy** [comment]
Can you test your payment without passing in a `SUBJECT` in your API request?  I see a Indian Business account facilitating a payment, with an Indian Buyer account, but your subject account (the receiver) is an unverified German Business.

**Comment by avinashpothula** [comment]
absolute  correct  what you had said . i am using Indian sandbox credentials. 
can you tell me what is subject in paypal api .

**Comment by pp-randy** [comment]
It would be one of the parameters being sent in with the API request. Try searching for a `SUBJECT` parameter or log the API request being made and see if its there.

**Comment by avinashpothula** [comment]
i did not get that subject. i check all program. i get response when i give example credentials. but my credentials getting bad response. what is problem how can do that.

**Comment by pp-randy** [comment]
Can you create a new payment and provide me the correlation id from the response?

**Comment by avinashpothula** [comment]
hi RANDY 
THANKS FOR YOUR RESPONSE FOR MY ISSUE .
I SOLVED IT. THE PROBLEM IS I GIVE WRONG CURRENCY. IT TAKE INDIAN CURRENCY BUT I GIVE USA.

**Comment by avinashpothula** [comment]
can i put PayPal withdraws on my site. can i save each withdrawn details. have any API for this . any one suggest me how can i do this

**Comment by xiaoleih41** [comment]
There's no API for withdrawal. Users will have to login to withdrawal funds or set up settlement withdrawal. You may want to contact the customer support number listed on your account as each region will have different rules on withdrawal.

**Comment by avinashpothula** [comment]
thanks for reply.

**Comment by avinashpothula** [comment]
The user has requested to admin for money.admin has send money  without login the PayPal account(automatic). this means user withdraw money from merchant account. can i know how could i do this  any API for this

**Comment by avinashpothula** [comment]
i am using  POST /v1/payments/payouts for sending money 
i get response this   "errors": {
			"name": "RECEIVER_UNREGISTERED",
			"message": "Receiver is unregistered",
			"information_link": "https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"
what was this error

**Comment by xiaoleih41** [comment]
The payment receiver has to be a registered PayPal user.

**Comment by avinashpothula** [comment]
I can successfully send money through sandbox REST API, but I get Authorization error occurred when using live API endpoint. i getting error response is Response code: 403	Error response: {"name":"AUTHORIZATION_ERROR","message":"Authorization error occurred","debug_id":"6ddad786cb0c0","information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors"} how could i solve this error

**Comment by xiaoleih41** [comment]
I cannot discuss your live account detail on this open forum but please contact customer service listed on your account to see if your payout API is completely enabled inside of your account, if your payout account is verified with all the funding source and if you have enough PayPal balance to cover the payout.
