### ISSUE TITLE
A problem of payout sync_mode

### ISSUE THREAD

**Issue by qqyycom** [paypal/PayPal-Java-SDK#308]
### General information

* SDK/Library version:  Latest
* Environment:  Sandbox
* `PayPal-Debug-ID` values:  f5fb06b4587d0	
* Language, language version, and OS: JDK1.1.0_80  on Windows 10

### Issue description

ERROR [com.forms.rest.payment.paypal.service.PayoutService] - class com.paypal.base.rest.PayPalRESTException 
response-code: 403	details: name: SYNC_MODE_NOT_APPLICABLE	message: Synchronous mode will soon be deprecated and is no longer available for new integrations. You can use the asynchronous mode by specifying sync_mode= false in the request.	details: null	debug-id: f5fb06b4587d0	information-link: https://developer.paypal.com/docs/api/payments.payouts-batch/#errors

I invoke the sync_create method of payout instance yesterday and it happened

but today I do it same and it success

I use the same App client

**Comment by pp-randy** [comment]
Do you already have a production integration using payouts in synchronous mode?

**Comment by mmaxine** [comment]
Yes, I'm having the same problem, it's failing in both sandbox and live environments with the following error message:

response-code: 403      details: name: SYNC_MODE_NOT_APPLICABLE message: Synchronous mode will soon be deprecated and is no longer available for new integrations. You can use the asynchronous mode by specifying sync_mode= false in the request.     details: null   debug-id: 73a80642c62e  information-link: https://developer.paypal.com/docs/api/payments.payouts-batch/#errors

**Comment by xiaoleih41** [comment]
Please use **async mode** instead as **sync mode** is deprecated. It can cause bandwidth issues sometimes.

**Comment by pp-randy** [comment]
@mmaxine please reach out to [PayPal Technical Support](https://www.paypal-techsupport.com/app/ask) if you are seeing this with an existing Live integration. 

Per the documentation it should be supported. 
![image](https://user-images.githubusercontent.com/6819909/28891489-49a245f6-7790-11e7-8a06-fb82fb0051d5.png)

**Comment by mmaxine** [comment]
I did reach out and they told me to move to asynchronous despite the documentation doesn't mention any current termination of the synchronous api for now.

How is the result of the asynchronous API differs from the synchronous one? 

My understanding is that the asynchronous API will give you a batch id but how do we know if the payouts are really going through and successful? Is this supposed to be know using webhooks?

Thanks!

**Comment by pp-randy** [comment]
> How is the result of the asynchronous API differs from the synchronous one?

_Synchronous_ mode will attempt to complete the payout before the API call ends.  _Asynchronous_ mode will return the API response if the batch was created; however, this doesn't mean the payouts have completed. 

> My understanding is that the asynchronous API will give you a batch id but how do we know if the payouts are really going through and successful? Is this supposed to be know using webhooks?

Yes, you should utilize webhooks to know when the payout batch completes.

**Comment by qqyycom** [comment]
@pp-randy  sorry for delayed response.  we used synchronous mode before and now  we have changed async_mode  and   would you please help me with my question #309

**Comment by xiaoleih41** [comment]
Close this issue as synchronous mode is deprecated.
