### ISSUE TITLE
A question of payout async_mode

### ISSUE THREAD

**Issue by qqyycom** [paypal/PayPal-Java-SDK#309]
### General information

* SDK/Library version:  Latest
* Environment:  Sandbox	
* Language, language version, and OS: JDK1.1.0_80  on Windows 10

### Issue description

When  I use Debugger mode  , I found the <b>items</b> object was <b>NULL</b> in <b>PayoutBatch</b> object, but the response shows that isn't .  and  the sync_mode has the items object

I want to know if there is any bug

**Comment by pp-randy** [comment]
Sync mode completes the payouts batch before returning the response.  Async mode you need to rely on webhooks.

**Comment by qqyycom** [comment]
@pp-randy  sorry for delayed responding. I got it
