### ISSUE TITLE
Why APIContext cannot be reused?

### ISSUE THREAD

**Issue by lojzatran** [paypal/PayPal-Java-SDK#311]
### General information

* SDK/Library version: 1.13.1
* Environment: sandbox

### Issue description

According to the docs of the SDK, we should always create new `APIContext` for every request call.  What is exactly the reason for this? Why can't we share `APIContext`? Looking at the code, I see the reason could be [requestId](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/rest/APIContext.java#L317). If so, why requestId is not recreated every time the method is called and why is it cached?

**Comment by pp-randy** [comment]
The request id is used for an idempotent response.  If a request fails due to a timeout, the same request id and the details from the original request should be returned.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been provided.
