### ISSUE TITLE
Mapper for Webhook Event is missing

### ISSUE THREAD

**Issue by simplicii** [paypal/PayPal-Java-SDK#315]
### General information

* SDK/Library version: 1.13.1
* Environment: Sandbox and Production, its uncomplete SDK implementation
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: any

### Issue description
Using Spring Controller to get webhook events there is no default mapper from json to Java Bean.
This is not very convenient and every user needs to implement it on his own.

Pelasee add a Mapper and the Beans so the json can be mapped.

**Comment by xiaoleih41** [comment]
Thank you for the suggestion. If you can submit a pull request, we will be glad to review.

**Comment by xiaoleih41** [comment]
Close this due to inactivity.
