### ISSUE TITLE
Timeout hard-coded to 5 seconds

### ISSUE THREAD

**Issue by flappingeagle** [paypal/PayPal-Java-SDK#320]
### General information

* SDK/Library version: 1.13.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: 29c7fbc3525b2
* Language, language version, and OS: Java-1.8.0u102-201609081643, Ubuntu 17.04

### Issue description

Sometimes i notice the following exception while calling "Payment.create(apiContext)". 

<pre>
Caused by: com.paypal.base.exception.HttpErrorException: Response code: 500	Error response: {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"29c7fbc3525b2"}
	at com.paypal.base.HttpConnection.executeWithStream(HttpConnection.java:162)
	at com.paypal.base.HttpConnection.execute(HttpConnection.java:65)
	at com.paypal.base.rest.PayPalResource.execute(PayPalResource.java:417)
</pre> 

I think this may be a timeout-issue in regards to slow sandbox-servers. 
Please see: https://github.com/paypal/paypal-checkout/issues/477
Please see: https://stackoverflow.com/questions/26785027/paypal-rest-api-returning-error-code-500-for-payment-verification

I want to suggest, to maybe increase the hard-coded timeout of "5 Seconds" (see: PayPalResource.createHttpConfiguration) to a larger value in the sandbox-environment to stop such problems in the sandbox-environment.

But if its really a timeout-problem it would also be not critical in sandbox and could just be ignored by sandbox-user?

**Comment by pp-randy** [comment]
You can increase the timeouts in the configuration https://github.com/paypal/PayPal-Java-SDK/wiki/What-happened-to-sdk_config.properties, and see if increasing them works.  

We will review the debug id further and get back to you.

**Comment by flappingeagle** [comment]
i increased the timeout to 20 seconds and checked in the Debugger that the value is correctly used. So thanks, this should help a bit.
<pre>
  apiContext.addConfiguration("http.ConnectionTimeOut", "20000");
</pre>

But even with this setting i sometimes get Response code: 500 Exceptions, so there must be something else going on... so i will wait for you reviewing the debug id. 
<pre>
com.paypal.base.exception.HttpErrorException: Response code: 500	Error response: {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"4dd885bb64ce6"}
</pre>

**Comment by pp-randy** [comment]
I see some potential issues with the sandbox account.  Can you try again?  I made some changed to try to address this.

**Comment by flappingeagle** [comment]
ah thx. Seems this was the correct fix.
I cant seem to get the 500 Exceptions anymore.

**Comment by xiaoleih41** [comment]
Close the issue as the issue has been solved.
