### ISSUE TITLE
Unable to make payment via payment method: credit_card

### ISSUE THREAD

**Issue by ajit-soman** [paypal/PayPal-Java-SDK#321]
### General information

* SDK/Library version: 1.13.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: a482b1b59ce8
* Language, language version, and OS:  Java 1.8  on Ubuntu 14.04 

### Issue description
Getting error with payment method `credit_card`  but runs well with type `paypal`
Here is the error log: 
<pre>m2017-10-23 22:57:31.289 ERROR 16557 --- [nio-8080-exec-3] com.paypal.base.HttpConnection           : Error code : 400 with response : {"name":"UNKNOWN_ERROR","message":"An unknown error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"a482b1b59ce8"}</pre>
Here is my method:
<pre>
public Payment createPayment(
			Double total, 
			String currency, 
			PaypalPaymentMethod method, 
			PaypalPaymentIntent intent, 
			String description, 
			String cancelUrl, 
			String successUrl) throws PayPalRESTException{
		Amount amount = new Amount();
		amount.setCurrency(currency);
		amount.setTotal(String.format("%.2f", total));

		Transaction transaction = new Transaction();
		transaction.setDescription(description);
		transaction.setAmount(amount);

		List<Transaction> transactions = new ArrayList<>();
		transactions.add(transaction);

		Payer payer = new Payer();
		payer.setPaymentMethod(method.toString());
		
		if(method.equals(PaypalPaymentMethod.credit_card)){
			FundingInstrument fundingInstrument = new FundingInstrument();
			CreditCard creditCard = new CreditCard();
			
			creditCard = creditCard.setBillingAddress(createAddress()).setExpireMonth(EXPMONTH)
					.setExpireYear(EXPYEAR).setFirstName(FIRSTNAME)
					.setLastName(LASTNAME).setNumber(NUMBER).setType(TYPE)
					.setCvv2(CVV2).setBillingAddress(createAddress()).setId(ID)
					.setState(STATE).setValidUntil(VALIDUNTIL);
			fundingInstrument.setCreditCard(creditCard);
			List<FundingInstrument> fundingInstruments = new ArrayList<FundingInstrument>();
			fundingInstruments.add(fundingInstrument);
			
			payer.setFundingInstruments(fundingInstruments);
		}
		
		Payment payment = new Payment();
		payment.setIntent(intent.toString());
		payment.setPayer(payer);
		payment.setTransactions(transactions);
		RedirectUrls redirectUrls = new RedirectUrls();
		redirectUrls.setCancelUrl(cancelUrl);
		redirectUrls.setReturnUrl(successUrl);
		payment.setRedirectUrls(redirectUrls);

		return payment.create(apiContext);
	}
</pre>

**Comment by xiaoleih41** [comment]
Credit card feature has been deprecated from REST API SDKs. Please consider to integrate Braintree SDK from braintreepayments.com instead.

**Comment by ajit-soman** [comment]
@xiaoleih41 Thanks for your comment

I just want to know one thing , Does braintree support merchant account in india ? . Because in braintree website they haven't mentioned india in their supported countries list.

**Comment by pp-randy** [comment]
It does not appear India is supported at this time by Braintree; however, PayPal also does not have a direct credit card offering for India either.  

You can use the PayPal funding option in conjunction with our Checkout JS offering https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/. You can test it here https://developer.paypal.com/demo/checkout/, this keeps the buyers on your website in most cases.
