### ISSUE TITLE
Getting "internal service error" while making payment using saved credit card

### ISSUE THREAD

**Issue by haresh14** [paypal/PayPal-Java-SDK#322]
### General information

* SDK/Library version: 1.13.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: 412e30597eea7
* Language, language version, and OS: Java 1.8.0_25 Ubuntu, Tomcat 8.0.15

### Issue description

I am getting internal service error when trying to call the payment.create(context) method with web application running on tomcat. Whereas same code works if i run the method with java class.
I suspect it could be a jar conflicts with tomcat jars but i'm not sure how to find the cause of error and fix it

Is there anyone who can help me please?

**Comment by xiaoleih41** [comment]
@haresh14 credit card processing feature has been deprecated for this SDK. If you haven't obtained the approval for production usage, please consider to integration Braintree SDK from braintreepayments.com instead.

**Comment by haresh14** [comment]
@xiaoleih41 But how its been deprecated? I have never seen in paypal which should say that its been deprecated. Also if its deprecated then why standalone java class works whereas it doesnt work with tomcate? I am using paypal Vault API to store the card and payment api to make the payment with the stored card. Vault API works fine in every cases.

**Comment by xiaoleih41** [comment]
@haresh14 We can look into the issue but if you haven't been approved for credit card processing for your live app credential,  you may consider to integrate Braintree SDK as no new integration will be approved to use this feature.

**Comment by haresh14** [comment]
@xiaoleih41 I'm just testing with sandbox so didnt get approved for credit card processing as live env is not ready yet.

**Comment by xiaoleih41** [comment]
stop integrating this SDK if that's the case. We have updated the SDK README.MD with the deprecated message. Please consider integrating Braintree SDK from braintreepayments.com instead.

**Comment by xiaoleih41** [comment]
Close as the suggestion has been provided.
