### ISSUE TITLE
Some configuration options are not used when generating oauth token

### ISSUE THREAD

**Issue by jbackes** [paypal/PayPal-Java-SDK#327]
### General information

* SDK/Library version: latest
* Environment: production
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 8u151-b12-0ubuntu0.16.04.2 on Ubuntu 16.04

### Issue description

We realized that sometimes (very rare cases) we have forever hanging http connections when generating an outh token. As far as I understand the code, the configuration for oauth connections is generated in `com.paypal.base.rest.OAuthTokenCredential::getOAuthHttpConfiguration()` (Line 446). This method does not set options like `readTimout` which should close the connections after some time and throw an exception. In contrast to that, for "normal" rest connections, the option is set in `com.paypal.base.rest.PayPalResource::createHttpConfiguration(Map<String, String>, HttpMethod, APICallPreHandler)` (Line 452), for example in Lines 481/482:
```
httpConfiguration.setReadTimeout(Integer.parseInt(configurationMap
				.get(Constants.HTTP_CONNECTION_READ_TIMEOUT)));
```
Why is that difference? Is it possible to set all (relevant) options there as well?

**Comment by xiaoleih41** [comment]
We are looking into it. Thank you for pointing it out.
