### ISSUE TITLE
Payment/Order#applicationContext property is not available

### ISSUE THREAD

**Issue by andrii-kovalenko-ct** [paypal/PayPal-Java-SDK#330]
Relative to https://github.com/paypal/PayPal-REST-API-issues/issues/179

### General information

* SDK/Library version: *1.14.0* (latest)
* Environment: any

### Issue description

`Payment/Order#applicationContext` property is not available

#### Details

We need to prevent customer (buyer) changes address during payment approving. As discussed with [Kristian Büsch](https://www.linkedin.com/in/kristian-büsch-57429a19/) (can't refer him from GitHub) the recommended way to do this - using `application_context#shipping_preference` entity in create payment, for example:
```bash 
curl --request POST 'https://api.sandbox.paypal.com/v1/payments/payment' \
  --data '{
  "intent": "sale",
  "payer": {
    "payment_method": "paypal"
  },
  "application_context": {
    "locale": "DE",
    "brand_name": "Company Name",
    "shipping_preference": "NO_SHIPPING"
  },
  "transactions": [
.......
```

this approach works fine (we testes using HTTP REST API), but [`Payment`](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/api/payments/Payment.java) class (as same as known descendants)  doesn't have this property.

**Note**:
  - looks like the property is not documented in [Payments API](https://developer.paypal.com/docs/api/payments/#payment)
  - in the same time it is documented in [Orders API](https://developer.paypal.com/docs/api/orders/#definition-application_context). Kristian Büsch mentioned the entity is the same for orders and payments
  - could you figure out is it shared on other API entities?

Also, last but not least: this feature (prevent address change) is very important for us and our customers, so pls respond as soon as possible.

Thanks.

**Comment by xiaoleih41** [comment]
I am filing an issue with API team to get this property listed under **Payments API** section as it does support this property. I am pretty sure that it only support these two APIs but I will double confirm and get back to you.

**Comment by andrii-kovalenko-ct** [comment]
i've created relative API documentation request:
https://github.com/paypal/PayPal-REST-API-issues/issues/179

**Comment by xiaoleih41** [comment]
@andrii-kovalenko-ct Great! I noted the internal ticket there for tracking. I will close this issue but update the status over instead. Please track the status on the new issue paypal/PayPal-REST-API-issues#179 going forward.
