### ISSUE TITLE
Cannot use amount discounts for invoices

### ISSUE THREAD

**Issue by fschon** [paypal/PayPal-Java-SDK#341]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

Whilst creating an invoice using the rest api:

The problem is that one cannot set a amount discount and a percentage discount a the same time. So when setting an amount discount, the percentage discount needs to be nullable. Since this is a java "float" variable in Cost.java, it cannot be nulled and is always converted to the float default value of zero, i.e. "0.0" in the json text. Thus causing the above error that both amount and percentage cannot be set.

I have seen the same error reported for the .NET api, however these issues, even though they were properly described, were closed without fixing them (the original submitter/s did not respond quickly enough).

**Comment by xiaoleih41** [comment]
I am looking into our V2 beta. it looks like it is parsed as an object, this should work. Please take a look [here](https://github.com/paypal/PayPal-Java-SDK/blob/2.0-beta/paypal-sdk/src/main/java/com/paypal/sdk/v1/invoices/Cost.java).

**Comment by fschon** [comment]
Yes, it now looks correct in V2beta. Is there a fix planned for the current production versions?

**Comment by xiaoleih41** [comment]
I have submitted the case. V2 is the focus at this time so I believe the issue in the v1 may be fixed but not be soon.

**Comment by sucithrashanu** [comment]
@fschon 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check[ PayPal Community ](https://www.paypal-community.com )and  [MTS](https://paypal.com/mts) 
Thanks!

**Comment by sucithrashanu** [comment]
@xiaoleih41 
Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.

Please Check PayPal Community  (https://www.paypal-community.com )and  MTS ( https://paypal.com/mts )
Thanks!
