### ISSUE TITLE
Capture the authorization code, How ?

### ISSUE THREAD

**Issue by vi007ra** [paypal/PayPal-Java-SDK#342]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

I think this is more a query upon steps mentioned rather any issue.

This is regarding the step you mentioned << Capture the authorization code that is available as a query parameter (code) in the redirect url. >> How can extract the authorization code embed into the redirectUrl, this is my redirectUrl : " https://www.sandbox.paypal.com/signin/authorize?client_id=&response_type=code&scope=openid+profile+address+email+https%3A%2F%2Furi.paypal.com%2Fservices%2Fpaypalattributes+https%3A%2F%2Furi.paypal.com%2Fservices%2Fexpresscheckout+https%3A%2F%2Furi.paypal.com%2Fservices%2Finvoicing+&redirect_uri=UserConsent "

**Comment by vi007ra** [comment]
This is regarding the step you mentioned << Capture the authorization code that is available as a query parameter (code) in the redirect url. >> How can extract the authorization code embed into the redirectUrl, this is my redirectUrl : " https://www.sandbox.paypal.com/signin/authorize?client_id=&response_type=code&scope=openid+profile+address+email+https%3A%2F%2Furi.paypal.com%2Fservices%2Fpaypalattributes+https%3A%2F%2Furi.paypal.com%2Fservices%2Fexpresscheckout+https%3A%2F%2Furi.paypal.com%2Fservices%2Finvoicing+&redirect_uri=UserConsent "

**Comment by xiaoleih41** [comment]
The `code` should have been sent to the `return_uri` specified in your `redirectUrl` for you to retrieve and process.

**Comment by xiaoleih41** [comment]
close the issue as the question as been answered. Please resubmit if you have any further questions.

**Comment by vi007ra** [comment]
Thank you, @xiaoleih41. will update you once I will relook the item.
