### ISSUE TITLE
Create Order

### ISSUE THREAD

**Issue by AlanMenhennet** [paypal/PayPal-Java-SDK#343]
General information
Environment: Sandbox
PayPal-Debug-ID values: 48d879102f339
Language, language version, and OS: Java 1.8 on Windows 7

### Issue description

I previously submitted the following issue to the api github, they advised me to use the Orders API. But I cannot see any documentation for creating orders via the Java SDK.

#### Original Issue
When trying to set a country code, or phone number on PayerInfo via the Java SDK, when I call payment.create() I get the following response

{"name":"MALFORMED_REQUEST","message":"Incoming JSON request does not map to API request","information_link":"https://developer.paypal.com/webapps/developer/docs/api/#MALFORMED_REQUEST","debug_id":"48d879102f339"}

I've scoured the docs and can't see why the country code or phone number cause this error. I can set the first name, last name, email succesfully.

Here's my request as serialized by the Java SDK. What I'm trying to achieve is prefilling the details for guest checkout.

{
"intent": "sale",
"payer": {
"payment_method": "paypal",
"payer_info": {
"email": "john@doe.com.au",
"first_name": "John",
"last_name": "Doe",
"country_code": "AU",
"billing_address": {
"phone": "1300123123",
"line1": "1 Test St",
"city": "Testville",
"country_code": "AU",
"postal_code": "3000",
"state": "VIC"
}
}
},
"transactions": [
{
"amount": {
"currency": "AUD",
"total": "45.55",
"details": {
"subtotal": "35.00",
"shipping": "10.55",
"tax": "0"
}
},
"description": "",
"note_to_payee": "Sent via Australia Post Domestic Parcel Post",
"custom": "Sent via Australia Post Domestic Parcel Post",
"item_list": {
"items": [
{
"name": "Beige knitted peaked Cap - small - C0020",
"quantity": "1",
"price": "35.00",
"currency": "AUD"
}
],
"shipping_address": {
"recipient_name": "John Doe",
"phone": "1300123123",
"line1": "1 Test St",
"city": "Testville",
"country_code": "AU",
"postal_code": "3000",
"state": "VIC"
},
"shipping_method": "Sent via Australia Post Domestic Parcel Post",
"shipping_phone_number": "123"
}
}
],
"redirect_urls": {
"return_url": "http://www.test.com.au/shop/category/bag/176",
"cancel_url": "http://www.test.com.au/shop/category/bag/176"
}
}

**Comment by xiaoleih41** [comment]
Can I ask what you are trying to achieve by setting up the country code in `payer_info`? This will help us to find a solution for you.

**Comment by AlanMenhennet** [comment]
when checking out via Guest checkout, only half the person's details I pass are being set. I believe this is because country isn't set, so therefore state isn't set.

I have the same problem when setting a phone number

**Comment by shoobham** [comment]
I'm having a similar issue and not able to find any solution

**Comment by Trupti21** [comment]
@AlanMenhennet , @shoobham ,

Below is my Request body and it works perfectly fine.

{
  "intent": "sale",
  "payer": {
    "payment_method": "paypal",
    "payer_info": {
"email": "john@doe.com.au",
"first_name": "John",
"last_name": "Doe",
"billing_address": {
"phone": "1300123123",
"line1": "1 Test St",
"city": "Testville",
"country_code": "US",
"postal_code": "3000",
"state": "VIC"
}
}
  },
  
  "transactions": [
    {
      "amount": {
        "total": "30.11",
        "currency": "USD",
        "details": {
          "subtotal": "30.00",
          "tax": "0.07",
          "shipping": "0.03",
          "handling_fee": "1.00",
          "shipping_discount": "-1.00",
          "insurance": "0.01"
        }
      },
      "description": "The payment transaction description.",
      "custom": "EBAY_EMS_90048630024435",
      "payment_options": {
        "allowed_payment_method": "INSTANT_FUNDING_SOURCE"
      },
      "soft_descriptor": "ECHI5786786",
      "item_list": {
        "items": [
          {
            "name": "hat",
            "description": "Brown hat.",
            "quantity": "5",
            "price": "3",
            "tax": "0.01",
            "sku": "1",
            "currency": "USD"
          },
          {
            "name": "handbag",
            "description": "Black handbag.",
            "quantity": "1",
            "price": "15",
            "tax": "0.02",
            "sku": "product34",
            "currency": "USD"
          }
        ],
        "shipping_address": {
          "recipient_name": "Brian Robinson",
          "line1": "4th Floor",
          "line2": "Unit #34",
          "city": "San Jose",
          "country_code": "US",
          "postal_code": "95131",
          "phone": "2025550110",
          "state": "CA"
        }
      }
    }
  ],
  "note_to_payer": "Contact us for any questions on your order.",
  "redirect_urls": {
    "return_url": "https://example.com/return",
    "cancel_url": "https://example.com/cancel"
  }
}

Now to answer your question - country_code and phone_number currently not supported in this request.

Thanks

**Comment by Trupti21** [comment]
@AlanMenhennet ,
Below code snippet is working fine for me. Try this.

`package com.javasdk.paypal.service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.paypal.api.payments.Amount;
import com.paypal.api.payments.Payer;
import com.paypal.api.payments.Payment;
import com.paypal.api.payments.PaymentExecution;
import com.paypal.api.payments.PotentialPayerInfo;
import com.paypal.api.payments.RedirectUrls;
import com.paypal.api.payments.Transaction;
import com.paypal.base.rest.APIContext;
import com.paypal.base.rest.PayPalRESTException;

import com.paypal.api.payments.PotentialPayerInfo;
import com.javasdk.paypal.config.PaypalPaymentIntent;
import com.javasdk.paypal.config.PaypalPaymentMethod;
import com.paypal.api.payments.Address;
import com.paypal.api.payments.BaseAddress;
import com.paypal.api.payments.Details;
import com.paypal.api.payments.Item;
import com.paypal.api.payments.ItemList;
import com.paypal.api.payments.PotentialPayerInfo;
import com.paypal.api.payments.ShippingInfo;
import com.paypal.api.payments.Phone;
import com.paypal.api.payments.ShippingAddress;
import com.paypal.api.payments.PayerInfo;
import com.paypal.api.payments.InvoiceAddress;
import com.paypal.api.payments.Invoice;
@Service
public class PaypalService {

	@Autowired
	private APIContext apiContext;
	
	public Payment createPayment(
			
			String currency, 
			PaypalPaymentMethod method, 
			PaypalPaymentIntent intent, 
			String description, 
			String cancelUrl, 
			String successUrl) throws PayPalRESTException{
		
		
		// ###Details
		// Let's you specify details of a payment amount.
		Details details = new Details();
		details.setShipping("0.03");
		details.setSubtotal("30.00");
		details.setTax("0.07");
		details.setInsurance("0.01");
		details.setHandlingFee("1.00");
		details.setShippingDiscount("-1.00");
		
		Amount amount = new Amount();
		amount.setCurrency(currency);
		amount.setTotal("30.11");
		amount.setDetails(details);
		
		


		// ### Items
		Item item = new Item();
		
		item.setName("hat").setSku("1").setDescription("Brown hat").setPrice("5").setCurrency("USD").setTax("0.01").setQuantity("5");
		item.setName("handbag").setSku("product34").setDescription("Black handbag.").setPrice("15.00").setCurrency("USD").setTax("0.02").setQuantity("1");
		ItemList itemList = new ItemList();
		List<Item> items = new ArrayList<Item>();
		items.add(item);
		items.add(1, item);
		itemList.setItems(items);
		itemList.setShippingPhoneNumber("2025550110");
		
		Transaction transaction = new Transaction();
		transaction.setDescription(description);
		transaction.setAmount(amount);
		transaction.setItemList(itemList);
		
		List<Transaction> transactions = new ArrayList<>();
		transactions.add(transaction);
		
		Phone p = new Phone();
		p.setCountryCode("1");
		p.setNationalNumber("120");
		p.setExtension("255-5011");
		
		Address ad =new Address();
		ad.setPhone("2025550110");
		ad.setCity("San Jose");
		ad.setCountryCode("US");
		ad.setLine1("4th Floor");
		ad.setLine2("Unit #34");
		ad.setState("CA");
		ad.setPostalCode("95131");
		
		PayerInfo pi = new PayerInfo();
		pi.setFirstName("Brian");
		pi.setLastName("Robinson");
		pi.setBillingAddress(ad);
		
		Payer payer = new Payer();
		payer.setPaymentMethod(method.toString());
		payer.setPayerInfo(pi);
		
		Payment payment = new Payment();
		payment.setIntent(intent.toString());
		payment.setPayer(payer);
		payment.setTransactions(transactions);
		
		RedirectUrls redirectUrls = new RedirectUrls();
		redirectUrls.setCancelUrl(cancelUrl);
		redirectUrls.setReturnUrl(successUrl);
		payment.setRedirectUrls(redirectUrls);
		System.out.println("payment details "+payment);
		
		return payment.create(apiContext);
	}
	
	public Payment executePayment(String paymentId, String payerId) throws PayPalRESTException{
		Payment payment = new Payment();
		payment.setId(paymentId);
		
		PaymentExecution paymentExecute = new PaymentExecution();
		paymentExecute.setPayerId(payerId);
		return payment.execute(apiContext, paymentExecute);
	}
}
`
<img width="1664" alt="Screenshot 2019-10-22 at 1 31 13 PM" src="https://user-images.githubusercontent.com/46967620/67268330-c7446000-f4d1-11e9-95ce-c1847426185d.png">

Thanks

**Comment by Trupti21** [comment]
@AlanMenhennet ,
Try above solution. If that doesn’t  work Please reopen the issue.

Thanks
