### ISSUE TITLE
Can you provide Server IPN demo?

### ISSUE THREAD

**Issue by bozomoyy** [paypal/PayPal-Java-SDK#346]
or where is it?

**Comment by xiaoleih41** [comment]
Are you looking for [IPN simulator](https://developer.paypal.com/docs/classic/ipn/integration-guide/IPNSimulator/?mark=IPN)?

**Comment by bozomoyy** [comment]
Not the simulator,i just wanna server IPN code or demo

**Comment by bozomoyy** [comment]
the language is Java

**Comment by xiaoleih41** [comment]
Do you want to use webhooks? That's what REST SDK does. For classic API, we use IPN. You can get some info from [here](https://github.com/paypal/merchant-sdk-java/blob/master/merchantsample/IPN-README.md)

**Comment by xiaoleih41** [comment]
Close the the answer has been given.
