### ISSUE TITLE
Unable to initiate payment

### ISSUE THREAD

**Issue by bozomoyy** [paypal/PayPal-Java-SDK#348]
When i click the payment button,alert a subpage,but this subpage always keep loading,and doesn't load any content ?

**Comment by xiaoleih41** [comment]
Are you using PayPal checkout components?  You may consider close this issue and ask here https://github.com/paypal/paypal-checkout

**Comment by xiaoleih41** [comment]
Close due to inactivity. The correct channel has been provided.
