### ISSUE TITLE
Get Authorization fail: PERMISSION_DENIED

### ISSUE THREAD

**Issue by maiconcarraro** [paypal/PayPal-Java-SDK#349]
### General information

* SDK/Library version: paypal-core:1.6.9 / rest-api-sdk:1.13.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: 5f470c54f1c35

### Issue description

I changed the payment intent from **sale** to **authorize**, it successfully created and returned an authorization ID. After, I tried to get the authorization:

`APIContext apiContext = new APIContext(...)`
`Authorization authorization = Authorization.get(apiContext, order.getAuthorizationId());`

But it returns an error:
` response-code: 403	details: name: PERMISSION_DENIED	message: No permission for the requested operation	details: null	debug-id: 5f470c54f1c35	information-link: https://developer.paypal.com/docs/api/payments/#errors`

I checked my account permissions and everything looks right. What is missing?

**Comment by maiconcarraro** [comment]
Ok, I found a workaround for this situation. I took a look inside `authorization.capture` method, and it only use the authorization ID to create the request... so I just did:

`Authorization authorization = new Authorization();`
`authorization.setId(order.getAuthorizationId());`

Then:

`authorization.capture(apiContext, capture);`

Its worked, successfully created a capture and payment confirmed (checked on history)

--

Didnt understand about the permission to get authorization yet

**Comment by xiaoleih41** [comment]
It says the API account and the receiver account are not the same.

**Comment by maiconcarraro** [comment]
@xiaoleih41 so I need to set receiver's token to the apiContext to get the authorization? makes sense to work without that token the capture?

**Comment by xiaoleih41** [comment]
It appears that you cannot do with authorization with this API. You can only do sales. You may have to look into [PayPal marketplace product](https://developer.paypal.com/docs/marketplaces/pp4mp/) for the feature you are looking for.

**Comment by xiaoleih41** [comment]
Close this issue as the answer has been given.
