### ISSUE TITLE
How to include paypal dependency into my sbt project? 

### ISSUE THREAD

**Issue by Ericglh** [paypal/PayPal-Java-SDK#351]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by xiaoleih41** [comment]
Please follow the steps on the [wiki page](https://github.com/paypal/PayPal-Java-SDK/wiki).

**Comment by xiaoleih41** [comment]
Close the issue as the answer has been given
