### ISSUE TITLE
Progress of RC1

### ISSUE THREAD

**Issue by tonprince** [paypal/PayPal-Java-SDK#355]
Is there any progress in this project to become a final release? I need an API for production for Java.

**Comment by aldwindelgado** [comment]
This project is already ready for production though, we're using this for about 8 months now. 

What do you mean with the final release?

**Comment by tonprince** [comment]
Dear Aldwin
Thanks for the fast reply. Unfortunately the 1.x version we cannot use as there is a bug while using discounts with a fixed amount and currency (https://github.com/paypal/PayPal-Java-SDK/issues/341).

Is there any release planned for the version 2.0?

**Comment by tonprince** [comment]
Another question is how can we disable sending emails to customers when creating and updating invoices? I cannot find the correct flag to set, only the one notifyMerchant.

**Comment by trainerbill** [comment]
@tonprince it only sends an email when you run the send api not create/update.  If you don't want an email sent then you have to omit the email property when you create the invoice.
