### ISSUE TITLE
How to prevent sending invoice by email to customer when using InvoiceSendRequest?

### ISSUE THREAD

**Issue by tonprince** [paypal/PayPal-Java-SDK#357]
Is there a flag that prevents sending an email to the customer when using InvoiceSendRequest? There is a flag notifyMerchant, but I cannot find the one for the customer.

In the documentation is stated:

_https://developer.paypal.com/docs/api/invoicing/
UNPAID | A merchant chooses to suppress the PayPal email notification when he or she sends the invoice through the API or the Create Invoice page, and then manually sends the invoice link in his or her own email. To send an invoice without email notification, the merchant either: Sets the notify_merchant and notify_customer query parameters to false when he or she sends the invoice. Selects Share link myself from the Send menu when he or she sends the invoice through the web UI Create Invoice page._

**Comment by trainerbill** [comment]
You would have to omit the email value.

email string
The invoice recipient email address. If you omit this value, the invoice is payable and a notification email is not sent.
Maximum length: 260.
