### ISSUE TITLE
Paypal recurring payment  web hook 

### ISSUE THREAD

**Issue by AnuvadiyaHiren** [paypal/PayPal-Java-SDK#358]
Paypal sends PAYMENT.SALE.COMPLETED event when payment is completed.
But i wanted to identify for which interval payment is completed.

1) Which date i need to consider ?
   Web hook's "create_time"  or resource object "create_time"

{
  "id": "WH-3T907611VT954351W-1AU65894YF484680G",
  "event_version": "1.0",
  "create_time": "2018-06-22T18:54:49.851Z",
  "resource_type": "sale",
  "event_type": "PAYMENT.SALE.COMPLETED",
  "summary": "Payment completed for $ 10.0 USD",
  "resource": {
    "id": "1XM89398N2238812F",
    "state": "completed",
    "amount": {
      "total": "10.00",
      "currency": "USD",
      "details": {
        
      }
    },
    "payment_mode": "INSTANT_TRANSFER",
    "protection_eligibility": "ELIGIBLE",
    "protection_eligibility_type": "ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE",
    "transaction_fee": {
      "value": "0.81",
      "currency": "USD"
    },
    "billing_agreement_id": "I-XF6J4ST5J5DX",
    "create_time": "2018-06-22T14:11:21Z",
    "update_time": "2018-06-22T14:11:21Z",
    "links": [
      {
        "href": "https://api.sandbox.paypal.com/v1/payments/sale/1XM89398N2238812F",
        "rel": "self",
        "method": "GET"
      },
      {
        "href": "https://api.sandbox.paypal.com/v1/payments/sale/1XM89398N2238812F/refund",
        "rel": "refund",
        "method": "POST"
      }
    ],
    "soft_descriptor": "PAYPAL *TESTFACILIT"
  },
  "links": [
    {
      "href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-3T907611VT954351W-1AU65894YF484680G",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://api.sandbox.paypal.com/v1/notifications/webhooks-events/WH-3T907611VT954351W-1AU65894YF484680G/resend",
      "rel": "resend",
      "method": "POST"
    }
  ]
}

**Comment by Trupti21** [comment]
@AnuvadiyaHiren ,
You need to consider resource object "create_time".
Webhook trigger's after completion of event.

Thanks

**Comment by Trupti21** [comment]
@AnuvadiyaHiren ,
I am closing the issue. If you have any query please reopen.

Thanks
