### ISSUE TITLE
Verify web hook

### ISSUE THREAD

**Issue by AnuvadiyaHiren** [paypal/PayPal-Java-SDK#359]
Please provide detail about how to verify webhook is sent from authentic source.

boolean isValidEvent=Event.validateReceivedEvent(getApiContext(), Utils.getHeadersInfo(request),webHookData);

I have implemented above code and testing with developer console

I have sent web hook from 
https://developer.paypal.com/developer/dashboard/webhooks/sandbox

But it it throws error

com.paypal.base.rest.PayPalRESTException: webhook.id cannot be null
	at com.paypal.base.SDKUtil.validateAndGet(SDKUtil.java:85)

**Comment by prakash-gangadharan** [comment]
@AnuvadiyaHiren, please revert us back if this is still an issue.
