### ISSUE TITLE
toJSON not available anymore in 2.0.0

### ISSUE THREAD

**Issue by sankotm** [paypal/PayPal-Java-SDK#360]
### General information
* SDK/Library version: 2.0.0-SNAPSHOT
* Environment: Sandbox

### Issue description
In previous version there was a `toJSON()` method available to all objects extending `PayPalModel`. I can't find it in `2.0.0`. Is it deprecated now? Or Is there a different recommended serialization approach?
I'd like to use it for logging and debugging.

Thanks

**Comment by trainerbill** [comment]
version 2 is a complete rewrite so most functionality will be changing.  Can you use another library to accomplish this task such as Gson?

http://www.java2novice.com/java-json/google-gson/object-to-json-string/

**Comment by sankotm** [comment]
Hey, yes, for now I use `new GsonBuilder().create().toJson(thing)`. I was just wondering whether there isn't any SDK-native way to do it. 
Thanks.
