### ISSUE TITLE
application_context

### ISSUE THREAD

**Issue by halfbaked** [paypal/PayPal-Java-SDK#361]
The general api docs mention an application_context 
https://developer.paypal.com/docs/api/payments/v1/#definition-application_context
but I see no means to set it in this java sdk.
Am I missing something? 
thanks.

**Comment by mohadib** [comment]
I cam here looking for this information myself.

**Comment by Trupti21** [comment]
@halfbaked ,

Closing the issue. If you have any query. Please reopen.
Thanks
