### ISSUE TITLE
Receipts API available?

### ISSUE THREAD

**Issue by sankotm** [paypal/PayPal-Java-SDK#366]
### General information
* SDK/Library version: 2.0

### Issue description
Is there planned support for Receipts API?
(https://developer.paypal.com/docs/integration/paypal-here/sdk-dev/receipts/)

**Comment by sucithrashanu** [comment]
@sankotm 

Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.Please Check [PayPal Community]( https://www.paypal-community.com) and  [MTS](https://paypal.com/mts) 

Thanks!
