### ISSUE TITLE
Why Webhook so slowly? 

### ISSUE THREAD

**Issue by NonCamp** [paypal/PayPal-Java-SDK#370]
Hi.I use **webhook** to get the payment result message, but it takes a long time (about 30 seconds, sometimes longer). Interestingly, IPN seems to be faster.I wonder why? Is it related to countries and regions?(i'm in China)

**Comment by Trupti21** [comment]
@NonCamp ,
Can you please share the logs?

Thanks

**Comment by prakash-gangadharan** [comment]
@NonCamp, feel free to reopen, if this is still an issue.
