### ISSUE TITLE
PayPal-Java-SDK 1.14 vs 2.0.0-rc1

### ISSUE THREAD

**Issue by kbachl** [paypal/PayPal-Java-SDK#371]
Hi,

on https://github.com/paypal/PayPal-Java-SDK its advised as:

> 2.0 Release Candidate!
> We're releasing a brand new version of our SDK! 2.0 is currently at release candidate status, and represents a full refactor, with the goal of making all of our APIs extremely easy to use. 2.0 includes all of the existing APIs (except payouts), and includes the new Orders API (disputes and Marketplace coming soon). Check out the FAQ and migration guide, and let us know if you have any suggestions or issues!

while on https://github.com/paypal/PayPal-Java-SDK/tree/2.0-beta
it says:

> NOTE: This API is still in beta, is subject to change, and should not be used in production.

So: where is this project now at? And why is the last release from February 9th? - thats over a half a year;

Im asking as I plan to integrate an express checkout button into our shop and currently unsure what api version to use....

**Comment by thberger** [comment]
Hello PayPal, any updates on this topic?

**Comment by RayBB** [comment]
Also wondering about this.

**Comment by FieserKiller** [comment]
bump for visibility

**Comment by Quiark** [comment]
the answer is clear, the v2 doesn't even work

**Comment by Trupti21** [comment]
@kbachl,
Latest version is 1.14. 
v2.0 beta version has released.
[You can get further information here- ](https://developer.paypal.com/docs/api/quickstart/#) 
Thanks

**Comment by FieserKiller** [comment]
PayPal bought Braintree in the meantime and pushes everyone to use Braintree sdk for nontrivial backend stuff. 
We did that and it works fine so far.

**Comment by kbachl** [comment]
@FieserKiller but doenst this add costs to the transactions if using braintree?

**Comment by kbachl** [comment]
@FieserKiller do you might give us some more details as I dont really understand yet what part of braintree sdk you are using? With or without their checkout UI?  - I see a lot of options there:
https://developers.braintreepayments.com/
and this: https://articles.braintreepayments.com/get-started/overview#braintree-direct tells me you need to use their  https://www.braintreepayments.com/de/products/braintree-direct for paypal?

**Comment by FieserKiller** [comment]
We use this java library for server side: https://developers.braintreepayments.com/start/hello-server/java
and the braintree js lib for web clients: https://developers.braintreepayments.com/start/hello-client/javascript/v2
from clients pov its all paypal, he does not see any braintree references. Authorisation, sales, etc still go through braintree servers to paypal. however, you get your daily reports old school from paypal directly (sftp) and are notified about events like chargebacks etc by paypal as well (webhooks).

**Comment by jeffcjohnson** [comment]
@FieserKiller When you use the PayPal webhooks, how are you parsing the JSON?  I think I figured out a solution but the latest version, v1.14.0, is missing Dispute.java.   I see the v2.0.0-rc1 has Dispute.java but it seems to be abandoned like everything else in this project.

So if I switch to the Braintree SDK, am I still stuck using the abandonware PayPal libs?
