### ISSUE TITLE
Null Pointer Error when attempting PayPal payment

### ISSUE THREAD

**Issue by jeffersonbarbee** [paypal/PayPal-Java-SDK#372]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 

### Issue description

I am using the Braintree payment gateway and adding a tokenized PayPal account to the Tract billing system.  I am able to successfully add a 'pre-approved' PayPal payment method to the account, but when I attempt to make a payment with this payment method I am receiving the following information from our internal error log system.

I am not familiar with the error and what might be causing the internal error/null pointer error.  Hoping someone on here is more familiar with this issue, or may have seen a similar error before, and be able to offer advice on what can be changed to correct the issue.  

Thank you!

{code}
org.apache.wicket.RequestCycle\|null\|java.lang.NullPointerException: null              at com.transverse.bleep.wicket.billingaccount.payment.ListPaymentPanel$ManualPaymentProcessor.onFinish(ListPaymentPanel.java:383)              at   com.transverse.bleep.wicket.common.component.EmbeddedPanel$3.onSubmit(EmbeddedPanel.java:194)              at   org.apache.wicket.ajax.markup.html.form.AjaxButton$1.onSubmit(AjaxButton.java:101)              at   org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:156)              at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:177)              at   org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:312)              at   org.apache.wicket.request.target.component.listener.BehaviorRequestTarget.processEvents(BehaviorRequestTarget.java:157)              at   org.apache.wicket.request.AbstractRequestCycleProcessor.processEvents(AbstractRequestCycleProcessor.java:92)              at   com.transverse.bleep.wicket.app.BleepApplication$2.processEvents(BleepApplication.java:154)              at org.apache.wicket.RequestCycle.processEventsAndRespond(RequestCycle.java:1279)              at org.apache.wicket.RequestCycle.step(RequestCycle.java:1358)              at org.apache.wicket.RequestCycle.steps(RequestCycle.java:1465)              at org.apache.wicket.RequestCycle.request(RequestCycle.java:545)              at org.apache.wicket.protocol.http.WicketFilter.doGet(WicketFilter.java:486)              at   org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:319)              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)              at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)              at   com.transverse.bleep.servlet.filter.MDCUserFilter.doFilter(MDCUserFilter.java:77)              at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)              at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)              at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311)              at   org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)              at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)              at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)              at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)              at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)              at com.transverse.tract.servlet.filter.tenant.TenantContextFilter.doFilter(TenantContextFilter.java:68)              at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)              at   org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:101)              at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)              at   org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)              at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)              at   org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)              at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)              at   org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:182)              at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)              at   org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:65)              at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)              at   org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)              at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)              at   org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)              at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)              at   org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)              at   org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)              at   org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)              at   org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)              at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)              at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)              at   org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:180)              at   org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)              at   org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)              at   org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)              at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)              at   org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)              at   org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)              at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)              at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)              at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:683)              at   org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)              at   org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)              at   org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082)              at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623)              at   org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)              at   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)              at   org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)              at java.lang.Thread.run(Thread.java:748)   \|###
{code}

-- | --

**Comment by jeffersonbarbee** [comment]
@gbramwell @burnto @bluk @jeffharrell  Hi all, I filed this issue yesterday.  Is there any chance I could get a pair of eyes on this to see if I'm missing something obvious?  Thank you!

**Comment by Trupti21** [comment]
@jeffersonbarbee ,
Can you please provide your code snippet ?
or you can have a look at [this code](https://github.com/Trupti21/Java-SDK-Payment-Demo).
It is working fine for direct Payment as well as guest checkout.

Thanks
