### ISSUE TITLE
Client Authentication failed

### ISSUE THREAD

**Issue by Abhishekoodles1** [paypal/PayPal-Java-SDK#373]
After done testing with test credentials. I have created a merchant account and generate client id and signature in my account under NVP/SOAP API integration (Classic).  But when I am doing transaction error is coming 
{"error":"invalid_client","error_description":"Client Authentication failed"}.  I checked my client id and the secret is correct.  I have not much idea about an actual merchant account. Please help

**Comment by Trupti21** [comment]
@Abhishekoodles1 ,
Create new secret Id and try.
when you click on show link in API credentials in your created App.
below there is a button called generate new secret.

Thanks

**Comment by Trupti21** [comment]
@Abhishekoodles1 ,

Please try the above solution. If still you have query. Please reopen the issue.

Thanks
