### ISSUE TITLE
Set payee of billing plan

### ISSUE THREAD

**Issue by davidvuletas** [paypal/PayPal-Java-SDK#374]
### General information

* SDK/Library version: Maven latest
* Environment: Sandbox

### Issue description
Hello,

I have one question about billing plans.
How can I set Payee for some billing plan,  because in my application i have different payee and i need to set where payment will be received?

Thanks

**Comment by Trupti21** [comment]
@davidvuletas ,
As mentioned in developers Docs. 
[The Billing Agreements API does not support the payee object.](https://developer.paypal.com/docs/api/payments.billing-agreements/v1/).

Thanks
