### ISSUE TITLE
Google Appengine  I get java.net.UnknownHostException: api.sandbox.paypal.com 

### ISSUE THREAD

**Issue by gandalfhv** [paypal/PayPal-Java-SDK#375]
### General information

* SDK/Library version: 1.14.0
* Environment: Google Appengine
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: Java 1.8.0_112-google-v7 on LInux 2.6

### Issue description
When trying to get the authorization token in my servlet, I get
java.net.UnknownHostException: api.sandbox.paypal.com 

context.usingGoogleAppEngine (true) does not work, I've seen the sources and  the class GoogleAppEngineHttpConnection is never called, force its use and it still does not work

**Comment by Trupti21** [comment]
@gandalfhv ,
Have you created an account in [Paypal](https://developer.paypal.com/developer)??
as instructed [here](https://developer.paypal.com/docs/api/overview/#). 
If yes then can you please share your code snippets.

Thanks

**Comment by Trupti21** [comment]
@gandalfhv ,

I am closing the issue. Please reopen if you have any query.
Thanks
