### ISSUE TITLE
PayPal Sync API Decoding issues (Malformed json - missing pair delimiter)

### ISSUE THREAD

**Issue by flo-m** [paypal/PayPal-Java-SDK#376]
### General information

* SDK/Library version: 2.0 beta
* Environment: Production
* Language, language version, and OS: Java 1.8 

### Issue description

when using the PayPal Sync API with JAVA (2.0-beta REST API), the result can throw an error like:
Malformed json - missing pair delimiter

This happens especially if your transaction_details, e.g. item_name has a double quote inside .
Example: 
"item_name":"Gartenschlauch Wasserschlauch Schlauch 1\" 1/2\" 3/4\" Zoll 20m 30m 50m 3-Lagig [Blau,20m,3/4\"]",

gets parsed and decoded as 
key : Gartenschlauch Wasserschlauch Schlauch 1\
hence it fails with the next steps, since it cannot find a closing bracket.

Any solutions for this issue?

**Comment by sucithrashanu** [comment]
@flo-m 



Currently we do not have any stipulated timeline for the v2.0.0 release, but it may be available in near future.Please Check [PayPal Community ](https://www.paypal-community.com) and  [MTS](https://paypal.com/mts) 

Thanks!
