### ISSUE TITLE
Identity-API changes

### ISSUE THREAD

**Issue by MiladSadinam** [paypal/PayPal-Java-SDK#377]
* SDK/Library version: 1.14.0

I hope this is the correct place to post this. I have received an email from Paypal that the Identity-API is being changed. This is the content (German unfortunately): 

`PayPal ändert die Identity-API, eine API, die Sie im Rahmen Ihrer Integration mit "Login mit PayPal" (jetzt als "Mit PayPal verbinden" bezeichnet) verwenden. Abhängig davon, wie Ihre Integration die API nutzt, müssen Sie möglicherweise bis 4. März 2019 Änderungen vornehmen, um diesen Dienst weiterhin verwenden zu können. Als Teil dieser Änderung werden einige Werte nicht mehr an die API zurückgegeben. Sie können unsere API-Dokumentation verwenden, um die erforderlichen Änderungen an Ihrer Integration vorzunehmen.`

The email is not very clear about the changes. But, checking the documentation the UserInfo object seems now to have an "emails" array. Currently, it is just a string property. The changes are live from 4th of March. Is the sdk being updated? Will it only be in the new  2.0 Release Candidate? I am currently using version 1.14.

**Comment by Trupti21** [comment]
@MiladSadinam ,
Yes this change is applicable on 2.0. 
email is still String in 1.14.

Thanks
