### ISSUE TITLE
Payouts support after SDK version 2.0

### ISSUE THREAD

**Issue by oshamahue** [paypal/PayPal-Java-SDK#378]
In the README file it is mentioned that payouts won't be supported. We use payouts extensively and Can you share more info on the future plans regarding to the  payouts feature (api support, deprecation, termination)?

**Comment by Trupti21** [comment]
@oshamahue ,
For existing users support will be provided. for more information [please check with your account manager](https://developer.paypal.com/docs/commerce-platform/v1/payouts/?mark=payouts).

**Comment by sucithrashanu** [comment]
@oshamahue 

Please check the [PayPal Community ](https://www.paypal-community.com) and  [MTS](https://paypal.com/mts)

Thanks
