### ISSUE TITLE
New subscription api implemntation

### ISSUE THREAD

**Issue by makahleh** [paypal/PayPal-Java-SDK#382]
Hi,
I want to integrate with paypal for recurring payments project, i noticed in the API docs the following  :

The /v1/billing-plans endpoints are deprecated. Use the /v1/billing/subscriptions endpoints instead.

Is there any Java implementation for the new endpoints ??
Is it recommended to go with this library as a new project ??

Thanks

**Comment by lepidotteri** [comment]
No it's not, and it's beyond absurd that PayPal would not promptly update its (already small) set of officially supported SDKs accordingly to the introduction of new APIs

**Comment by makahleh** [comment]
@lepidotteri 
So you see that i can integrate safely with the existing SDK.

Thanks.

**Comment by lepidotteri** [comment]
No, the old APIs have been deprecated (according to PayPal) and this SDK only supports those very same APIs (old Billing Plans & Agreements API)

**Comment by makahleh** [comment]
@lepidotteri 
Aha, i think it will be wasting time to write the calls with Java, can i integrate with Braintree to solve my issue ?

**Comment by yingdi1** [comment]
I am having the same question. What is the plan here

**Comment by Quiark** [comment]
and don't waste your time looking at the announced v2 of this SDK because there is nothing there

and note that the new subscription API is buggy - the subscription plan details shown to user is different from what they'll be charged

**Comment by Trupti21** [comment]
@makahleh ,
@lepidotteri  answered your question.
I am closing the ticket. If you have any query please reopen the issue.

Thanks

**Comment by makahleh** [comment]
@Trupti21 

I can't see the answer is satisfying  .. you are saying that this SDK supports deprecated APIs, so what is the goal of providing the SDK?

Is there any plan to support the new subscription APIs?

**Comment by prakash-gangadharan** [comment]
@makahleh REST sdks still using below `Billing Plans API` which is  deprecated.
https://developer.paypal.com/docs/api/payments.billing-plans/v1/#billing-plans

**Deprecation notice**:

-  The /v1/billing-plans endpoints are deprecated. 
- Use the /v1/billing/subscriptions endpoints instead. 
- For details, see [Subscriptions Integration](https://developer.paypal.com/docs/subscriptions/integrate/).

Currently we do not have any stipulated timeline to replace the deprecated endpoints with the newer one but it may be available in near future.
