### ISSUE TITLE
getpayment command is failure.

### ISSUE THREAD

**Issue by zhaoxinhu** [paypal/PayPal-Java-SDK#385]
COMMOND:
curl --verbose --request GET 'https://api.sandbox.paypal.com/v1/payments/payment/PAY-0XL713371A312273YKE2GCNI' \
  --header "Authorization:Bearer A21AAH2wH1Ykz-JP5x3VxuNzV9qyvqTZF4xBgkd32fZKr3FuiKFwvD0e3q0wbp7J0eoEZuKa6QNV5cM2w_5U_gT1bY90l-wmQ" \
  --header "User-Agent:PayPalSDK/  (v=1.8.0_201-2-redhat; vendor=Oracle Corporation; bit=64; os=Windows_10 10.0)" \
  --header "PayPal-Request-Id:1cf84d52-d85e-4d7e-ab8f-d5f6e71b7eea" \
  --header "Content-Type:application/json" \
  --data ''
RESPONSE:
401       Error response: {"name":"PERMISSION_DENIED","message":"Permission denied.","information_link":"https://developer.paypal.com/docs/api/payme
nts/#errors","debug_id":"7d29356c27420"}

**Comment by prakash-gangadharan** [comment]
Hi @zhaoxinhu , I just executed the below CURL command to call getpayment API and it is working fine for me without any error.

```ruby
curl -v GET 'https://api.sandbox.paypal.com/v1/payments/payment/PAYID-LWAINGQ46J64684TJ571415R' \
-H "Authorization: Bearer A21AAGgYWlOocAdU9YTffDC0Vtk011GFMgKPjeYRCJeACu7PdfooLgKmoMkNNZk63ODgKLfEFns8f2-tmRaYCN3O-bWsgLYIA" \
-H "User-Agent: PayPalSDK/ (v=1.8.0_201-2-redhat; vendor=Oracle Corporation; bit=64; os=Windows_10 10.0)" \
-H "PayPal-Request-Id: 1cf84d52-d85e-4d7e-ab8f-d5f6e71b7eea" \
-H "Content-Type: application/json"
```

**Paypal-Debug-Id** for success get call: 8c5c812882444


```json
{
  "name": "PERMISSION_DENIED",
  "message": "Permissiondenied.",
  "information_link": "https://developer.paypal.com/docs/api/payments/#errors",
  "debug_id": "d73607e356848"
}
```

The above **PERMISSION_DENIED** error occurs when merchant doesn't grant permission to the API caller account. Make sure that you are using the correct access token of the merchant who really created the payment. If this is still an issue help us with the recent Paypal-Debug-Id to check further.

Thanks!
