### ISSUE TITLE
How to download statement in excel format using Java language

### ISSUE THREAD

**Issue by youxiu326** [paypal/PayPal-Java-SDK#386]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by Trupti21** [comment]
@youxiu326 ,
Can you please provide more context. What statement you want to download?

Thanks

**Comment by youxiu326** [comment]
My problem has been solved, thank you！




------------------ 原始邮件 ------------------
发件人: "Trupti21"<notifications@github.com>;
发送时间: 2019年10月10日(星期四) 晚上7:35
收件人: "paypal/PayPal-Java-SDK"<PayPal-Java-SDK@noreply.github.com>;
抄送: "第二次"<youxiu326@foxmail.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [paypal/PayPal-Java-SDK] How to download statement in excelformat using Java language (#386)




@youxiu326 ,
 Can you please provide more context. What statement you want to download?
 
Thanks
