### ISSUE TITLE
Links for Self, Approval URL, and Execute Do Not Work

### ISSUE THREAD

**Issue by PulseBeat02** [paypal/PayPal-Java-SDK#387]
### General information

* SDK/Library version: 1.14.0

* Environment: Sandbox

* `PayPal-Debug-ID` values: Using the url's will give this error: {"name":"AUTHENTICATION_FAILURE","message":"Authentication failed due to invalid authentication credentials or a missing Authorization header.","links":[{"href":"https://developer.paypal.com/docs/api/overview/#error","rel":"information_link"}]}

* Java 1.8.0_101-b13 on Windows 10 Pro and MacBook Pro

### Issue description

I followed all the instructions and used the documentary to make a payment, however, I noticed some errors when making the payment. The payment was successfully made according to the JSON file that is outputted:

```
{
  "id": "PAYID-LUGVKPA4N187973XG698712U",
  "intent": "authorize",
  "payer": {
    "payment_method": "paypal"
  },
  "transactions": [
    {
      "related_resources": [],
      "amount": {
        "currency": "USD",
        "total": "1.20",
        "details": {
          "subtotal": "0.00",
          "shipping": "0.00",
          "tax": "0.00"
        }
      },
      "description": "Shoe Raffle Ticket by Coppers Odds"
    }
  ],
  "state": "created",
  "create_time": "2019-06-21T22:07:55Z",
  "links": [
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAYID-LUGVKPA4N187973XG698712U",
      "rel": "self",
      "method": "GET"
    },
    {
      "href": "https://www.sandbox.paypal.com/cgi-bin/webscr?cmd\u003d_express-checkout\u0026token\u003dEC-6SL80260CD7884239",
      "rel": "approval_url",
      "method": "REDIRECT"
    },
    {
      "href": "https://api.sandbox.paypal.com/v1/payments/payment/PAYID-LUGVKPA4N187973XG698712U/execute",
      "rel": "execute",
      "method": "POST"
    }
  ]
}
```

However, pasting the get, approval_url, or execute links will not lead to a payment, and instead just a text saying the following:

`{"name":"AUTHENTICATION_FAILURE","message":"Authentication failed due to invalid authentication credentials or a missing Authorization header.","links":[{"href":"https://developer.paypal.com/docs/api/overview/#error","rel":"information_link"}]}
`

Does anyone know if the paypal servers are down, causing this error to happen? Otherwise, I don't get the problem I am having here.

**Comment by prakash-gangadharan** [comment]
Hi @PulseBeat02 ,  is this still an issue, if yes can you help us with the recent ayPal-Debug-ID to check this further.

Thanks!

**Comment by PulseBeat02** [comment]
@prakash-gangadharan I'm here to help. I believe the issue still exists. And also, what is the ayPal-Debug-ID?

**Comment by prakash-gangadharan** [comment]
`PayPal-Debug-ID` is nothing but the debug_id which is sent along with the error message
for example:
 {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"############"}"
It would be helpful for us to debug the issue using paypal logs.

**Comment by PulseBeat02** [comment]
There is no debug id. 

```
{"name":"AUTHENTICATION_FAILURE","message":"Authentication failed due to invalid authentication credentials or a missing Authorization header.","links":[{"href":"https://developer.paypal.com/docs/api/overview/#error","rel":"information_link"}]}
```

**Comment by prakash-gangadharan** [comment]
Hi @PulseBeat02, can you try the same request using the CURL command to check whether are you receiving any PayPal-Debug-ID for the reported error.

**Comment by PulseBeat02** [comment]
Now I am getting a different issue. It said that the currency format is incorrect:

`response-code: 400	details: name: VALIDATION_ERROR	message: Invalid request - see details	details: [{
  "field": "transactions.amount.details",
  "issue": "Currency amount must be non-negative number, may optionally contain exactly 2 decimal places separated by \u0027.\u0027, optional thousands separator \u0027,\u0027, limited to 7 digits before the decimal point and currency which is a valid ISO Currency Code"
}]`

It seems that the currency amount is incorrect, but I set the price to be "1.20". Here is the debug id: 17113fb87cc5c

**Comment by prakash-gangadharan** [comment]
Hi @PulseBeat02, It looks like you are getting the above error since you passing the special character `$` along with the amount. 
Screenshot:
![image](https://user-images.githubusercontent.com/13796434/66289820-5743b080-e8fb-11e9-8b1e-10b035f6f9dc.png)
Can you try create the payment by removing the same?
You can find the sample request here :
https://developer.paypal.com/docs/api/payments/v1/#payment_create

**Comment by PulseBeat02** [comment]
Hi, @prakash-gangadharan Thank you for telling me. I will take a look at my code and fix this issue as quickly as possible. Then, I will report back to you if the original issue still persists.
