### ISSUE TITLE
Question: Does Transaction class hold transaction ID and execution timestamp?

### ISSUE THREAD

**Issue by AndreyLebedenko** [paypal/PayPal-Java-SDK#388]
### General information

* SDK/Library version: 1.0.1
* Environment: Sandbox
* Language, language version, and OS: Java 1.8.0_201 on Mac OS

### Issue description

Say I have a list of transactions for a period of time. How do I get ID of each transaction and their time stamp?

Thanks.

**Comment by prakash-gangadharan** [comment]
@AndreyLebedenko you can make use of [PayPal Sync API](https://developer.paypal.com/docs/api/sync/v1/)  to get the history of transactions for a PayPal account.

**Comment by sucithrashanu** [comment]
@AndreyLebedenko 

Please check the [PayPal Community ](https://www.paypal-community.com) and  [MTS](https://paypal.com/mts)

Thanks
