### ISSUE TITLE
InvoiceSample has wrong developer docs links, i.e the links mentioned in the InvoiceSample java file is not working.

### ISSUE THREAD

**Issue by MuthuRamaKrishnan-M** [paypal/PayPal-Java-SDK#389]
### General information

* SDK/Library version: v1.14.0
* Environment: Sandbox 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: 1.8.0_211 on windows 10 enterprise

### Issue description

InvoiceSample java file has wrong developer docs links, i.e the links mentioned in it  is not working or not redirecting to the correct documentation page.

**Comment by prakash-gangadharan** [comment]
PR Raised : https://github.com/paypal/PayPal-Java-SDK/pull/393
