### ISSUE TITLE
Invoice creation is broken

### ISSUE THREAD

**Issue by tazio** [paypal/PayPal-Java-SDK#39]
When I create an Invoice I have this error:
18:00:33.009 [main] ERROR c.l.c.cmw.utils.PaypalPaymentGateway - Paypal error: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 307

This because in the Address class, included in MerchantInfo class, in Invoice I have the following "phone":

	/**
	 * Phone number in E.123 format.
	 */
	private String phone; 

while paypal's sandbox returns:
... "address":{"phone":{"country_code":"39","national_number":"05021313"}}} ...

**Comment by jaypatel512** [comment]
Hey All,

The temporary fix was made in Java SDK https://github.com/paypal/PayPal-Java-SDK/commit/95a873b40fb715bfb342da2ca660b0970c2a298f to allow separate invoicing address and address to solve this issue. I am closing this issue for now. Please re-open if issue still exists.
