### ISSUE TITLE
2 factor Authentication

### ISSUE THREAD

**Issue by noyanebi** [paypal/PayPal-Java-SDK#391]
hi,
i have problem with 2 factor Authentication.
after i enable 2fa in my paypal panel i am not enable to get sms verification in android paypal . please clarify me about my problem

**Comment by prakash-gangadharan** [comment]
Hi @noyanebi , did you integrated with PayPal-Java-SDK, can you help me with the account you are using.

Thanks!

**Comment by noyanebi** [comment]
Hi yes , actually I follow this web site

http://www.theappguruz.com/blog/integrate-paypal-in-android

**Comment by prakash-gangadharan** [comment]
Can you help me with the primary email of the account for which you enabled the 2fa?

**Comment by noyanebi** [comment]
After enabling 2fa , then not work
I have shifted to webview solution

**Comment by prakash-gangadharan** [comment]
@noyanebi, we apologize for the inconvenience caused. And you are not integrating with the PayPal-Java-SDK anymore?

**Comment by noyanebi** [comment]
As I mentioned earlier I have implement with sdk first , but after face
with 2fa problem I changed to webview paypal
