### ISSUE TITLE
Error while running Rest API Sample's credit card save & retrieve examples under Vault section

### ISSUE THREAD

**Issue by joanson** [paypal/PayPal-Java-SDK#394]
### General information

* SDK/Library version: v1.14.0 
* Environment: Sandbox
* `PayPal-Debug-ID` values: e08253eca444e
* Language, language version, and OS: Java 1.8.0_211 on windows

### Issue description
Rest API Sample's credit card save and retrieve examples under Vault section gives out Error responses.

###  Credit Card - Save

Response code: 400 Error response:
```
{
  "name": "VALIDATION_ERROR",
  "message": "Invalid request - see details",
  "debug_id": "e08253eca444e",
  "information_link": "https://developer.paypal.com/docs/api/vault/#errors",
  "details": [
    {
      "field": "expire_month, expire_year",
      "location": "body",
      "issue": "Invalid expiration (cannot be in the past)"
    }
  ],
  "links": []
}
```

### Credit Card - Retrieve

Response code: 404 Error response
```
{
  "name": "INVALID_RESOURCE_ID",
  "message": "The requested resource ID was not found",
  "debug_id": "43ac72c9f2da0",
  "information_link": "https://developer.paypal.com/docs/api/vault/#errors",
  "links": []
}
```

**Comment by joanson** [comment]
###  Credit Card - Save
![CreditCard_Save](https://user-images.githubusercontent.com/43883352/64344016-3857b300-d00b-11e9-9e16-5ad57d2f548b.PNG)

### Credit Card - Retrieve
![CreditCard_Retrieve](https://user-images.githubusercontent.com/43883352/64344158-8967a700-d00b-11e9-8f64-6bdcc69f08d9.PNG)

**Comment by prakash-gangadharan** [comment]
PR Raised : https://github.com/paypal/PayPal-Java-SDK/pull/396
