### ISSUE TITLE
Rest API Sample's Validate Webhook example under Payments section gives out Error responses

### ISSUE THREAD

**Issue by joanson** [paypal/PayPal-Java-SDK#395]
### General information

* SDK/Library version: v1.14.0 
* Environment: Sandbox
* `PayPal-Debug-ID` values: NA
* Language, language version, and OS: Java 1.8.0_211 on windows

###  Validate Webhook
source : /rest-api-sample/source/payments/servlet/ValidateWebhookServlet.html

Webhook Validated: (Failed)
```
Response Object
 PAYPAL-CERT-URL cannot be null
```
![image](https://user-images.githubusercontent.com/13796434/64373903-5c81b700-d040-11e9-9020-e8d71ed7d615.png)

**Comment by prakash-gangadharan** [comment]
PR Raised : https://github.com/paypal/PayPal-Java-SDK/pull/396
