### ISSUE TITLE
pay servlet returns nul value for authentication

### ISSUE THREAD

**Issue by lakshmiprabha1993** [paypal/PayPal-Java-SDK#397]
http://localhost:8080/paypal/payServlet?mail=mail&amount=7&fundingType=BALANCE

 

The above api is returning the nul value for the  if (resp.getResponseEnvelope().getAck().toString()
.equalsIgnoreCase("SUCCESS")) line in payservlet 

 

Note : Access token is given an all credentials for configuration are given in configuration class

 

please reply if any to be added to solve the issue.

**Comment by prakash-gangadharan** [comment]
Hi @lakshmiprabha1993 , can you help me with the code snippet to check this further or do you have any supporting PayPal-Debug-IDs to dig further?

**Comment by prakash-gangadharan** [comment]
Hi @lakshmiprabha1993 , if this not an integration issue with PayPal-Java-SDK, refer the below link for merchant technical support.
https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723

Thanks!
