### ISSUE TITLE
payment using sandbox account in java 

### ISSUE THREAD

**Issue by lakshmiprabha1993** [paypal/PayPal-Java-SDK#398]
### General information

* SDK/Library version: 
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS:

**Comment by prakash-gangadharan** [comment]
@lakshmiprabha1993 , can you please be precise on your question and what is your exact ask here?

**Comment by lakshmiprabha1993** [comment]
Thank you Prakash.. Actually I need to make payment using sandbox account and integrate in my java application .. I have got the access token using the cliendId and clientSecret .. Now When I try to make payment using the api  from https://github.com/paypal/PayPal-Java-SDK/  using payservlet  I have got the error :

{"accessToken":null,"tokenSecret":null,"lastRequest":null,"lastResponse":null}
Sep 16, 2019 9:21:43 AM com.paypal.core.LoggingManager log
INFO: requestEnvelope.errorLanguage=en_IND&receiverList.receiver(0).amount=7.0&receiverList.receiver(0).email=lakshmiprabha.t%40test.com&reverseAllParallelPaymentsOnError=false&fundingConstraint.allowedFundingType.fundingTypeInfo(0).fundingType=BALANCE&
java.net.SocketException: Connection reset




Please help

**Comment by prakash-gangadharan** [comment]
@lakshmiprabha1993 , have you tried with the below step by step procedures here in the below link?
https://developer.paypal.com/docs/api/quickstart/payments 
and can you help me with your code snippet which your trying to make a payment using SDK.

Thanks!

**Comment by lakshmiprabha1993** [comment]
https://developer.paypal.com/docs/integration/direct/payments/paypal-payments/#create-paypal-payment link I have used to integrate my application .. Please let me know which link I should use to integrate with java

**Comment by prakash-gangadharan** [comment]
* Is this new integration and are you trying to integrate with the JAVA SDK ? if yes refer https://developer.paypal.com/docs/api/quickstart 
* https://developer.paypal.com/docs/integration/direct/payments/paypal-payments , this link is the basic integration guide which was explained using CURL commands.

**Comment by lakshmiprabha1993** [comment]
Can I use the given link https://developer.paypal.com/docs/integration/direct/payments/paypal-payments     in spring mvc java package . We are not using android adk package.. Can I integrate with jersey RSET or servlet

**Comment by prakash-gangadharan** [comment]
Hi @lakshmiprabha1993 , if this not an integration issue with PayPal-Java-SDK, refer the below link for merchant technical support.
https://www.paypal.com/in/smarthelp/article/how-do-i-get-merchant-technical-support,-such-as-for-paypal-product-integrations,-apis-or-sandbox-testing-faq3723

Thanks!

**Comment by lakshmiprabha1993** [comment]
The java coding issue comes when I try to integrate.. I need the **developer technical suport.**.But the link mentioned is for a **merchant** . 


Thanks

**Comment by prakash-gangadharan** [comment]
Please visit [Merchant Technical Support](https://www.paypal-techsupport.com/app/) and submit your question.

Thanks!
