### ISSUE TITLE
Unable to import into Eclipse

### ISSUE THREAD

**Issue by Jesterise** [paypal/PayPal-Java-SDK#399]
* SDK/Library version: 1.1.4 /2.0.0
* Environment: Sandbox
* `PayPal-Debug-ID` values: NA
* Language, language version, and OS: JDK 11.0.4 on Windows 10

### Issue description

I am currently facing an issue while trying to import this SDK into Eclipse 4.13.0 using BuildShip 3.1.2. For both SDK versions, I am faced with the following error. 
"Could not create an instance of Tooling API implementation using the specified Gradle distribution 'https://services.gradle.org/distributions/gradle-2.13-all.zip'.
Could not create service of type FileWatcherFactory using GlobalScopeServices.createFileWatcherFactory().
Could not determine java version from '11.0.4'."

Could really use some help

**Comment by prakash-gangadharan** [comment]
@Jesterise , so you are using java 11.0.4 and are you trying to do a local setup or trying to import the paypal java sdk into your eclipse project?

**Comment by Jesterise** [comment]
> @Jesterise , so you are using java 11.0.4 and are you trying to do a local setup or trying to import the paypal java sdk into your eclipse project?

hi @prakash-gangadharan im currently trying to do a local setup to test the workings of the sdk first before integrating with my current project.

**Comment by prakash-gangadharan** [comment]
@Jesterise, does your project running on jdk 11.0.4?

**Comment by Jesterise** [comment]
actually on jdk 11.0.2. currently on another computer that runs jdk 11.0.4

**Comment by prakash-gangadharan** [comment]
@Jesterise, despite the fact that, the [Prerequisites](https://github.com/paypal/PayPal-Java-SDK#prerequisites) says **PayPal-Java-SDK** requires Java JDK 6 or higher
I could see .[travis.yml](https://github.com/paypal/PayPal-Java-SDK/blob/master/.travis.yml) has jdk as oraclejdk8.

We need to the check the compatibility with JDK 11.0.2 and 11.0.4

**Comment by Jesterise** [comment]
@prakash-gangadharan Yes it is. Thanks for you help.
