### ISSUE TITLE
Wrong amount: Transaction amount details (subtotal, tax, shipping) must add up to specified amount total

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [paypal/PayPal-Java-SDK#404]
### General information

* SDK/Library version: 
name     : paypal/rest-api-sdk-php
descrip. : PayPal's PHP SDK for REST APIs
keywords : payments, paypal, rest, sdk
versions : * 1.14.0
type     : library
license  : Apache License 2.0 (Apache-2.0) (OSI approved) https://spdx.org/licenses/Apache-2.0.html#licenseText
source   : [git] https://github.com/paypal/PayPal-PHP-SDK.git 72e2f2466975bf128a31e02b15110180f059fc04
dist     : [zip] https://api.github.com/repos/paypal/PayPal-PHP-SDK/zipball/72e2f2466975bf128a31e02b15110180f059fc04 72e2f2466975bf128a31e02b15110180f059fc04
path     : /laravel/justitalianwine_ecommerce/vendor/paypal/rest-api-sdk-php
names    : paypal/rest-api-sdk-php

* Environment: sandbox
* `PayPal-Debug-ID` values:91d27597e954
* Language, language version, and OS: PHP 7.2.24 on apache (ubuntu)

### Issue description
My payment is this:
```json
{
   "intent":"sale",
   "payer":{
      "payment_method":"paypal"
   },
   "redirect_urls":{
      "return_url":"http://website.lab/payment/paypal/success",
      "cancel_url":"http://website.lab/payment/paypal/cancel"
   },
   "transactions":[
      {
         "amount":{
            "currency":"EUR",
            "total":"223",
            "details":{
               "shipping":"0",
               "subtotal":"273"
            }
         },
         "description":"...",
         "item_list":{
            "items":[
               {
                  "name":"product 8",
                  "currency":"EUR",
                  "quantity":21,
                  "sku":"w9",
                  "price":"13.00"
               }
            ],
            "shipping_address":{
               "city":"...",
               "postal_code":"...",
               "country_code":"...",
               "recipient_name":"...",
               "line1":"..."
            }
         }
      }
   ]
}
```
and i'm getting
```
400{"name":"VALIDATION_ERROR","details":[{"field":"transactions[0].amount","issue":"Transaction amount details (subtotal, tax, shipping) must add up to specified amount total"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"91d27597e954"}
```

Now, i can see that are missing 50€ from total to subtotal, but in this order (on my website) i ave a coupon associated to it, and so there is a 50€ discount, and i not able to find anything on the API to specify this discount.. how can i handle it?

**Comment by prakash-gangadharan** [comment]
Hi @AlbertoSinigaglia  refer this comment : https://github.com/paypal/PayPal-PHP-SDK/issues/908#issuecomment-320291229
Try adding  a line item with a negative amount.

Similar issue : https://github.com/paypal/PayPal-PHP-SDK/issues/908
