### ISSUE TITLE
Resource 'sdk_config.properties' could not be found

### ISSUE THREAD

**Issue by kunalransing** [paypal/PayPal-Java-SDK#64]
Issue : We are able to set config file from custom location....when we try to create instance for OAuthTokenCredential providing clientid & clientsecret..it gives exception "Resource 'sdk_config.properties' could not be found"

Description:
//below code init resource properly
InputStream is = MyPaypalAuth.class.getResourceAsStream("/myresource/sdk_config.properties");
PayPalResource.initConfig(is);

//below line raise exception
String accessToken = new OAuthTokenCredential(clientID, clientSecret).getAccessToken();

Exception:
java.io.IOException: Resource 'sdk_config.properties' could not be found
	com.paypal.base.util.ResourceLoader.getInputStream(ResourceLoader.java:50)
	com.paypal.base.ConfigManager.<init>(ConfigManager.java:85)
	com.paypal.base.ConfigManager.getInstance(ConfigManager.java:102)
	com.paypal.base.rest.OAuthTokenCredential.<init>(OAuthTokenCredential.java:97)

**Comment by juwlee** [comment]
@kunalransing do you see the config file in the path you specified?

**Comment by kunalransing** [comment]
Yes. I can see file & yes it read correctly & inputstream correctly pass to PayPalResource.initConfig().

Reason: I guess reason is when we call below method from OAuthTokenCredential.java. Internally it call ConfigManager.getInstance() which try to load default sdk_config.properties using below code
ResourceLoader resourceLoader = new ResourceLoader(
				Constants.DEFAULT_CONFIGURATION_FILE);
Above code raise exception. Since we init file using custom location then why we try to load default file ?
	/**
	 * @param clientID
	 *            Client ID for the OAuth
	 * @param clientSecret
	 *            Client Secret for OAuth
	 */
	public OAuthTokenCredential(String clientID, String clientSecret) {
		super();
		this.clientID = clientID;
		this.clientSecret = clientSecret;
		this.configurationMap = SDKUtil.combineDefaultMap(ConfigManager
				.getInstance().getConfigurationMap());
		this.sdkVersion = new SDKVersionImpl();
	}


Description:
//below code init resource properly
InputStream is = MyPaypalAuth.class.getResourceAsStream("/myresource/sdk_config.properties");
PayPalResource.initConfig(is);

I can see variable 'is' has initialized with byte stream. Also method initConfig(is) return object of OAuthTokenCredential which contain populated configurationMap & clientSecret but not clientID(why ?).

**Comment by juwlee** [comment]
OAuthTokenCredential is returned from [PayPalResource.initConfig()](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/rest/PayPalResource.java#L67) on which you can call getAccessToken(). I have updated [the docs](https://github.com/paypal/PayPal-Java-SDK#to-make-an-api-call) accordingly.

Also, OAuthTokenCredential can hold client ID as well as configurationMap & clientSecret. If it is not loaded while the other fields are, I would suggest checking your config file.

**Comment by kunalransing** [comment]
OAuthTokenCredential is returned from PayPalResource.initConfig() contain configurationMap which contain value for clientId, clientSecret. BUT OAuthTokenCredential has clientID,clientSecret etc as member fields out of which clientSecret,configurationMap (contain populated field clientID,clientSecret) has populated but member field of OAuthTokenCredential i.e clientID is NOT initialized.

So if my config file is not correct then how configurationMap contain all correct fields from my file ?

Second, oAuthTokenCredential.getAccessToken() return error as invalid credentials since when it call code(check below)...clientID is null(<b>I know reason & explained reason at end</b>)
	private String generateAccessToken() throws PayPalRESTException 
        {
		String generatedToken = null;
		String base64ClientID = generateBase64String(clientID + ":"
				+ clientSecret);
		generatedToken = generateOAuthToken(base64ClientID);
		return generatedToken;
	}

<b>Exception</b>: com.paypal.base.rest.PayPalRESTException: Error code : 401 with response : {"error":"invalid_client","error_description":"The client credentials are invalid"}

<b>Reason</b> : Reason is your config file contain name <b>'clientID'</b> (D is capital) but 
               <b>Constants.CLIENT_ID = "clientId" (d is small)</b>...so you configurationMap contain 'clientID'(D is capital) & you try to read by 'clientId'(d is small). Check below code -
	/**
	 * Return Client ID from configuration Map
	 */
	public static String getClientID() {
		return configurationMap.get(Constants.CLIENT_ID);
	}
        Constants.CLIENT_ID = "clientId" ;

**Comment by juwlee** [comment]
@kunalransing thanks for pointing that out. Fix has been released in v1.1.0 along with docs updates as well.
