### ISSUE TITLE
Store Credit Card support payer_id property

### ISSUE THREAD

**Issue by shiva-kalgudi** [paypal/PayPal-Java-SDK#66]
Following REST API documentation for storing credit card support property "payer_id". 
https://developer.paypal.com/docs/integration/direct/store-a-credit-card/

I don't find corresponding field in the CreditCard class (com.paypal.api.payments.CreditCard).. Please add the property.

**Comment by juwlee** [comment]
Yes, this is a [known issue](http://stackoverflow.com/questions/27355983/cannot-assign-a-payer-id-when-saving-a-card-to-the-vault). It will be added in the next release.

**Comment by juwlee** [comment]
Fix was released in v1.1.0.
