### ISSUE TITLE
PayPalRESTException - Provide easier way to intercept message

### ISSUE THREAD

**Issue by shiva-kalgudi** [paypal/PayPal-Java-SDK#67]
Currently exception details are coming as string containing error code and json message. It will be nice if details can be exposed as separate properties, that will help SDK user to intercept the details without having to write custom error message parser. 

Error Example - Error code : 400 with response : {"name":"VALIDATION_ERROR","details":[{"field":"number","issue":"Value is invalid"}],"message":"Invalid request - see details","information_link":"https://developer.paypal.com/docs/api/#VALIDATION_ERROR","debug_id":"5c16c7e108c14"}

This message content can be split  to represent field for error code, error type, details, message and other fields..

**Comment by juwlee** [comment]
@shiva-kalgudi thanks for the suggestion. Would you like to submit a pull request for this enhancement?

**Comment by jziaja** [comment]
Just for reference, the .NET SDK wraps these kinds of exceptions as a [PaymentsException](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Exception/PaymentsException.cs) object with a [Details](https://github.com/paypal/PayPal-NET-SDK/blob/master/Source/SDK/Exception/PaymentsException.cs#L12) property containing quick access to the error details.

**Comment by shiva-kalgudi** [comment]
Thanks, shared link provided me quick-start. 

I did analysis of the required changes. I am able to enhance the PayPalRESTException to provide additional information about error. My current implementation handles Payments Exception only. 

Need clarification on the following to continue further on the changes.
1. Ideally we should have at least 2 exceptions to handle 2 types of errors - One for payments and one for Identity. Introducing these 2 new exceptions are going to be breaking changes. Is it fine to introduce new changes 
  a.  PaymentsException from PayPalResouce
  b. IdentityException from OAuthTokenCredential

2. Currently representation of payments error and identity errors are defined with same class name. It is better to differentiate identity error object.

**Comment by jaypatel512** [comment]
Hey @shiva-kalgudi ! 

Let me know if you need any help with the pull request.

**Comment by shiva-kalgudi** [comment]
Thx.. Will send pull request shortly..

**Comment by shiva-kalgudi** [comment]
I have created pull request.. Please check..

**Comment by juwlee** [comment]
@shiva-kalgudi thanks for PR. It has been merged.
