### ISSUE TITLE
RelatedResources doesn't have an Order transaction?

### ISSUE THREAD

**Issue by richardrega** [paypal/PayPal-Java-SDK#68]
https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/api/payments/RelatedResources.java

	/**
	 * An order transaction
	 */
	private Authorization authorization;

https://developer.paypal.com/docs/integration/direct/create-process-order/#create-the-order
"Executing an order results in an Order ID (in the related_resources container)."

I can see this transaction id in my raw JSON response, but my Java code doesn't have it by the time it gets to my application?

All I see is an empty relatedResources inside my transactions inside my Payment object.

**Comment by richardrega** [comment]
I just added my own

"private Order order;"

to confirm that is all that is needed to collect the Order transaction id.  I'm new to GitHub, so I don't really know the official way of submitting a patch and requesting this be added to the master.

**Comment by juwlee** [comment]
@richardrega thanks for letting us know about this. It has been fixed in v1.1.0.

To submit a patch, please see [github pull request docs](https://help.github.com/articles/using-pull-requests/) and feel free to submit one any time!
