### ISSUE TITLE
Version numbers in pom.xml in main project and rest-api-sample needs updating

### ISSUE THREAD

**Issue by uromahn** [paypal/PayPal-Java-SDK#70]
The latest version number of the main API is 1.0.0. However, the version numbers in the main pom.xml as well as in the rest-api-sample pom.xml still has 0.12.2. I believe those versions should also be updated to 1.0.0 to be consistent.

**Comment by juwlee** [comment]
Thanks @uromahn . It has been fixed in v1.1.0.
