### ISSUE TITLE
Error in App Engine after introduce log4j2

### ISSUE THREAD

**Issue by Markenson** [paypal/PayPal-Java-SDK#72]
Hi,

0.12.2 version of PayPal-java-SDK was working fine. Since 1.0.0 version the following error occurs in App Engine deployed application (local development [dev server] works fine) when calling OAuthTokenCredential.generateOAuthToken():

java.lang.NoClassDefFoundError: Could not initialize class com.paypal.base.DefaultHttpConnection

Regards,
Markenson

**Comment by juwlee** [comment]
Same issue as #63 . I am closing this.
