### ISSUE TITLE
WebProfile getList doesn't return List of Web Profile objects. Instead gson internal StringMap is returned.

### ISSUE THREAD

**Issue by mpateiru** [paypal/PayPal-Java-SDK#74]
Following Rest API documentation says, API returns a web_profile_list object that contains the list of all the profiles (with details) that the merchant owns. However when WebProfile.getList(apicontext) method is called, it returns list of gson internal StringMap objects instead of WebProfile object List.

https://developer.paypal.com/docs/api/#list-web-experience-profiles

Reason seems to be, parameter passed to configureAndExecute method from getList(). As of now "new ArrayList().getClass()" is passed to configureAndExecute method. When it is changed to "WebProfileList.class", this method returns List of WebProfile objects.

**Comment by juwlee** [comment]
@mpateiru thanks for bringing it to our attention. Would you send a pull request for the fix?

**Comment by mpateiru** [comment]
@juwlee  I will do it, however since this is my first time, are there any guidelines on how to pull request for fix. I have made the changes and testng passing it correctly. If you can quickly guide, it would be helpful.

**Comment by juwlee** [comment]
Please see [Github pull request guide](https://help.github.com/articles/using-pull-requests/). I will review it when submitted.

**Comment by mpateiru** [comment]
@juwlee  Thanks. I have submitted Pull request.

**Comment by juwlee** [comment]
@mpateiru thanks for your contribution. I have reviewed and merged the PR. Closing this issue.
