### ISSUE TITLE
Payment "update" and HttpMethod.PATCH not supported?

### ISSUE THREAD

**Issue by richardrega** [paypal/PayPal-Java-SDK#78]
https://developer.paypal.com/docs/api/#update-a-payment-resource

I'm trying to change the fine details of a Payment after its creation using the id.  The documentation says I'm allowed to change the amount or the shipping address.

What I'd really like to do is update the invoice number of a Transaction inside the Payment, but, either way, I don't see a way to update anything in a Payment.

When I look at Payment.java I only see create() [HttpMethod.GET] and execute() [HttpMethod.POST].  There is no function that calls HttpMethod.PATCH.

How are we supposed to update Payments using the Java-SDK?

**Comment by jaypatel512** [comment]
Hey @richardrega ! I saw that there are no update methods for payment. I have already started to work on this, and will be available soon. Thank you so much for creating an issue notifying us of this. 

I will update this issue once the update method is ready and released.
