### ISSUE TITLE
Credit card payments without CVV fail consistently

### ISSUE THREAD

**Issue by dleshem** [paypal/PayPal-Java-SDK#82]
CreditCard.java defines the private cvv2 member as int so it gets a default value of 0.

Since it's ok for CVVs to not be specified, a better approach would be to define the cvv2 member as either Integer or String, and correctly handle the null case.

Right now it's impossible to use this library for direct credit card clearing for merchants that do not require a CVV, which is a very common use case.

**Comment by juwlee** [comment]
@dleshem have you tried curl to see if API does not complain about no CVV?

**Comment by dleshem** [comment]
No, but the [API's Credit Card object](https://developer.paypal.com/docs/api/#creditcard-object) doesn't mark the cvv2 field as required, and takes it as String.

Wouldn't it be easier to ask your API folks rather than your users? :)

**Comment by juwlee** [comment]
@dleshem we have tested 0 CVV and no CVV at all but they all passed. It would help if you could try curl  because the behavior might be different for your credit card that does not have CVV.

Also, please always feel free to submit pull request. :)

**Comment by dleshem** [comment]
When I use my personal credit card without explicitly specifying the cvv (for which your Java client implicitly sends 0) the transaction is rejected and I immediately get an SMS from my credit card provider that it failed due to wrong cvv.

Explicitly specifying the correct cvv works.

**Comment by juwlee** [comment]
Just to make sure, is your [credit card supported](https://developer.paypal.com/webapps/developer/docs/integration/direct/rest_api_payment_country_currency_support/#direct-credit-card-payments)?

**Comment by dleshem** [comment]
Yes, it's a standard visa card, and the account is a US business account. Like I wrote, when I explicitly specify the cvv it works.

Seriously, you're over thinking this. The bug is obvious - you're sending 0 instead of not sending anything because you use an int instead of Integer.

**Comment by juwlee** [comment]
This has been fixed in v1.1.2. The type was changed from int to Integer not to break existing integration but, at the same time, to provide a way to specify empty CVV. Thanks for pointing this out @dleshem

**Comment by dleshem** [comment]
Thanks! Is 1.1.2 available through Maven? The latest I see there is 1.1.0 released Jan 26, 2015.

**Comment by juwlee** [comment]
@dleshem yes, [here](http://search.maven.org/#artifactdetails%7Ccom.paypal.sdk%7Crest-api-sdk%7C1.1.2%7Cjar) it is.
