### ISSUE TITLE
incorrect artifact descriptor, Failure to find com.paypal.sdk:rest-api:pom:1.1.1

### ISSUE THREAD

**Issue by aarohi** [paypal/PayPal-Java-SDK#83]
LATEST 1.1.1 release breaks builds, artifact resp-api-sdk has a unresolved parent rest-api artifact. There's no such artifact in maven central. We had to downgrade to v1.1.0 for builds to work.

**Comment by juwlee** [comment]
This has been also fixed in v1.1.2. The parent artifact is not published, just rest-api-sdk is.
