### ISSUE TITLE
WebProfile.getList throws ClassCastException

### ISSUE THREAD

**Issue by krico** [paypal/PayPal-Java-SDK#85]
```java
return PayPalResource.configureAndExecute(apiContext, HttpMethod.GET, resourcePath, payLoad, new ArrayList<WebProfile>().getClass());
```

`new ArrayList<WebProfile>().getClass()` is wrong here.  You need to provide a Type to GSON... In the lines of

```java
  Type tyeType = new TypeToken<ArrayList<WebProfile>>() {
        }.getType();
```

Did anyone ever test this method?

**Comment by juwlee** [comment]
@krico thanks for reporting. In terms of the type vs. class, [GSON library does take class as well as type](http://google-gson.googlecode.com/svn-history/trunk/gson/docs/javadocs/index.html). SDK uses [a wrapper for JSON which passes through class](https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/base/rest/JSONFormatter.java#L78).

Please try the latest version which has getList() return type fix. Let us know if if the issue persists.
