### ISSUE TITLE
RelatedResources missing get/set methods for Order object

### ISSUE THREAD

**Issue by richardrega** [paypal/PayPal-Java-SDK#86]
I pulled the latest master and discovered some old code broke.

https://github.com/paypal/PayPal-Java-SDK/blob/master/rest-api-sdk/src/main/java/com/paypal/api/payments/RelatedResources.java

is missing get() and set() functions for the private Order variable.

https://github.com/richardrega/PayPal-Java-SDK/commit/76cccf785d553c6f1bd229e15144c10c45250bf6#diff-9bc9a3d1e6c89650615eeb48b5871544

I compiled my own jar and fixed it on my fork, but you guys should update this if it isn't already fixed somewhere else.

**Comment by jziaja** [comment]
Hi @richardrega, if you already have the fix made in your fork, would you mind making a pull request to this repo so we can apply the fix?  Thanks!

**Comment by richardrega** [comment]
I posted those links inside this issue because I don't know how to push anything to this repo (I don't have that kind of permission).  I can pull on the master and commit to my local repo, but I don't understand what you want me to do after that...

**Comment by richardrega** [comment]
https://github.com/paypal/PayPal-Java-SDK/pull/87

OK so I think I found what you suggested, but I'm unsure if there is something else I need to do.
