### ISSUE TITLE
FileNotFoundException when Eclipse project resides in a directory containing spaces

### ISSUE THREAD

**Issue by ARyan2812** [paypal/PayPal-Java-SDK#92]
Hi,

I am developing a Java webapp in Eclipse Luna (on Windows 7) which uses the PayPal SDK as a dependency. The file path to my sdk_config.properties file is something like the following:

_C:\workspace\my project\stuff\sdk_config.properties_
(The actual path isn't relevant, it is the fact that there is whitespace in the path that is relevant)

When processing a credit card payment, the _ResourceLoader.searchResourcepath()_ method creates a file with an escaped path as follows:

_C:\workspace\my%20project\stuff\sdk_config.properties_

Then when _ResourceLoader.urlToFile()_ is called, the file is created using the escaped **String** (not the **URL**). I have 2 suggestions that may be better for this scenario:
1. Change "return new File(externalForm.substring(5))"
    to "return new File(res.toURI())"
2. Change "return new File(externalForm.substring(5))"
    to "return new File(URLDecoder.decode(externalForm.substring(5), "UTF-8"))"

I have tested both suggestions, and both work fine, however I believe suggestion 1 carries less risk, so I have used this one for the time being.

Thanks,
Adam

**Comment by ARyan2812** [comment]
The other alternative to one of the suggested solutions above would be to include in the documentation somewhere that the path cannot contain whitespace characters

**Comment by juwlee** [comment]
@ARyan2812 thanks for letting us know. Fix was checked in 4f6c476
