### ISSUE TITLE
Get access token fail in version 1.2.1

### ISSUE THREAD

**Issue by Freddan78** [paypal/PayPal-Java-SDK#99]
Hi,

I'm using the following code to get an access token.

````java
Map<String, String> sdkConfig = new HashMap<>();
sdkConfig.put(Constants.ENDPOINT, "https://api.sandbox.paypal.com/");
sdkConfig.put(Constants.HTTP_CONNECTION_TIMEOUT, "30000");
sdkConfig.put(Constants.HTTP_CONNECTION_READ_TIMEOUT,  "30000");
sdkConfig.put(Constants.HTTP_CONNECTION_MAX_CONNECTION, "20");
sdkConfig.put(Constants.HTTP_CONNECTION_RETRY, "0");
                
String payPalClientId = ...
String payPalClientSecret = ...
                
OAuthTokenCredential oAuthTokenCredential = new OAuthTokenCredential(payPalClientId, payPalClientSecret, sdkConfig);
String accessToken = oAuthTokenCredential.getAccessToken();
````

This code worked fine in version 1.2.0 of the REST API SDK, but when I updated to version 1.2.1 it stopped working.

I get a `java.io.IOException: Resource 'sdk_config.properties' could not be found.`

I found that `SSLUtil` wants to load the configuration via `ConfigManager`. This was not the case in 1.2.0. 

Could you please fix the SDK so that `sdk_config.properties` is not needed? As it was in 1.2.0. 

Regards,
Fredrik Johansson

**Comment by jziaja** [comment]
Hi @Freddan78, thanks for reporting this - we'll get this fixed in the upcoming release.  Ideally, anything that worked with version 1.2.0 should continue to work with future 1.2.x versions.

**Comment by Freddan78** [comment]
Do you know when the next release will be available?

**Comment by jziaja** [comment]
It should be coming very soon both in this SDK and the Java Core SDK (where this issue was [also reported](https://github.com/paypal/sdk-core-java/issues/53)).

**Comment by tankchintan** [comment]
@jziaja Is this release yet?

**Comment by jaypatel512** [comment]
https://github.com/paypal/PayPal-Java-SDK/releases/tag/v1.2.2 has the fix now. Sorry for the delay.
